// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package management

import (
	"github.com/deploymenttheory/go-api-sdk-apple/device_management/ddm"
)

// ByDeclarationType maps declaration type identifiers to payload factories.
// Factories return zero payloads ready to populate or decode into.
var ByDeclarationType = map[string]func() ddm.DeclarationPayload{
	"com.apple.management.organization-info":   func() ddm.DeclarationPayload { return new(OrganizationInfo) },
	"com.apple.management.properties":          func() ddm.DeclarationPayload { return new(Properties) },
	"com.apple.management.server-capabilities": func() ddm.DeclarationPayload { return new(ServerCapabilities) },
}
