// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package activations

import (
	"github.com/deploymenttheory/go-api-sdk-apple/device_management/ddm"
)

// ByDeclarationType maps declaration type identifiers to payload factories.
// Factories return zero payloads ready to populate or decode into.
var ByDeclarationType = map[string]func() ddm.DeclarationPayload{
	"com.apple.activation.simple": func() ddm.DeclarationPayload { return new(Simple) },
}
