// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// AccountConfiguration — Account Configuration Command.
// Create and configure a local administrator account on a device.
//
// Supported: macOS 10.11+.
type AccountConfiguration struct {
	// If `true`, Setup Assistant skips the user interface for setting up primary accounts and disables
	// autologin. If `true`, you must specify a value for `AutoSetupAdminAccounts`.
	//
	// Default: false.
	SkipPrimarySetupAccountCreation *bool `plist:"SkipPrimarySetupAccountCreation,omitempty" json:"SkipPrimarySetupAccountCreation,omitempty"`
	// If `true`, Setup Assistant creates the primary accounts as regular users, and you must specify a
	// value for `AutoSetupAdminAccounts`.
	//
	// Default: false.
	SetPrimarySetupAccountAsRegularUser *bool `plist:"SetPrimarySetupAccountAsRegularUser,omitempty" json:"SetPrimarySetupAccountAsRegularUser,omitempty"`
	// The full name for the primary account. If present, Setup Assistant uses this value to prefill
	// the Full Name field. However, Setup Assistant ignores this value if
	// `DontAutoPopulatePrimaryAccountInfo` is `true`. This value is available in macOS 10.15 and
	// later.
	PrimaryAccountFullName *string `plist:"PrimaryAccountFullName,omitempty" json:"PrimaryAccountFullName,omitempty"`
	// The account name for the primary account. If present, Setup Assistant uses this value to prefill
	// the User Name field. However, Setup Assistant ignores this value if
	// `DontAutoPopulatePrimaryAccountInfo` is `true`. This value is available in macOS 10.15 and
	// later.
	PrimaryAccountUserName *string `plist:"PrimaryAccountUserName,omitempty" json:"PrimaryAccountUserName,omitempty"`
	// If `true`, Setup Assistant ignores the primary account information and requires the user to
	// enter that information. If `false`, Setup Assistant prefills the Full Name field with
	// `PrimaryAccountFullName` and the User Name field with `PrimaryAccountUserName`. This value is
	// available in macOS 10.15 and later.
	//
	// Default: false.
	DontAutoPopulatePrimaryAccountInfo *bool `plist:"DontAutoPopulatePrimaryAccountInfo,omitempty" json:"DontAutoPopulatePrimaryAccountInfo,omitempty"`
	// If `true`, and you provide values for `PrimaryAccountFullName` or `PrimaryAccountUserName`,
	// Setup Assistant disables editing for the corresponding fields.
	// `DontAutoPopulatePrimaryAccountInfo` must also be 0 (or missing).
	//
	// Default: false.
	LockPrimaryAccountInfo *bool `plist:"LockPrimaryAccountInfo,omitempty" json:"LockPrimaryAccountInfo,omitempty"`
	// A dictionary that describes the administrator account to create with Setup Assistant, which uses
	// the first element and ignores additional elements.
	AutoSetupAdminAccounts []AccountConfigurationAutoSetupAdminAccountItem `plist:"AutoSetupAdminAccounts,omitempty" json:"AutoSetupAdminAccounts,omitempty"`
	// If present, this is the short name of the local account to manage, which can also be the account
	// that results from setting `AutoSetupAdminAccounts` to `true`. Otherwise, only the local account
	// that Setup Assistant creates is a managed account. This value is available in macOS 11 and
	// later.
	ManagedLocalUserShortName *string `plist:"ManagedLocalUserShortName,omitempty" json:"ManagedLocalUserShortName,omitempty"`
}

// AccountConfigurationAutoSetupAdminAccountItem is the AutoSetupAdminAccountItem dictionary.
// A dictionary that describes the administrator account to create with Setup Assistant, which uses
// the first element and ignores additional elements.
type AccountConfigurationAutoSetupAdminAccountItem struct {
	// The short name of the user.
	ShortName string `plist:"shortName" json:"shortName"`
	// The full name of the user, which defaults to `shortName` if not specified.
	FullName *string `plist:"fullName,omitempty" json:"fullName,omitempty"`
	// Data that contains the pre-created salted PBKDF2 SHA512 password hash for the account.
	PasswordHash []byte `plist:"passwordHash,omitempty" json:"passwordHash,omitempty"`
	// If `true`, this sets the account attribute to make the account hidden in the Login Window and
	// Users & Groups.
	//
	// Default: false.
	Hidden *bool `plist:"hidden,omitempty" json:"hidden,omitempty"`
}
