// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RemoveApplication — Remove Application Command.
// Remove an app.
//
// Supported: iOS 5.0+, macOS 11.0+, tvOS 10.2+, visionOS 1.1+, watchOS 10.0+.
type RemoveApplication struct {
	// The bundle identifier of the managed app.
	Identifier string `plist:"Identifier" json:"Identifier"`
}
