// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// ActiveNSExtensions — Active NSExtensions Command.
// Get a list of active extensions for a user on a device.
//
// Supported: macOS 10.13+.
type ActiveNSExtensions struct {
	// An array of extension points. If you choose to provide this value, the response only includes
	// the app extensions for the extension points you specify.
	FilterExtensionPoints []string `plist:"FilterExtensionPoints,omitempty" json:"FilterExtensionPoints,omitempty"`
}

// ActiveNSExtensionsResponse models the device response to the ActiveNSExtensions command.
type ActiveNSExtensionsResponse struct {
	// An array of dictionaries that contains information about active extensions on the device.
	Extensions []ActiveNSExtensionsResponseExtensionsItem `plist:"Extensions" json:"Extensions"`
}

// ActiveNSExtensionsResponseExtensionsItem is the ExtensionsItem dictionary.
// A dictionary that contains information about an extension.
type ActiveNSExtensionsResponseExtensionsItem struct {
	// The identifier of the extension.
	Identifier string `plist:"Identifier" json:"Identifier"`
	// The `NSExtensionPointIdentifier` for the extension.
	ExtensionPoint string `plist:"ExtensionPoint" json:"ExtensionPoint"`
	// The extension's display name.
	DisplayName string `plist:"DisplayName" json:"DisplayName"`
	// The display name of the container.
	ContainerDisplayName *string `plist:"ContainerDisplayName,omitempty" json:"ContainerDisplayName,omitempty"`
	// The identifier of the container.
	ContainerIdentifier *string `plist:"ContainerIdentifier,omitempty" json:"ContainerIdentifier,omitempty"`
	// The path to the extension.
	Path string `plist:"Path" json:"Path"`
	// The version of the extension.
	Version string `plist:"Version" json:"Version"`
	// The user-selected state of the extension, which a user sets in the Extensions preference pane in
	// System Preferences.
	UserElection ActiveNSExtensionsResponseExtensionsItemUserElection `plist:"UserElection" json:"UserElection"`
}
