// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for RemoveApplication.
func (RemoveApplication) RequestType() string { return "RemoveApplication" }

// Validate checks the payload against Apple's spec. RemoveApplication has no
// constraints beyond its field types.
func (p *RemoveApplication) Validate() error { return nil }
