// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for ApplyRedemptionCode.
func (ApplyRedemptionCode) RequestType() string { return "ApplyRedemptionCode" }

// Validate checks the payload against Apple's spec. ApplyRedemptionCode has no
// constraints beyond its field types.
func (p *ApplyRedemptionCode) Validate() error { return nil }
