// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// CancelEnhancedLogCollection — Cancel Enhanced Log Collection Command.
// Cancel enhanced log collection on the device.
//
// Supported: iOS 27.0+, macOS 27.0+, tvOS 27.0+.
type CancelEnhancedLogCollection struct {
}
