// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// CertificateList — Certificate List Command.
// Get a list of installed certificates on a device.
//
// Supported: iOS 4.0+, macOS 10.7+, tvOS 9.0+, visionOS 1.1+, watchOS 10.0+.
type CertificateList struct {
	// If `true`, only include certificates that MDM installed or that are in the same profile as the
	// MDM payload. User-enrolled devices ignore this value and always only include managed
	// certificates. This value is available in iOS 13 and later, macOS 10.15 and later, and tvOS 13
	// and later.
	//
	// Default: false.
	ManagedOnly *bool `plist:"ManagedOnly,omitempty" json:"ManagedOnly,omitempty"`
}

// CertificateListResponse models the device response to the CertificateList command.
type CertificateListResponse struct {
	// An array of certificate list items that describes each certificate.
	CertificateList []CertificateListResponseCertificateListItem `plist:"CertificateList" json:"CertificateList"`
}

// CertificateListResponseCertificateListItem is the CertificateListItem dictionary.
// A dictionary that contains information about a certificate list item.
type CertificateListResponseCertificateListItem struct {
	// The certificate's common name.
	CommonName string `plist:"CommonName" json:"CommonName"`
	// If `true`, this is an identity certificate.
	IsIdentity bool `plist:"IsIdentity" json:"IsIdentity"`
	// The certificate in DER-encoded X.509 format.
	Data []byte `plist:"Data" json:"Data"`
}
