// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// DeviceConfigured — Device Configured Command.
// Inform the device that it can allow the user to continue in Setup Assistant.
//
// Supported: iOS 9.0+, macOS 10.11+, tvOS 10.2+, visionOS 2.0+.
type DeviceConfigured struct {
}
