// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for EnableLostMode.
func (EnableLostMode) RequestType() string { return "EnableLostMode" }

// Validate checks the payload against Apple's spec. EnableLostMode has no
// constraints beyond its field types.
func (p *EnableLostMode) Validate() error { return nil }
