// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for DeviceLocation.
func (DeviceLocation) RequestType() string { return "DeviceLocation" }

// Validate checks the payload against Apple's spec. DeviceLocation has no
// constraints beyond its field types.
func (p *DeviceLocation) Validate() error { return nil }

// Validate checks the payload against Apple's spec. DeviceLocationResponse has no
// constraints beyond its field types.
func (p *DeviceLocationResponse) Validate() error { return nil }
