// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for ClearRestrictionsPassword.
func (ClearRestrictionsPassword) RequestType() string { return "ClearRestrictionsPassword" }

// Validate checks the payload against Apple's spec. ClearRestrictionsPassword has no
// constraints beyond its field types.
func (p *ClearRestrictionsPassword) Validate() error { return nil }
