// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for ClearActivationLockBypassCode.
func (ClearActivationLockBypassCode) RequestType() string { return "ClearActivationLockBypassCode" }

// Validate checks the payload against Apple's spec. ClearActivationLockBypassCode has no
// constraints beyond its field types.
func (p *ClearActivationLockBypassCode) Validate() error { return nil }
