// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// DeviceLocation — Device Location Command.
// Request the location of a device when in Lost Mode.
//
// Supported: iOS 9.3+.
type DeviceLocation struct {
}

// DeviceLocationResponse models the device response to the DeviceLocation command.
type DeviceLocationResponse struct {
	// The latitude of the device's location.
	Latitude float64 `plist:"Latitude" json:"Latitude"`
	// The longitude of the device's location.
	Longitude float64 `plist:"Longitude" json:"Longitude"`
	// The radius of uncertainty for the location in meters, which is a negative value if the
	// horizontal accuracy is unknown.
	HorizontalAccuracy float64 `plist:"HorizontalAccuracy" json:"HorizontalAccuracy"`
	// The accuracy of the altitude value in meters, which is a negative value if the vertical accuracy
	// is unknown.
	VerticalAccuracy float64 `plist:"VerticalAccuracy" json:"VerticalAccuracy"`
	// The altitude of the device's location, which is a negative value if the altitude is unknown.
	Altitude float64 `plist:"Altitude" json:"Altitude"`
	// The speed of the device in meters per second, which is a negative value if the speed is unknown.
	Speed float64 `plist:"Speed" json:"Speed"`
	// The direction the device is traveling, which is a negative value if the course is unknown.
	Course float64 `plist:"Course" json:"Course"`
	// The RFC 3339 timestamp of when the server determines the location of the device.
	Timestamp string `plist:"Timestamp" json:"Timestamp"`
}
