// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// ShutDownDevice — Shut Down Device Command.
// Remotely and immediately shut down a device.
//
// Supported: iOS 10.3+, macOS 10.13+.
type ShutDownDevice struct {
}
