// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// SecurityInfo — Security Info Command.
// Get security-related information about a device.
//
// Supported: iOS 4.0+, macOS 10.7+, tvOS 9.0+, visionOS 1.1+, watchOS 10.0+.
type SecurityInfo struct {
}

// SecurityInfoResponse models the device response to the SecurityInfo command.
type SecurityInfoResponse struct {
	// A dictionary that contains security-related information.
	SecurityInfo SecurityInfoResponseSecurityInfo `plist:"SecurityInfo" json:"SecurityInfo"`
}

// SecurityInfoResponseSecurityInfoFirewallSettingsApplicationsItem is the ApplicationsItem dictionary.
// A dictionary that describes the allowed apps.
type SecurityInfoResponseSecurityInfoFirewallSettingsApplicationsItem struct {
	// If `true`, the app is an allowed app.
	Allowed *bool `plist:"Allowed,omitempty" json:"Allowed,omitempty"`
	// The app's bundle identifier.
	BundleID *string `plist:"BundleID,omitempty" json:"BundleID,omitempty"`
	// The app's display name if it's determinable from the `BundleID`.
	Name *string `plist:"Name,omitempty" json:"Name,omitempty"`
}

// SecurityInfoResponseSecurityInfoFirewallSettings is the FirewallSettings dictionary.
// A dictionary that contains the firewall settings. This value is available in macOS 10.12 and
// later.
type SecurityInfoResponseSecurityInfoFirewallSettings struct {
	// If `true`, the firewall is on.
	FirewallEnabled *bool `plist:"FirewallEnabled,omitempty" json:"FirewallEnabled,omitempty"`
	// If `true`, the firewall blocks all incoming connections.
	BlockAllIncoming *bool `plist:"BlockAllIncoming,omitempty" json:"BlockAllIncoming,omitempty"`
	// If true, stealth mode is active for the firewall.
	StealthMode *bool `plist:"StealthMode,omitempty" json:"StealthMode,omitempty"`
	// An array of dictionaries that describes the allowed applications.
	Applications []SecurityInfoResponseSecurityInfoFirewallSettingsApplicationsItem `plist:"Applications,omitempty" json:"Applications,omitempty"`
	// If `true`, logging is enabled.
	LoggingEnabled *bool `plist:"LoggingEnabled,omitempty" json:"LoggingEnabled,omitempty"`
	// The type of logging emitted by the firewall.
	LoggingOption *SecurityInfoResponseSecurityInfoFirewallSettingsLoggingOption `plist:"LoggingOption,omitempty" json:"LoggingOption,omitempty"`
}

// SecurityInfoResponseSecurityInfoFirmwarePasswordStatus is the FirmwarePasswordStatus dictionary.
// A dictionary that contains the status of the EFI firmware password. This value is available in
// macOS 10.13 and later.
type SecurityInfoResponseSecurityInfoFirmwarePasswordStatus struct {
	// If `true`, the device has an EFI firmware password.
	PasswordExists *bool `plist:"PasswordExists,omitempty" json:"PasswordExists,omitempty"`
	// If `true`, a firmware password change is pending. A device restart is necessary for this change
	// to take effect. Until then, additional attempts to change the password fail.
	ChangePending *bool `plist:"ChangePending,omitempty" json:"ChangePending,omitempty"`
	// If `true`, enable ROMs.
	AllowOroms *bool `plist:"AllowOroms,omitempty" json:"AllowOroms,omitempty"`
}

// SecurityInfoResponseSecurityInfoManagementStatus is the ManagementStatus dictionary.
// A dictionary that contains the status of the device's MDM enrollment.
type SecurityInfoResponseSecurityInfoManagementStatus struct {
	// If `true`, the device enrolled in MDM through the Device Enrollment Program (DEP). This value is
	// available in macOS 10.13.2 and later.
	EnrolledViaDEP *bool `plist:"EnrolledViaDEP,omitempty" json:"EnrolledViaDEP,omitempty"`
	// If `true`, the enrollment was user-approved. If `false`, the device may reject certain
	// security-sensitive payloads or commands. This value is available in macOS 10.13.2 and later.
	UserApprovedEnrollment *bool `plist:"UserApprovedEnrollment,omitempty" json:"UserApprovedEnrollment,omitempty"`
	// If `true`, the device is user-enrolled. This value is available in iOS 13 and later, and macOS
	// 10.15 and later.
	IsUserEnrollment *bool `plist:"IsUserEnrollment,omitempty" json:"IsUserEnrollment,omitempty"`
	// If `true`, the type of enrollment allows the MDM to manage Activation Lock for this device. This
	// value is available in macOS 10.15 and later.
	IsActivationLockManageable *bool `plist:"IsActivationLockManageable,omitempty" json:"IsActivationLockManageable,omitempty"`
}

// SecurityInfoResponseSecurityInfoSecureBoot is the SecureBoot dictionary.
// A dictionary that contains the device's Secure Boot settings. This value is available in macOS
// 10.15 and later.
type SecurityInfoResponseSecurityInfoSecureBoot struct {
	// The security level for the bootable operating system versions.
	SecureBootLevel *SecurityInfoResponseSecurityInfoSecureBootSecureBootLevel `plist:"SecureBootLevel,omitempty" json:"SecureBootLevel,omitempty"`
	// The device's external boot level, which indicates whether it allows booting from an external
	// device, disallows it, or doesn't support it.
	ExternalBootLevel *SecurityInfoResponseSecurityInfoSecureBootExternalBootLevel `plist:"ExternalBootLevel,omitempty" json:"ExternalBootLevel,omitempty"`
	// Reports which security features the user disables in `recoveryOS`. This property is only present
	// for a Mac with Apple silicon when `SecureBootLevel` is `medium`.
	ReducedSecurity []string `plist:"ReducedSecurity,omitempty" json:"ReducedSecurity,omitempty"`
}

// SecurityInfoResponseSecurityInfo is the SecurityInfo dictionary.
// A dictionary that contains security-related information.
type SecurityInfoResponseSecurityInfo struct {
	// An integer that indicates the underlying hardware encryption capabilities of the device, which
	// is one of the following values:
	HardwareEncryptionCaps *int64 `plist:"HardwareEncryptionCaps,omitempty" json:"HardwareEncryptionCaps,omitempty"`
	// If `true`, the device has a passcode. This key doesn't apply to User-Enrolled devices. This
	// value is available in iOS 4 and later, and tvOS 6 and later.
	PasscodePresent *bool `plist:"PasscodePresent,omitempty" json:"PasscodePresent,omitempty"`
	// If `true`, the user's passcode is compliant with all requirements on the device, including
	// Exchange and other accounts. This value is available in iOS 4 and later, and tvOS 6 and later.
	PasscodeCompliant *bool `plist:"PasscodeCompliant,omitempty" json:"PasscodeCompliant,omitempty"`
	// If `true`, the user's passcode is compliant with requirements from profiles. This key doesn't
	// apply to User-Enrolled devices. This value is available in iOS 4 and later, and tvOS 6 and
	// later.
	PasscodeCompliantWithProfiles *bool `plist:"PasscodeCompliantWithProfiles,omitempty" json:"PasscodeCompliantWithProfiles,omitempty"`
	// The user preference for the number of seconds before a locked screen requires the device
	// passcode to unlock it. This value is only available for Shared iPad.
	PasscodeLockGracePeriod *int64 `plist:"PasscodeLockGracePeriod,omitempty" json:"PasscodeLockGracePeriod,omitempty"`
	// The enforced value for the number of seconds before a locked screen requires the device passcode
	// to unlock it. If a device has a passcode, changing `PasscodeLockGracePeriod` to a larger value
	// doesn't take effect until the user logs out or removes the passcode. This value is only
	// available for Shared iPad.
	PasscodeLockGracePeriodEnforced *int64 `plist:"PasscodeLockGracePeriodEnforced,omitempty" json:"PasscodeLockGracePeriodEnforced,omitempty"`
	// The number of seconds before a device goes to sleep after being idle. This value is only
	// available on Shared iPad in iOS 17 and later.
	AutoLockTime *int64 `plist:"AutoLockTime,omitempty" json:"AutoLockTime,omitempty"`
	// If `true`, the device has enabled FileVault full disk encryption (FDE). This value is available
	// in macOS 10.9 and later.
	FDEEnabled *bool `plist:"FDE_Enabled,omitempty" json:"FDE_Enabled,omitempty"`
	// If `true`, FileVault FDE has a personal recovery key. This value is available in macOS 10.9 and
	// later.
	FDEHasPersonalRecoveryKey *bool `plist:"FDE_HasPersonalRecoveryKey,omitempty" json:"FDE_HasPersonalRecoveryKey,omitempty"`
	// If `true`, FileVault FDE has an institutional recovery key. This value is available in macOS
	// 10.9 and later.
	FDEHasInstitutionalRecoveryKey *bool `plist:"FDE_HasInstitutionalRecoveryKey,omitempty" json:"FDE_HasInstitutionalRecoveryKey,omitempty"`
	// If the FileVault personal recovery key has enabled escrow with a recovery key, this value
	// contains the key. The certificate from the `FDERecoveryKeyEscrow` profile encrypts the key and
	// wraps it as CMS data. This value is available in macOS 10.13 and later.
	FDEPersonalRecoveryKeyCMS []byte `plist:"FDE_PersonalRecoveryKeyCMS,omitempty" json:"FDE_PersonalRecoveryKeyCMS,omitempty"`
	// If the FileVault personal recovery key has enabled escrow with a recovery key, this value is the
	// device serial number. This is the value that displays to the user at the EFI Login Window as
	// part of the help message if they enter their password incorrectly three times. The server also
	// uses this value as an index when saving the device personal recovery key. This replaces the
	// `recordNumber` that the server returned in the previous escrow mechanism. This value is
	// available in macOS 10.13 and later.
	FDEPersonalRecoveryKeyDeviceKey *string `plist:"FDE_PersonalRecoveryKeyDeviceKey,omitempty" json:"FDE_PersonalRecoveryKeyDeviceKey,omitempty"`
	// If `true`, System Integrity Protection (SIP) is active on the device. This value is available in
	// macOS 10.12 and later.
	SystemIntegrityProtectionEnabled *bool `plist:"SystemIntegrityProtectionEnabled,omitempty" json:"SystemIntegrityProtectionEnabled,omitempty"`
	// A dictionary that contains the firewall settings. This value is available in macOS 10.12 and
	// later.
	FirewallSettings *SecurityInfoResponseSecurityInfoFirewallSettings `plist:"FirewallSettings,omitempty" json:"FirewallSettings,omitempty"`
	// A dictionary that contains the status of the EFI firmware password. This value is available in
	// macOS 10.13 and later.
	FirmwarePasswordStatus *SecurityInfoResponseSecurityInfoFirmwarePasswordStatus `plist:"FirmwarePasswordStatus,omitempty" json:"FirmwarePasswordStatus,omitempty"`
	// A dictionary that contains the status of the device's MDM enrollment.
	ManagementStatus *SecurityInfoResponseSecurityInfoManagementStatus `plist:"ManagementStatus,omitempty" json:"ManagementStatus,omitempty"`
	// A dictionary that contains the device's Secure Boot settings. This value is available in macOS
	// 10.15 and later.
	SecureBoot *SecurityInfoResponseSecurityInfoSecureBoot `plist:"SecureBoot,omitempty" json:"SecureBoot,omitempty"`
	// If `true`, Remote Desktop is active on the device. This value is available in macOS 10.14.4 and
	// later.
	RemoteDesktopEnabled *bool `plist:"RemoteDesktopEnabled,omitempty" json:"RemoteDesktopEnabled,omitempty"`
	// If `true`, the system booted using an Authenticated Root Volume. This value is available in
	// macOS 11 and later.
	AuthenticatedRootVolumeEnabled *bool `plist:"AuthenticatedRootVolumeEnabled,omitempty" json:"AuthenticatedRootVolumeEnabled,omitempty"`
	// This value specifies whether the Secure Enclave Processor (SEP) supports and allows secure
	// operations to use the Bootstrap Token. The value is automatically set for devices enrolled
	// through the Device Enrollment Program (DEP). The user can also manually set this value in the
	// RecoveryOS.
	BootstrapTokenAllowedForAuthentication *SecurityInfoResponseSecurityInfoBootstrapTokenAllowedForAuthentication `plist:"BootstrapTokenAllowedForAuthentication,omitempty" json:"BootstrapTokenAllowedForAuthentication,omitempty"`
	// If `true`, the device can accept a Bootstrap Token from the MDM server instead of prompting for
	// user authentication prior to installation. This only applies when
	// `BootstrapTokenAllowedForAuthentication` is `true` in the `SecurityInfo` response.
	BootstrapTokenRequiredForSoftwareUpdate *bool `plist:"BootstrapTokenRequiredForSoftwareUpdate,omitempty" json:"BootstrapTokenRequiredForSoftwareUpdate,omitempty"`
	// If `true`, the device can accept a Bootstrap Token from the MDM server instead of prompting for
	// user authentication prior to enabling kernel extensions. This includes enabling kexts through
	// the `com.apple.syspolicy.kernel-extension-policy` payload or triggering the `RestartDevice`
	// command with `RebuildKernelCache` set to `true`. This only applies when
	// `BootstrapTokenAllowedForAuthentication` is `true` in the `SecurityInfo` response.
	BootstrapTokenRequiredForKernelExtensionApproval *bool `plist:"BootstrapTokenRequiredForKernelExtensionApproval,omitempty" json:"BootstrapTokenRequiredForKernelExtensionApproval,omitempty"`
	// If `true`, a password is required to enter recovery (see `SetRecoveryLockCommand`). Available in
	// macOS 11.5 and later and only on a Mac with Apple silicon.
	IsRecoveryLockEnabled *bool `plist:"IsRecoveryLockEnabled,omitempty" json:"IsRecoveryLockEnabled,omitempty"`
}
