// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

import (
	"time"
)

// ContentCachingInformation — Content Caching Information Command.
// Get the status of the content caches on a device.
//
// Supported: macOS 10.15.4+.
type ContentCachingInformation struct {
}

// ContentCachingInformationResponse models the device response to the ContentCachingInformation command.
type ContentCachingInformationResponse struct {
	// A dictionary that contains the status of content caching on a device.
	StatusResponse ContentCachingInformationResponseStatusResponse `plist:"StatusResponse" json:"StatusResponse"`
}

// ContentCachingInformationResponseStatusResponseAlertsForPeerFilterRangesANYIndex is the ANY index dictionary.
// A dictionary that describes the alerts for the peer filter ranges. The key name is the index
// into the `PeerFilterRanges` array in the installed `com.apple.AssetCache.managed` payload.
type ContentCachingInformationResponseStatusResponseAlertsForPeerFilterRangesANYIndex struct {
	// The type of the alert.
	ClassName string `plist:"className" json:"className"`
	// The date of the alert.
	PostDate time.Time `plist:"postDate" json:"postDate"`
	// The index into the `PeerFilterRanges` in the installed ContentCaching payload.
	PeerFilterRangeIndex int64 `plist:"peerFilterRangeIndex" json:"peerFilterRangeIndex"`
	// An array of local IP addresses of peer content caches that rejected requests from the content
	// cache.
	Addresses []string `plist:"addresses" json:"addresses"`
}

// ContentCachingInformationResponseStatusResponseAlertsForPeerFilterRanges is the AlertsForPeerFilterRanges dictionary.
// The error conditions the content cache detected in the `PeerFilterRanges` in the installed
// `com.apple.AssetCache.managed` payload.
type ContentCachingInformationResponseStatusResponseAlertsForPeerFilterRanges struct {
	// A dictionary that describes the alerts for the peer filter ranges. The key name is the index
	// into the `PeerFilterRanges` array in the installed `com.apple.AssetCache.managed` payload.
	ANYIndex ContentCachingInformationResponseStatusResponseAlertsForPeerFilterRangesANYIndex `plist:"ANY index" json:"ANY index"`
}

// ContentCachingInformationResponseStatusResponseAlertsItem is the AlertsItem dictionary.
// A dictionary that describes an alert from the content cache.
type ContentCachingInformationResponseStatusResponseAlertsItem struct {
	// The type of the alert.
	ClassName ContentCachingInformationResponseStatusResponseAlertsItemClassName `plist:"className" json:"className"`
	// The date of the alert.
	PostDate time.Time `plist:"postDate" json:"postDate"`
	// The limit, in bytes, for the content cache at the time of the alert. This value only applies to
	// `AssetCacheLowSpaceAlert` and `AssetCacheNoSpaceAlert` types.
	CacheLimit *int64 `plist:"cacheLimit,omitempty" json:"cacheLimit,omitempty"`
	// The space, in bytes, that the system reserves at the time of the alert. This value only applies
	// to the `AssetCacheLowSpaceAlert` and `AssetCacheNoSpaceAlert` types.
	ReservedVolumeSpace *int64 `plist:"reservedVolumeSpace,omitempty" json:"reservedVolumeSpace,omitempty"`
	// The resource that was missing or inaccessible at the time of the alert. This value only applies
	// to the `AssetCacheResourceMissingAlert` type.
	Resource *string `plist:"resource,omitempty" json:"resource,omitempty"`
	// The subpath of the resource that was missing or inaccessible at the time of the alert. This
	// value only applies to the `AssetCacheResourceMissingAlert` type.
	PathPreventingAccess *string `plist:"pathPreventingAccess,omitempty" json:"pathPreventingAccess,omitempty"`
}

// ContentCachingInformationResponseStatusResponseCacheDetails is the CacheDetails dictionary.
// The amount of disk space that various categories of cached content use. Apple defines these
// categories and they're subject to change.
type ContentCachingInformationResponseStatusResponseCacheDetails struct {
	// The amount of disk space, in bytes, that this category of cached content uses.
	CategoryName int64 `plist:"Category Name" json:"Category Name"`
}

// ContentCachingInformationResponseStatusResponseDataMigrationErrorUserInfo is the userInfo dictionary.
// A dictionary that contains additional information about the error.
type ContentCachingInformationResponseStatusResponseDataMigrationErrorUserInfo struct {
	// A dictionary that contains additional details about the error.
	ANY any `plist:"ANY,omitempty" json:"ANY,omitempty"`
}

// ContentCachingInformationResponseStatusResponseDataMigrationError is the DataMigrationError dictionary.
// The error that occurred while the content cache moved from one volume to another.
type ContentCachingInformationResponseStatusResponseDataMigrationError struct {
	// The error domain.
	Domain string `plist:"domain" json:"domain"`
	// The error code.
	Code int64 `plist:"code" json:"code"`
	// A dictionary that contains additional information about the error.
	UserInfo *ContentCachingInformationResponseStatusResponseDataMigrationErrorUserInfo `plist:"userInfo,omitempty" json:"userInfo,omitempty"`
}

// ContentCachingInformationResponseStatusResponseParentsItemAlert is the alert dictionary.
// A dictionary that describes an alert related to the parent content cache.
type ContentCachingInformationResponseStatusResponseParentsItemAlert struct {
	// The type of the alert.
	ClassName ContentCachingInformationResponseStatusResponseParentsItemAlertClassName `plist:"className" json:"className"`
	// The date of the alert.
	PostDate time.Time `plist:"postDate" json:"postDate"`
	// An array of local IP addresses of parent content caches.
	Addresses []string `plist:"addresses" json:"addresses"`
}

// ContentCachingInformationResponseStatusResponseParentsItemDetailsCapabilities is the capabilities dictionary.
// A dictionary that describes the capabilities of the parent content cache.
type ContentCachingInformationResponseStatusResponseParentsItemDetailsCapabilities struct {
	// If `true`, the parent content cache is capable of imports and uploads.
	//
	// Default: false.
	Im *bool `plist:"im,omitempty" json:"im,omitempty"`
	// If `true`, the parent content cache is capable of handling namespaces, which is an aspect of
	// personal caching.
	//
	// Default: false.
	Ns *bool `plist:"ns,omitempty" json:"ns,omitempty"`
	// If `true`, the parent content cache is capable of caching personal iCloud content.
	//
	// Default: false.
	Pc *bool `plist:"pc,omitempty" json:"pc,omitempty"`
	// If `true`, the parent content cache is capable of handling query parameters in URLs.
	//
	// Default: false.
	QueryParameters *bool `plist:"query-parameters,omitempty" json:"query-parameters,omitempty"`
	// If `true`, the parent content cache is capable of caching shared non-iCloud content.
	//
	// Default: false.
	Sc *bool `plist:"sc,omitempty" json:"sc,omitempty"`
	// If `true`, the parent content cache is capable of prioritizing imports and uploads.
	//
	// Default: false.
	Ur *bool `plist:"ur,omitempty" json:"ur,omitempty"`
}

// ContentCachingInformationResponseStatusResponseParentsItemDetailsLocalNetwork is the local-network dictionary.
// A dictionary that describes the parent content cache's connection to its local network.
type ContentCachingInformationResponseStatusResponseParentsItemDetailsLocalNetwork struct {
	// The transfer speed, in megabits per second, of the parent content cache's connection to its
	// local network.
	Speed *int64 `plist:"speed,omitempty" json:"speed,omitempty"`
	// If `true`, the parent content cache has a wired connection to its local network. If `false`, it
	// has a wireless connection; for example, Wi-Fi.
	//
	// Default: false.
	Wired *bool `plist:"wired,omitempty" json:"wired,omitempty"`
}

// ContentCachingInformationResponseStatusResponseParentsItemDetails is the details dictionary.
// A dictionary that contains additional details about the parent content cache.
type ContentCachingInformationResponseStatusResponseParentsItemDetails struct {
	// If `true`, the parent content cache power source is AC; otherwise, an internal battery provides
	// its power.
	//
	// Default: false.
	AcPower *bool `plist:"ac-power,omitempty" json:"ac-power,omitempty"`
	// The maximum amount of disk space, in bytes, available to the parent content cache.
	CacheSize *int64 `plist:"cache-size,omitempty" json:"cache-size,omitempty"`
	// A dictionary that describes the capabilities of the parent content cache.
	Capabilities *ContentCachingInformationResponseStatusResponseParentsItemDetailsCapabilities `plist:"capabilities,omitempty" json:"capabilities,omitempty"`
	// If `true`, the parent content cache computer is portable; for example, a laptop.
	//
	// Default: false.
	IsPortable *bool `plist:"is-portable,omitempty" json:"is-portable,omitempty"`
	// A dictionary that describes the parent content cache's connection to its local network.
	LocalNetwork *ContentCachingInformationResponseStatusResponseParentsItemDetailsLocalNetwork `plist:"local-network,omitempty" json:"local-network,omitempty"`
}

// ContentCachingInformationResponseStatusResponseParentsItem is the ParentsItem dictionary.
// A dictionary that describes a parent content cache.
type ContentCachingInformationResponseStatusResponseParentsItem struct {
	// The local IP address of the parent content cache.
	Address string `plist:"address" json:"address"`
	// A dictionary that describes an alert related to the parent content cache.
	Alert *ContentCachingInformationResponseStatusResponseParentsItemAlert `plist:"alert,omitempty" json:"alert,omitempty"`
	// A dictionary that contains additional details about the parent content cache.
	Details ContentCachingInformationResponseStatusResponseParentsItemDetails `plist:"details" json:"details"`
	// The unique identifier of the parent content cache.
	Guid string `plist:"guid" json:"guid"`
	// If `true,` the parent content cache is able to respond to requests from this content cache.
	Healthy bool `plist:"healthy" json:"healthy"`
	// The IP port number the parent content cache listens to for requests.
	Port int64 `plist:"port" json:"port"`
	// The version number of the parent content cache software.
	Version string `plist:"version" json:"version"`
}

// ContentCachingInformationResponseStatusResponsePeersItemAlert is the alert dictionary.
// A dictionary that describes an alert related to the peer content cache.
type ContentCachingInformationResponseStatusResponsePeersItemAlert struct {
	// The type of the alert.
	ClassName ContentCachingInformationResponseStatusResponsePeersItemAlertClassName `plist:"className" json:"className"`
	// The date of the alert.
	PostDate time.Time `plist:"postDate" json:"postDate"`
	// An array of local IP addresses of peer content caches.
	Addresses []string `plist:"addresses,omitempty" json:"addresses,omitempty"`
	// The local IP address of a peer content cache.
	PeerAddress *string `plist:"peerAddress,omitempty" json:"peerAddress,omitempty"`
}

// ContentCachingInformationResponseStatusResponsePeersItemDetailsCapabilities is the capabilities dictionary.
// A dictionary that describes the capabilities of the peer content cache.
type ContentCachingInformationResponseStatusResponsePeersItemDetailsCapabilities struct {
	// If `true`, the peer content cache is capable of imports and uploads.
	//
	// Default: false.
	Im *bool `plist:"im,omitempty" json:"im,omitempty"`
	// If `true`, the peer content cache is capable of handling namespaces, which is an aspect of
	// personal caching.
	//
	// Default: false.
	Ns *bool `plist:"ns,omitempty" json:"ns,omitempty"`
	// If `true`, the peer content cache is capable of caching personal iCloud content.
	//
	// Default: false.
	Pc *bool `plist:"pc,omitempty" json:"pc,omitempty"`
	// If `true`, the peer content cache is capable of handling query parameters in URLs.
	//
	// Default: false.
	QueryParameters *bool `plist:"query-parameters,omitempty" json:"query-parameters,omitempty"`
	// If `true`, the peer content cache is capable of caching shared non-iCloud content.
	//
	// Default: false.
	Sc *bool `plist:"sc,omitempty" json:"sc,omitempty"`
	// If `true`, the peer content cache is capable of prioritizing imports and uploads.
	//
	// Default: false.
	Ur *bool `plist:"ur,omitempty" json:"ur,omitempty"`
}

// ContentCachingInformationResponseStatusResponsePeersItemDetailsLocalNetwork is the local-network dictionary.
// A dictionary that describes the peer content cache's connection to its local network.
type ContentCachingInformationResponseStatusResponsePeersItemDetailsLocalNetwork struct {
	// The transfer speed, in megabits per second, of the peer content cache's connection to its local
	// network.
	Speed *int64 `plist:"speed,omitempty" json:"speed,omitempty"`
	// If `true`, the peer content cache has a wired connection to its local network. If `false`, it
	// has a wireless connection; for example, Wi-Fi.
	//
	// Default: false.
	Wired *bool `plist:"wired,omitempty" json:"wired,omitempty"`
}

// ContentCachingInformationResponseStatusResponsePeersItemDetails is the details dictionary.
// A dictionary that contains additional details about the peer content cache.
type ContentCachingInformationResponseStatusResponsePeersItemDetails struct {
	// If `true`, the peer content cache power source is AC; otherwise, an internal battery provides
	// its power.
	//
	// Default: false.
	AcPower *bool `plist:"ac-power,omitempty" json:"ac-power,omitempty"`
	// The maximum amount of disk space, in bytes, available to the peer content cache.
	CacheSize *int64 `plist:"cache-size,omitempty" json:"cache-size,omitempty"`
	// A dictionary that describes the capabilities of the peer content cache.
	Capabilities *ContentCachingInformationResponseStatusResponsePeersItemDetailsCapabilities `plist:"capabilities,omitempty" json:"capabilities,omitempty"`
	// If `true`, the peer content cache computer is portable; for example, a laptop.
	//
	// Default: false.
	IsPortable *bool `plist:"is-portable,omitempty" json:"is-portable,omitempty"`
	// A dictionary that describes the peer content cache's connection to its local network.
	LocalNetwork *ContentCachingInformationResponseStatusResponsePeersItemDetailsLocalNetwork `plist:"local-network,omitempty" json:"local-network,omitempty"`
}

// ContentCachingInformationResponseStatusResponsePeersItem is the PeersItem dictionary.
// A dictionary that describes a peer content cache.
type ContentCachingInformationResponseStatusResponsePeersItem struct {
	// The local IP address of the peer content cache.
	Address string `plist:"address" json:"address"`
	// A dictionary that describes an alert related to the peer content cache.
	Alert *ContentCachingInformationResponseStatusResponsePeersItemAlert `plist:"alert,omitempty" json:"alert,omitempty"`
	// A dictionary that contains additional details about the peer content cache.
	Details ContentCachingInformationResponseStatusResponsePeersItemDetails `plist:"details" json:"details"`
	// If `true`, the peer content cache is able to respond to requests from the content cache.
	Friendly bool `plist:"friendly" json:"friendly"`
	// The unique identifier of the peer content cache.
	Guid string `plist:"guid" json:"guid"`
	// If `true`, the peer content cache is able to respond to requests from the content cache.
	Healthy bool `plist:"healthy" json:"healthy"`
	// The IP port number the peer content cache listens to for requests.
	Port int64 `plist:"port" json:"port"`
	// The version number of the peer content cache software.
	Version string `plist:"version" json:"version"`
}

// ContentCachingInformationResponseStatusResponse is the StatusResponse dictionary.
// A dictionary that contains the status of content caching on a device.
type ContentCachingInformationResponseStatusResponse struct {
	// If `true`, the device has enabled content caching. Enabling content caching doesn't guarantee
	// service. See the `Active` key for the readiness of content caching to serve requests.
	//
	// Default: false.
	Activated *bool `plist:"Activated,omitempty" json:"Activated,omitempty"`
	// If `true`, content caching is ready to serve requests.
	//
	// Default: false.
	Active *bool `plist:"Active,omitempty" json:"Active,omitempty"`
	// The actual amount of disk space, in bytes, that cached content uses. See related values
	// `CacheUsed` and `PersonalCacheUsed`.
	ActualCacheUsed *int64 `plist:"ActualCacheUsed,omitempty" json:"ActualCacheUsed,omitempty"`
	// The error conditions the content cache detected in the `PeerFilterRanges` in the installed
	// `com.apple.AssetCache.managed` payload.
	AlertsForPeerFilterRanges *ContentCachingInformationResponseStatusResponseAlertsForPeerFilterRanges `plist:"AlertsForPeerFilterRanges,omitempty" json:"AlertsForPeerFilterRanges,omitempty"`
	// An array that contains the error conditions the content cache detected that aren't related to
	// peer filter ranges, parent content caches, or peer content caches.
	Alerts []ContentCachingInformationResponseStatusResponseAlertsItem `plist:"Alerts,omitempty" json:"Alerts,omitempty"`
	// The amount of disk space that various categories of cached content use. Apple defines these
	// categories and they're subject to change.
	CacheDetails *ContentCachingInformationResponseStatusResponseCacheDetails `plist:"CacheDetails,omitempty" json:"CacheDetails,omitempty"`
	// The amount of disk space, in bytes, available to the content cache.
	CacheFree *int64 `plist:"CacheFree,omitempty" json:"CacheFree,omitempty"`
	// The maximum amount of disk space, in bytes, available to the content cache. A value of `0`
	// indicates an unlimited amount. This value corresponds to `CacheLimit` in the installed
	// `ContentCaching` profile.
	CacheLimit *int64 `plist:"CacheLimit,omitempty" json:"CacheLimit,omitempty"`
	// The level of cache pressure. `LowSpace` means cache pressure is high.
	CacheStatus *ContentCachingInformationResponseStatusResponseCacheStatus `plist:"CacheStatus,omitempty" json:"CacheStatus,omitempty"`
	// The amount of disk space, in bytes, cached content uses. Content caching allocates space in its
	// cache for entire files even when it stores only part of those files in its cache.
	CacheUsed *int64 `plist:"CacheUsed,omitempty" json:"CacheUsed,omitempty"`
	// If `true`, the content cache finished moving from one volume to another.
	//
	// Default: false.
	DataMigrationCompleted *bool `plist:"DataMigrationCompleted,omitempty" json:"DataMigrationCompleted,omitempty"`
	// The error that occurred while the content cache moved from one volume to another.
	DataMigrationError *ContentCachingInformationResponseStatusResponseDataMigrationError `plist:"DataMigrationError,omitempty" json:"DataMigrationError,omitempty"`
	// A floating-point number between `0.0` and `1.0` that indicates the percentage of progress in
	// moving the content cache from one volume to another. A value of `1.0` indicates that the content
	// cache has fully migrated.
	DataMigrationProgress *float64 `plist:"DataMigrationProgress,omitempty" json:"DataMigrationProgress,omitempty"`
	// A floating-point number between `0.0` and `1.0` that represents how often the cache needed more
	// disk space over the last hour of operation. A lower value is better.
	MaxCachePressureLast1Hour *float64 `plist:"MaxCachePressureLast1Hour,omitempty" json:"MaxCachePressureLast1Hour,omitempty"`
	// An array of dictionaries that describes parent content caches.
	Parents []ContentCachingInformationResponseStatusResponseParentsItem `plist:"Parents,omitempty" json:"Parents,omitempty"`
	// An array of dictionaries that describes peer content caches.
	Peers []ContentCachingInformationResponseStatusResponsePeersItem `plist:"Peers,omitempty" json:"Peers,omitempty"`
	// The amount of disk space, in bytes, available to the content cache for personal iCloud content.
	PersonalCacheFree *int64 `plist:"PersonalCacheFree,omitempty" json:"PersonalCacheFree,omitempty"`
	// The maximum amount of disk space, in bytes, available to the content cache for personal iCloud
	// content. A value of `0` indicates an unlimited amount.
	PersonalCacheLimit *int64 `plist:"PersonalCacheLimit,omitempty" json:"PersonalCacheLimit,omitempty"`
	// The amount of disk space, in bytes, available to the content cache for personal iCloud content.
	PersonalCacheUsed *int64 `plist:"PersonalCacheUsed,omitempty" json:"PersonalCacheUsed,omitempty"`
	// The IP port number the content cache listens to for requests from clients, peers, and children.
	Port *int64 `plist:"Port,omitempty" json:"Port,omitempty"`
	// An array of the content cache's local IP addresses.
	PrivateAddresses []string `plist:"PrivateAddresses,omitempty" json:"PrivateAddresses,omitempty"`
	// The public IP address of the content cache.
	PublicAddress *string `plist:"PublicAddress,omitempty" json:"PublicAddress,omitempty"`
	// If present, the reason the content cache failed to register itself with Apple.
	RegistrationError *string `plist:"RegistrationError,omitempty" json:"RegistrationError,omitempty"`
	// If present, the HTTP response code the content cache received when it failed to register itself
	// with Apple.
	RegistrationResponseCode *int64 `plist:"RegistrationResponseCode,omitempty" json:"RegistrationResponseCode,omitempty"`
	// The date when the content cache began registering itself with Apple. This value is only
	// available during registration attempts.
	RegistrationStarted *time.Time `plist:"RegistrationStarted,omitempty" json:"RegistrationStarted,omitempty"`
	// The status of the content cache's registration with Apple, which is one of the following values:
	RegistrationStatus *ContentCachingInformationResponseStatusResponseRegistrationStatus `plist:"RegistrationStatus,omitempty" json:"RegistrationStatus,omitempty"`
	// If `true`, a restriction prevents caching of certain content types.
	//
	// Default: false.
	RestrictedMedia *bool `plist:"RestrictedMedia,omitempty" json:"RestrictedMedia,omitempty"`
	// The unique identifier of the content cache.
	ServerGUID *string `plist:"ServerGUID,omitempty" json:"ServerGUID,omitempty"`
	// The status of the content cache's registration with Apple.
	StartupStatus *ContentCachingInformationResponseStatusResponseStartupStatus `plist:"StartupStatus,omitempty" json:"StartupStatus,omitempty"`
	// The status of tethered caching, which is content caching with a shared internet connection,
	// which is one of the following values:
	TetheratorStatus *ContentCachingInformationResponseStatusResponseTetheratorStatus `plist:"TetheratorStatus,omitempty" json:"TetheratorStatus,omitempty"`
	// The start date to use when collecting data for the other `TotalBytes` values.
	TotalBytesAreSince *time.Time `plist:"TotalBytesAreSince,omitempty" json:"TotalBytesAreSince,omitempty"`
	// The amount of data, in bytes, that the content cache downloaded, but couldn't add to its cache,
	// since the `TotalBytesAreSince` date.
	TotalBytesDropped *int64 `plist:"TotalBytesDropped,omitempty" json:"TotalBytesDropped,omitempty"`
	// The amount of data, in bytes, that the content cache received since the `TotalBytesAreSince`
	// date.
	TotalBytesImported *int64 `plist:"TotalBytesImported,omitempty" json:"TotalBytesImported,omitempty"`
	// The amount of data, in bytes, that the content cache served to its child content cache since the
	// `TotalBytesAreSince` date.
	TotalBytesReturnedToChildren *int64 `plist:"TotalBytesReturnedToChildren,omitempty" json:"TotalBytesReturnedToChildren,omitempty"`
	// The amount of data, in bytes, that the content cache served to client iOS, macOS, and tvOS
	// devices since the `TotalBytesAreSince` date.
	TotalBytesReturnedToClients *int64 `plist:"TotalBytesReturnedToClients,omitempty" json:"TotalBytesReturnedToClients,omitempty"`
	// The amount of data, in bytes, that the content cache served to peer content caches since the
	// `TotalBytesAreSince` date.
	TotalBytesReturnedToPeers *int64 `plist:"TotalBytesReturnedToPeers,omitempty" json:"TotalBytesReturnedToPeers,omitempty"`
	// The amount of data, in bytes, that the content cache saved from the internet since the
	// `TotalBytesAreSince` date.
	TotalBytesStoredFromOrigin *int64 `plist:"TotalBytesStoredFromOrigin,omitempty" json:"TotalBytesStoredFromOrigin,omitempty"`
	// The amount of data, in bytes, that the content cache saved from parent content caches since the
	// `TotalBytesAreSince` date.
	TotalBytesStoredFromParents *int64 `plist:"TotalBytesStoredFromParents,omitempty" json:"TotalBytesStoredFromParents,omitempty"`
	// The amount of data, in bytes, that the content cache saved from peer content caches since the
	// `TotalBytesAreSince` date.
	TotalBytesStoredFromPeers *int64 `plist:"TotalBytesStoredFromPeers,omitempty" json:"TotalBytesStoredFromPeers,omitempty"`
}
