// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// RequestType returns the wire type identifier for DeviceInformation.
func (DeviceInformation) RequestType() string { return "DeviceInformation" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *DeviceInformation) Validate() error {
	var errs []error
	if p.Queries == nil {
		errs = append(errs, validate.Required("Queries"))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *DeviceInformationResponse) Validate() error {
	var errs []error
	if err := p.QueryResponses.Validate(); err != nil {
		errs = append(errs, validate.Nested("QueryResponses", err))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. DeviceInformationResponseQueryResponsesOrganizationInfo has no
// constraints beyond its field types.
func (p *DeviceInformationResponseQueryResponsesOrganizationInfo) Validate() error { return nil }

// Validate checks the payload against Apple's spec. DeviceInformationResponseQueryResponsesMDMOptions has no
// constraints beyond its field types.
func (p *DeviceInformationResponseQueryResponsesMDMOptions) Validate() error { return nil }

// Validate checks the payload against Apple's spec. DeviceInformationResponseQueryResponsesOSUpdateSettings has no
// constraints beyond its field types.
func (p *DeviceInformationResponseQueryResponsesOSUpdateSettings) Validate() error { return nil }

// Validate checks the payload against Apple's spec. DeviceInformationResponseQueryResponsesAutoSetupAdminAccountsItem has no
// constraints beyond its field types.
func (p *DeviceInformationResponseQueryResponsesAutoSetupAdminAccountsItem) Validate() error {
	return nil
}

// Validate checks the payload against Apple's spec. DeviceInformationResponseQueryResponsesServiceSubscriptionProperty has no
// constraints beyond its field types.
func (p *DeviceInformationResponseQueryResponsesServiceSubscriptionProperty) Validate() error {
	return nil
}

// Validate checks the payload against Apple's spec. DeviceInformationResponseQueryResponsesSoftwareUpdateSettings has no
// constraints beyond its field types.
func (p *DeviceInformationResponseQueryResponsesSoftwareUpdateSettings) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *DeviceInformationResponseQueryResponsesAccessibilitySettings) Validate() error {
	var errs []error
	if p.TextSize != nil {
		if err := validate.InList("TextSize", *p.TextSize, []DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSize{DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValueNeg1, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue0, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue1, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue2, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue3, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue4, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue5, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue6, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue7, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue8, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue9, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue10, DeviceInformationResponseQueryResponsesAccessibilitySettingsTextSizeValue11}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *DeviceInformationResponseQueryResponses) Validate() error {
	var errs []error
	if p.OrganizationInfo != nil {
		if err := p.OrganizationInfo.Validate(); err != nil {
			errs = append(errs, validate.Nested("OrganizationInfo", err))
		}
	}
	if p.MDMOptions != nil {
		if err := p.MDMOptions.Validate(); err != nil {
			errs = append(errs, validate.Nested("MDMOptions", err))
		}
	}
	if p.CellularTechnology != nil {
		if err := validate.InList("CellularTechnology", *p.CellularTechnology, []DeviceInformationResponseQueryResponsesCellularTechnology{DeviceInformationResponseQueryResponsesCellularTechnologyValue0, DeviceInformationResponseQueryResponsesCellularTechnologyValue1, DeviceInformationResponseQueryResponsesCellularTechnologyValue2, DeviceInformationResponseQueryResponsesCellularTechnologyValue3}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.OSUpdateSettings != nil {
		if err := p.OSUpdateSettings.Validate(); err != nil {
			errs = append(errs, validate.Nested("OSUpdateSettings", err))
		}
	}
	for i := range p.AutoSetupAdminAccounts {
		if err := p.AutoSetupAdminAccounts[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AutoSetupAdminAccounts", i, err))
		}
	}
	for i := range p.ServiceSubscriptions {
		if err := p.ServiceSubscriptions[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ServiceSubscriptions", i, err))
		}
	}
	if p.SoftwareUpdateSettings != nil {
		if err := p.SoftwareUpdateSettings.Validate(); err != nil {
			errs = append(errs, validate.Nested("SoftwareUpdateSettings", err))
		}
	}
	if p.AccessibilitySettings != nil {
		if err := p.AccessibilitySettings.Validate(); err != nil {
			errs = append(errs, validate.Nested("AccessibilitySettings", err))
		}
	}
	return errors.Join(errs...)
}
