// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// LOMDeviceRequest — LOM Device Request Command.
// Send requests to a device using lights-out management (LOM).
//
// Supported: macOS 11.0+.
type LOMDeviceRequest struct {
	// An array of requests to perform.
	RequestList []LOMDeviceRequestRequestListItem `plist:"RequestList" json:"RequestList"`
}

// LOMDeviceRequestResponse models the device response to the LOMDeviceRequest command.
type LOMDeviceRequestResponse struct {
	// An array of dictionaries that describes the status of each request.
	ResponseList []LOMDeviceRequestResponseResponseListItem `plist:"ResponseList" json:"ResponseList"`
}

// LOMDeviceRequestRequestListItem is the RequestListItem dictionary.
// A dictionary that contains a requested action to perform on a device using lights-out management
// (LOM).
type LOMDeviceRequestRequestListItem struct {
	// The requested action to perform on the device.
	DeviceRequestType LOMDeviceRequestRequestListItemDeviceRequestType `plist:"DeviceRequestType" json:"DeviceRequestType"`
	// The unique identifier of the request.
	DeviceRequestUUID string `plist:"DeviceRequestUUID" json:"DeviceRequestUUID"`
	// The DNS name of the device. This should match the `dNSName` in `SubjectAltName` or an equivalent
	// in a PKCS12 identity.
	DeviceDNSName string `plist:"DeviceDNSName" json:"DeviceDNSName"`
	// An array that contains the IPv6 addresses for primary LOM-compatible Ethernet interfaces for the
	// device.
	PrimaryIPv6AddressList []string `plist:"PrimaryIPv6AddressList" json:"PrimaryIPv6AddressList"`
	// An array that contains the IPv6 addresses for secondary LOM-compatible Ethernet interfaces for
	// the device.
	SecondaryIPv6AddressList []string `plist:"SecondaryIPv6AddressList" json:"SecondaryIPv6AddressList"`
	// The LOM protocol version that the device supports. Provide the same value that
	// `LOMProtocolVersion` receives in the `LOMSetupRequestResponse`.
	LOMProtocolVersion int64 `plist:"LOMProtocolVersion" json:"LOMProtocolVersion"`
}

// LOMDeviceRequestResponseResponseListItem is the ResponseListItem dictionary.
// A dictionary that describes a response list item.
type LOMDeviceRequestResponseResponseListItem struct {
	// If `true`, the request was successful.
	DeviceRequestSuccess bool `plist:"DeviceRequestSuccess" json:"DeviceRequestSuccess"`
	// The unique identifier of the request for this response list item.
	DeviceRequestUUID string `plist:"DeviceRequestUUID" json:"DeviceRequestUUID"`
	// If present, a description of the error for a failed request.
	DeviceRequestReturnError *string `plist:"DeviceRequestReturnError,omitempty" json:"DeviceRequestReturnError,omitempty"`
}
