// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// RequestType returns the wire type identifier for ManagedApplicationConfiguration.
func (ManagedApplicationConfiguration) RequestType() string { return "ManagedApplicationConfiguration" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ManagedApplicationConfiguration) Validate() error {
	var errs []error
	if p.Identifiers == nil {
		errs = append(errs, validate.Required("Identifiers"))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ManagedApplicationConfigurationResponse) Validate() error {
	var errs []error
	if p.ApplicationConfigurations == nil {
		errs = append(errs, validate.Required("ApplicationConfigurations"))
	}
	for i := range p.ApplicationConfigurations {
		if err := p.ApplicationConfigurations[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ApplicationConfigurations", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. ManagedApplicationConfigurationResponseApplicationConfigurationsItemConfiguration has no
// constraints beyond its field types.
func (p *ManagedApplicationConfigurationResponseApplicationConfigurationsItemConfiguration) Validate() error {
	return nil
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ManagedApplicationConfigurationResponseApplicationConfigurationsItem) Validate() error {
	var errs []error
	if p.Configuration != nil {
		if err := p.Configuration.Validate(); err != nil {
			errs = append(errs, validate.Nested("Configuration", err))
		}
	}
	return errors.Join(errs...)
}
