// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// RequestType returns the wire type identifier for InstallMedia.
func (InstallMedia) RequestType() string { return "InstallMedia" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *InstallMedia) Validate() error {
	var errs []error
	if err := validate.InList("MediaType", p.MediaType, []string{"Book"}); err != nil {
		errs = append(errs, err)
	}
	if p.Kind != nil {
		if err := validate.InList("Kind", *p.Kind, []InstallMediaKind{InstallMediaKindPdf, InstallMediaKindEpub, InstallMediaKindIbooks}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *InstallMediaResponse) Validate() error {
	var errs []error
	if p.State != nil {
		if err := validate.InList("State", *p.State, []InstallMediaResponseState{InstallMediaResponseStateQueued, InstallMediaResponseStatePromptingForLogin, InstallMediaResponseStateUpdating, InstallMediaResponseStateInstalling, InstallMediaResponseStateManaged, InstallMediaResponseStateManagedButUninstalled, InstallMediaResponseStateInstalled, InstallMediaResponseStateUninstalled, InstallMediaResponseStateFailed, InstallMediaResponseStateUnknown}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.RejectionReason != nil {
		if err := validate.InList("RejectionReason", *p.RejectionReason, []InstallMediaResponseRejectionReason{InstallMediaResponseRejectionReasonCouldNotVerifyITunesStoreID, InstallMediaResponseRejectionReasonPurchaseNotFound, InstallMediaResponseRejectionReasonAppStoreDisabled, InstallMediaResponseRejectionReasonWrongMediaType, InstallMediaResponseRejectionReasonDownloadInvalid, InstallMediaResponseRejectionReasonEnterpriseBooksNotSupportedInMultiUser}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
