// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// RequestType returns the wire type identifier for ManagedMediaList.
func (ManagedMediaList) RequestType() string { return "ManagedMediaList" }

// Validate checks the payload against Apple's spec. ManagedMediaList has no
// constraints beyond its field types.
func (p *ManagedMediaList) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ManagedMediaListResponse) Validate() error {
	var errs []error
	if p.Books == nil {
		errs = append(errs, validate.Required("Books"))
	}
	for i := range p.Books {
		if err := p.Books[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Books", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. ManagedMediaListResponseBooksItem has no
// constraints beyond its field types.
func (p *ManagedMediaListResponseBooksItem) Validate() error { return nil }
