// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestMirroring — Request Mirroring Command.
// Prompt the user to share their screen using AirPlay Mirroring.
//
// Supported: iOS 7.0+, macOS 10.10+.
type RequestMirroring struct {
	// The name of the AirPlay Mirroring destination.
	DestinationName *string `plist:"DestinationName,omitempty" json:"DestinationName,omitempty"`
	// The hardware address of the AirPlay Mirroring destination that identifies the device, in the
	// format `xx:xx:xx:xx:xx`. This value isn't case-sensitive. Not available for Apple TV devices
	// running tvOS 18 or later, use `DestinationName` instead.
	DestinationDeviceID *string `plist:"DestinationDeviceID,omitempty" json:"DestinationDeviceID,omitempty"`
	// The number of seconds, from `10` to `300`, for the device to spend searching for the
	// destination. The default value is `30`.
	ScanTime *int64 `plist:"ScanTime,omitempty" json:"ScanTime,omitempty"`
	// The screen-sharing password that the device uses when connecting to the destination.
	Password *string `plist:"Password,omitempty" json:"Password,omitempty"`
}

// RequestMirroringResponse models the device response to the RequestMirroring command.
type RequestMirroringResponse struct {
	// The result of the request. One of these values:
	MirroringResult *string `plist:"MirroringResult,omitempty" json:"MirroringResult,omitempty"`
}
