// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// StopMirroring — Stop Mirroring Command.
// Stop mirroring the display to another device.
//
// Supported: iOS 7.0+, macOS 10.10+.
type StopMirroring struct {
}
