// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for StopMirroring.
func (StopMirroring) RequestType() string { return "StopMirroring" }

// Validate checks the payload against Apple's spec. StopMirroring has no
// constraints beyond its field types.
func (p *StopMirroring) Validate() error { return nil }
