// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// VerifyFirmwarePassword — Verify Firmware Password Command.
// Verify the firmware password on a device.
//
// Supported: macOS 10.13+.
type VerifyFirmwarePassword struct {
	// The password to verify.
	Password string `plist:"Password" json:"Password"`
}

// VerifyFirmwarePasswordResponse models the device response to the VerifyFirmwarePassword command.
type VerifyFirmwarePasswordResponse struct {
	// A dictionary containing the results of the command.
	VerifyFirmwarePassword VerifyFirmwarePasswordResponseVerifyFirmwarePassword `plist:"VerifyFirmwarePassword" json:"VerifyFirmwarePassword"`
}

// VerifyFirmwarePasswordResponseVerifyFirmwarePassword is the VerifyFirmwarePassword dictionary.
// A dictionary containing the results of the command.
type VerifyFirmwarePasswordResponseVerifyFirmwarePassword struct {
	// If 'true', the provided password matched the firmware password set for the device.
	PasswordVerified bool `plist:"PasswordVerified" json:"PasswordVerified"`
}
