// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for SetRecoveryLock.
func (SetRecoveryLock) RequestType() string { return "SetRecoveryLock" }

// Validate checks the payload against Apple's spec. SetRecoveryLock has no
// constraints beyond its field types.
func (p *SetRecoveryLock) Validate() error { return nil }
