// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// RequestType returns the wire type identifier for InstallProvisioningProfile.
func (InstallProvisioningProfile) RequestType() string { return "InstallProvisioningProfile" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *InstallProvisioningProfile) Validate() error {
	var errs []error
	if p.ProvisioningProfile == nil {
		errs = append(errs, validate.Required("ProvisioningProfile"))
	}
	return errors.Join(errs...)
}
