// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for RemoveProvisioningProfile.
func (RemoveProvisioningProfile) RequestType() string { return "RemoveProvisioningProfile" }

// Validate checks the payload against Apple's spec. RemoveProvisioningProfile has no
// constraints beyond its field types.
func (p *RemoveProvisioningProfile) Validate() error { return nil }
