// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RotateFileVaultKey — Rotate FileVault Key Command.
// Change the FileVault primary password on a device.
//
// Supported: macOS 10.9+.
type RotateFileVaultKey struct {
	// The type of FileVault key you want to change the password for. Set this value to `personal` and
	// set a value for `Password` in the `FileVaultUnlock` dictionary to enable unlocking a device with
	// a password. Set this value to `institutional` and set values for `PrivateKeyExport` and
	// `PrivateKeyExportPassword` in the `FileVaultUnlock` dictionary.
	KeyType RotateFileVaultKeyKeyType `plist:"KeyType" json:"KeyType"`
	// A dictionary that contains FileVault unlock options.
	FileVaultUnlock RotateFileVaultKeyFileVaultUnlock `plist:"FileVaultUnlock" json:"FileVaultUnlock"`
	// A DER-encoded certificate for creating a new institutional recovery key, which the system
	// requires if `KeyType` is `institutional`.
	NewCertificate []byte `plist:"NewCertificate,omitempty" json:"NewCertificate,omitempty"`
	// A DER-encoded certificate for encrypting the new personal recovery key in a wrapper conforming
	// to the IETF Cryptographic Message Syntax (CMS) standard.
	ReplyEncryptionCertificate []byte `plist:"ReplyEncryptionCertificate,omitempty" json:"ReplyEncryptionCertificate,omitempty"`
}

// RotateFileVaultKeyResponse models the device response to the RotateFileVaultKey command.
type RotateFileVaultKeyResponse struct {
	// The result of rotating the personal recovery key.
	RotateResult *RotateResultItem `plist:"RotateResult,omitempty" json:"RotateResult,omitempty"`
}

// RotateFileVaultKeyFileVaultUnlock is the FileVaultUnlock dictionary.
// A dictionary that contains FileVault unlock options.
type RotateFileVaultKeyFileVaultUnlock struct {
	// A FileVault user's password, or if using a CoreStorage volume, the personal recovery key.
	Password *string `plist:"Password,omitempty" json:"Password,omitempty"`
	// The data for a .p12 export of the private key for the current institutional recovery key, which
	// requires that `KeyType` is `institutional`. The system ignores this key on APFS volumes.
	PrivateKeyExport []byte `plist:"PrivateKeyExport,omitempty" json:"PrivateKeyExport,omitempty"`
	// The password for `PrivateKeyExport`. Either `Password` or both `PrivateKeyExport` and
	// `PrivateKeyExportPassword` must be present. The system ignores this key on APFS volumes.
	PrivateKeyExportPassword *string `plist:"PrivateKeyExportPassword,omitempty" json:"PrivateKeyExportPassword,omitempty"`
}

// RotateResultItem is the RotateResult dictionary.
// The result of rotating the personal recovery key.
type RotateResultItem struct {
	// A new personal recovery key that is encrypted using a `ReplyEncryptionCertificate` as a
	// CMS-compliant envelope.
	EncryptedNewRecoveryKey []byte `plist:"EncryptedNewRecoveryKey,omitempty" json:"EncryptedNewRecoveryKey,omitempty"`
}
