// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// ScheduleOSUpdate — Schedule OS Update Command.
// Schedule an update of the operating system on a device.
//
// Supported: iOS 9.0+, macOS 10.11+, tvOS 12.0+.
type ScheduleOSUpdate struct {
	// An array of dictionaries specifying the updates to download or install. If this value is
	// missing, the device applies the default behavior for handling updates.
	Updates []ScheduleOSUpdateUpdatesItem `plist:"Updates" json:"Updates"`
}

// ScheduleOSUpdateResponse models the device response to the ScheduleOSUpdate command.
type ScheduleOSUpdateResponse struct {
	// An array of dictionaries that describes the results of processing operating-system updates.
	UpdateResults []ScheduleOSUpdateResponseUpdateResultsItem `plist:"UpdateResults" json:"UpdateResults"`
}

// ScheduleOSUpdateUpdatesItem is the UpdatesItem dictionary.
// A dictionary that describes the available operating-system updates item.
type ScheduleOSUpdateUpdatesItem struct {
	// The product key that represents the update.
	ProductKey *string `plist:"ProductKey,omitempty" json:"ProductKey,omitempty"`
	// The version of the update, which the system requires if `ProductKey` isn't present. This value
	// is available in iOS 11.3 and later, macOS 12 and later, and tvOS 12.2 and later.
	ProductVersion *string `plist:"ProductVersion,omitempty" json:"ProductVersion,omitempty"`
	// The install action, which is one of the following values:
	InstallAction ScheduleOSUpdateUpdatesItemInstallAction `plist:"InstallAction" json:"InstallAction"`
	// The maximum number of times the system allows the user to postpone an update before it's
	// installed. The system prompts the user once a day.
	MaxUserDeferrals *int64 `plist:"MaxUserDeferrals,omitempty" json:"MaxUserDeferrals,omitempty"`
	// The scheduling priority for downloading and preparing the requested update. This is only
	// supported for minor OS updates (macOS 12.x to 12.y).
	//
	// Default: Low.
	Priority *ScheduleOSUpdateUpdatesItemPriority `plist:"Priority,omitempty" json:"Priority,omitempty"`
}

// ScheduleOSUpdateResponseUpdateResultsItemErrorChainItem is the ErrorChainItem dictionary.
// A dictionary that describes an error chain item.
type ScheduleOSUpdateResponseUpdateResultsItemErrorChainItem struct {
	// The error details.
	ANY any `plist:"ANY" json:"ANY"`
}

// ScheduleOSUpdateResponseUpdateResultsItem is the UpdateResultsItem dictionary.
// The response dictionary that describes the result of processing an operating-system update.
type ScheduleOSUpdateResponseUpdateResultsItem struct {
	// The product key that represents the update.
	ProductKey string `plist:"ProductKey" json:"ProductKey"`
	// The install action that the device scheduled, which is one of the following values:
	InstallAction ScheduleOSUpdateResponseUpdateResultsItemInstallAction `plist:"InstallAction" json:"InstallAction"`
	// The status of the update, which is one of the following values:
	Status ScheduleOSUpdateResponseUpdateResultsItemStatus `plist:"Status" json:"Status"`
	// A dictionary that describes an error chain.
	ErrorChain []ScheduleOSUpdateResponseUpdateResultsItemErrorChainItem `plist:"ErrorChain,omitempty" json:"ErrorChain,omitempty"`
}
