// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// ScheduleOSUpdateScan — Schedule OS Update Scan Command.
// Schedule a background scan for operating-system updates on a device.
//
// Supported: macOS 10.11+.
type ScheduleOSUpdateScan struct {
	// If `true`, force a scan to start immediately. Otherwise, the scan starts at a system-determined
	// time.
	//
	// Default: false.
	Force *bool `plist:"Force,omitempty" json:"Force,omitempty"`
}

// ScheduleOSUpdateScanResponse models the device response to the ScheduleOSUpdateScan command.
type ScheduleOSUpdateScanResponse struct {
	// If `true`, the scan started successfully.
	ScanInitiated bool `plist:"ScanInitiated" json:"ScanInitiated"`
}
