// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// RequestType returns the wire type identifier for OSUpdateStatus.
func (OSUpdateStatus) RequestType() string { return "OSUpdateStatus" }

// Validate checks the payload against Apple's spec. OSUpdateStatus has no
// constraints beyond its field types.
func (p *OSUpdateStatus) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *OSUpdateStatusResponse) Validate() error {
	var errs []error
	if p.OSUpdateStatus == nil {
		errs = append(errs, validate.Required("OSUpdateStatus"))
	}
	for i := range p.OSUpdateStatus {
		if err := p.OSUpdateStatus[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("OSUpdateStatus", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. OSUpdateStatusResponseOSUpdateStatusItem has no
// constraints beyond its field types.
func (p *OSUpdateStatusResponseOSUpdateStatusItem) Validate() error { return nil }
