// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// RequestType returns the wire type identifier for ScheduleOSUpdate.
func (ScheduleOSUpdate) RequestType() string { return "ScheduleOSUpdate" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ScheduleOSUpdate) Validate() error {
	var errs []error
	if p.Updates == nil {
		errs = append(errs, validate.Required("Updates"))
	}
	for i := range p.Updates {
		if err := p.Updates[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Updates", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ScheduleOSUpdateResponse) Validate() error {
	var errs []error
	if p.UpdateResults == nil {
		errs = append(errs, validate.Required("UpdateResults"))
	}
	for i := range p.UpdateResults {
		if err := p.UpdateResults[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("UpdateResults", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ScheduleOSUpdateUpdatesItem) Validate() error {
	var errs []error
	if err := validate.InList("InstallAction", p.InstallAction, []ScheduleOSUpdateUpdatesItemInstallAction{ScheduleOSUpdateUpdatesItemInstallActionDefault, ScheduleOSUpdateUpdatesItemInstallActionDownloadOnly, ScheduleOSUpdateUpdatesItemInstallActionInstallASAP, ScheduleOSUpdateUpdatesItemInstallActionNotifyOnly, ScheduleOSUpdateUpdatesItemInstallActionInstallLater, ScheduleOSUpdateUpdatesItemInstallActionInstallForceRestart}); err != nil {
		errs = append(errs, err)
	}
	if p.Priority != nil {
		if err := validate.InList("Priority", *p.Priority, []ScheduleOSUpdateUpdatesItemPriority{ScheduleOSUpdateUpdatesItemPriorityLow, ScheduleOSUpdateUpdatesItemPriorityHigh}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ScheduleOSUpdateResponseUpdateResultsItemErrorChainItem) Validate() error {
	var errs []error
	if p.ANY == nil {
		errs = append(errs, validate.Required("ANY"))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ScheduleOSUpdateResponseUpdateResultsItem) Validate() error {
	var errs []error
	if err := validate.InList("InstallAction", p.InstallAction, []ScheduleOSUpdateResponseUpdateResultsItemInstallAction{ScheduleOSUpdateResponseUpdateResultsItemInstallActionError, ScheduleOSUpdateResponseUpdateResultsItemInstallActionDownloadOnly, ScheduleOSUpdateResponseUpdateResultsItemInstallActionInstallASAP, ScheduleOSUpdateResponseUpdateResultsItemInstallActionNotifyOnly, ScheduleOSUpdateResponseUpdateResultsItemInstallActionInstallLater, ScheduleOSUpdateResponseUpdateResultsItemInstallActionInstallForceRestart}); err != nil {
		errs = append(errs, err)
	}
	if err := validate.InList("Status", p.Status, []ScheduleOSUpdateResponseUpdateResultsItemStatus{ScheduleOSUpdateResponseUpdateResultsItemStatusIdle, ScheduleOSUpdateResponseUpdateResultsItemStatusDownloading, ScheduleOSUpdateResponseUpdateResultsItemStatusDownloadFailed, ScheduleOSUpdateResponseUpdateResultsItemStatusDownloadRequiresComputer, ScheduleOSUpdateResponseUpdateResultsItemStatusDownloadInsufficientSpace, ScheduleOSUpdateResponseUpdateResultsItemStatusDownloadInsufficientPower, ScheduleOSUpdateResponseUpdateResultsItemStatusDownloadInsufficientNetwork, ScheduleOSUpdateResponseUpdateResultsItemStatusInstalling, ScheduleOSUpdateResponseUpdateResultsItemStatusInstallInsufficientSpace, ScheduleOSUpdateResponseUpdateResultsItemStatusInstallInsufficientPower, ScheduleOSUpdateResponseUpdateResultsItemStatusInstallPhoneCallInProgress, ScheduleOSUpdateResponseUpdateResultsItemStatusInstallFailed}); err != nil {
		errs = append(errs, err)
	}
	for i := range p.ErrorChain {
		if err := p.ErrorChain[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ErrorChain", i, err))
		}
	}
	return errors.Join(errs...)
}
