// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for ScheduleOSUpdateScan.
func (ScheduleOSUpdateScan) RequestType() string { return "ScheduleOSUpdateScan" }

// Validate checks the payload against Apple's spec. ScheduleOSUpdateScan has no
// constraints beyond its field types.
func (p *ScheduleOSUpdateScan) Validate() error { return nil }

// Validate checks the payload against Apple's spec. ScheduleOSUpdateScanResponse has no
// constraints beyond its field types.
func (p *ScheduleOSUpdateScanResponse) Validate() error { return nil }
