// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// RequestType returns the wire type identifier for AvailableOSUpdates.
func (AvailableOSUpdates) RequestType() string { return "AvailableOSUpdates" }

// Validate checks the payload against Apple's spec. AvailableOSUpdates has no
// constraints beyond its field types.
func (p *AvailableOSUpdates) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AvailableOSUpdatesResponse) Validate() error {
	var errs []error
	if p.AvailableOSUpdates == nil {
		errs = append(errs, validate.Required("AvailableOSUpdates"))
	}
	for i := range p.AvailableOSUpdates {
		if err := p.AvailableOSUpdates[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AvailableOSUpdates", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AvailableOSUpdatesResponseAvailableOSUpdatesItem) Validate() error {
	var errs []error
	if p.AppIdentifiersToClose == nil {
		errs = append(errs, validate.Required("AppIdentifiersToClose"))
	}
	return errors.Join(errs...)
}
