// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for DeleteUser.
func (DeleteUser) RequestType() string { return "DeleteUser" }

// Validate checks the payload against Apple's spec. DeleteUser has no
// constraints beyond its field types.
func (p *DeleteUser) Validate() error { return nil }
