// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// RequestType returns the wire type identifier for LogOutUser.
func (LogOutUser) RequestType() string { return "LogOutUser" }

// Validate checks the payload against Apple's spec. LogOutUser has no
// constraints beyond its field types.
func (p *LogOutUser) Validate() error { return nil }
