// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package commands

// UserList — User List Command.
// Get a list of users with active accounts on a device.
//
// Supported: iOS 9.3+, macOS 10.13+.
type UserList struct {
}

// UserListResponse models the device response to the UserList command.
type UserListResponse struct {
	// An array of user dictionaries that contains information about the active accounts.
	Users []UserListResponseUsersItem `plist:"Users" json:"Users"`
}

// UserListResponseUsersItem is the UsersItem dictionary.
// A dictionary that contains information about an active account on a device.
type UserListResponseUsersItem struct {
	// The user name for the account. In macOS, this is the short name of the user account. This value
	// is available in iOS 9.3 and later, and macOS 10.13 and later.
	UserName string `plist:"UserName" json:"UserName"`
	// The user's full name. This value is available in macOS 10.13 and later.
	FullName string `plist:"FullName" json:"FullName"`
	// The user's unique identifier. This value is available in macOS 10.13 and later.
	UID int64 `plist:"UID" json:"UID"`
	// The user's `GeneratedUID`. This value is available in macOS 10.13 and later.
	UserGUID string `plist:"UserGUID" json:"UserGUID"`
	// If `true`, the user is currently logged in on the device. This value is available in iOS 9.3 and
	// later, and macOS 10.13 and later.
	IsLoggedIn bool `plist:"IsLoggedIn" json:"IsLoggedIn"`
	// If `true`, the user has data to sync to the cloud. This value is available in iOS 9.3 and later.
	HasDataToSync bool `plist:"HasDataToSync" json:"HasDataToSync"`
	// If present, the user's data quota in bytes. This isn't present if the account doesn't enforce a
	// quota. This value is available in iOS 9.3 and later.
	DataQuota int64 `plist:"DataQuota" json:"DataQuota"`
	// The amount of data, in bytes, that the user has used. This value is available in iOS 9.3 and
	// later.
	DataUsed int64 `plist:"DataUsed" json:"DataUsed"`
	// If `true`, the account is a mobile account. This value is available in macOS 10.13 and later.
	MobileAccount bool `plist:"MobileAccount" json:"MobileAccount"`
	// If `true`, the user currently has a secure token set. This value is available in macOS 11 and
	// later.
	HasSecureToken bool `plist:"HasSecureToken" json:"HasSecureToken"`
}
