package auditevents

// Field constants for fields[auditEvents] query parameter.
const (
	FieldEventDateTime                                  = "eventDateTime"
	FieldType                                           = "type"
	FieldCategory                                       = "category"
	FieldActorType                                      = "actorType"
	FieldActorId                                        = "actorId"
	FieldActorName                                      = "actorName"
	FieldSubjectType                                    = "subjectType"
	FieldSubjectId                                      = "subjectId"
	FieldSubjectName                                    = "subjectName"
	FieldOutcome                                        = "outcome"
	FieldGroupId                                        = "groupId"
	FieldEventDataPropertyKey                           = "eventDataPropertyKey"
	FieldEventDataDeviceAddedToOrg                      = "eventDataDeviceAddedToOrg"
	FieldEventDataDeviceRemovedFromOrg                  = "eventDataDeviceRemovedFromOrg"
	FieldEventDataDeviceAssignedToServer                = "eventDataDeviceAssignedToServer"
	FieldEventDataDeviceIsErased                        = "eventDataDeviceIsErased"
	FieldEventDataDeviceUnassignedFromServer             = "eventDataDeviceUnassignedFromServer"
	FieldEventDataSubjectHasICloudStoragePurchaseAdded   = "eventDataSubjectHasICloudStoragePurchaseAdded"
	FieldEventDataSubjectHasICloudStoragePurchaseRemoved = "eventDataSubjectHasICloudStoragePurchaseRemoved"
	FieldEventDataSubjectHasAppleCarePurchaseAdded       = "eventDataSubjectHasAppleCarePurchaseAdded"
	FieldEventDataSubjectHasAppleCarePurchaseRemoved     = "eventDataSubjectHasAppleCarePurchaseRemoved"
	FieldEventDataConfigSettingsCreated                  = "eventDataConfigSettingsCreated"
	FieldEventDataConfigSettingsUpdated                  = "eventDataConfigSettingsUpdated"
	FieldEventDataConfigSettingsDeleted                  = "eventDataConfigSettingsDeleted"
	FieldEventDataCollectionCreated                      = "eventDataCollectionCreated"
	FieldEventDataCollectionUpdated                      = "eventDataCollectionUpdated"
	FieldEventDataCollectionDeleted                      = "eventDataCollectionDeleted"
	FieldEventDataSubscriptionCreated                    = "eventDataSubscriptionCreated"
	FieldEventDataSubscriptionUpdated                    = "eventDataSubscriptionUpdated"
	FieldEventDataSubscriptionDeleted                    = "eventDataSubscriptionDeleted"
	FieldEventDataAccountRoleLocationChanged             = "eventDataAccountRoleLocationChanged"
	FieldEventDataAccountAdded                           = "eventDataAccountAdded"
	FieldEventDataAccountDeleted                         = "eventDataAccountDeleted"
	FieldEventDataExternalAccountAssociated              = "eventDataExternalAccountAssociated"
	FieldEventDataExternalAccountDisassociated           = "eventDataExternalAccountDisassociated"
	FieldEventDataDomainAdded                            = "eventDataDomainAdded"
	FieldEventDataDomainRemoved                          = "eventDataDomainRemoved"
	FieldEventDataDomainVerified                         = "eventDataDomainVerified"
	FieldEventDataApiAccountCreatedWithKey               = "eventDataApiAccountCreatedWithKey"
	FieldEventDataApiAccountCreatedWithoutKey            = "eventDataApiAccountCreatedWithoutKey"
	FieldEventDataApiAccountDeleted                      = "eventDataApiAccountDeleted"
	FieldEventDataApiAccountKeyGenerated                 = "eventDataApiAccountKeyGenerated"
	FieldEventDataApiAccountKeyRevoked                   = "eventDataApiAccountKeyRevoked"
	FieldEventDataApiAccountNameChanged                  = "eventDataApiAccountNameChanged"
	FieldEventDataApiAccountRoleLocationChanged          = "eventDataApiAccountRoleLocationChanged"
)

// AuditEventType constants for filter[type] query parameter.
const (
	AuditEventTypeDeviceAddedToOrg                        = "DEVICE_ADDED_TO_ORG"
	AuditEventTypeDeviceRemovedFromOrg                    = "DEVICE_REMOVED_FROM_ORG"
	AuditEventTypeDeviceAssignedToServer                  = "DEVICE_ASSIGNED_TO_SERVER"
	AuditEventTypeDeviceUnassignedFromServer              = "DEVICE_UNASSIGNED_FROM_SERVER"
	AuditEventTypeSubjectHasICloudStoragePurchaseAdded    = "SUBJECT_HAS_ICLOUD_STORAGE_PURCHASE_ADDED"
	AuditEventTypeSubjectHasICloudStoragePurchaseRemoved  = "SUBJECT_HAS_ICLOUD_STORAGE_PURCHASE_REMOVED"
	AuditEventTypeSubjectHasAppleCarePurchaseAdded        = "SUBJECT_HAS_APPLECARE_PURCHASE_ADDED"
	AuditEventTypeSubjectHasAppleCarePurchaseRemoved      = "SUBJECT_HAS_APPLECARE_PURCHASE_REMOVED"
	AuditEventTypeDeviceIsErased                          = "DEVICE_IS_ERASED"
	AuditEventTypeConfigSettingsCreated                   = "CONFIG_SETTINGS_CREATED"
	AuditEventTypeConfigSettingsUpdated                   = "CONFIG_SETTINGS_UPDATED"
	AuditEventTypeConfigSettingsDeleted                   = "CONFIG_SETTINGS_DELETED"
	AuditEventTypeCollectionCreated                       = "COLLECTION_CREATED"
	AuditEventTypeCollectionUpdated                       = "COLLECTION_UPDATED"
	AuditEventTypeCollectionDeleted                       = "COLLECTION_DELETED"
	AuditEventTypeSubscriptionCreated                     = "SUBSCRIPTION_CREATED"
	AuditEventTypeSubscriptionUpdated                     = "SUBSCRIPTION_UPDATED"
	AuditEventTypeSubscriptionDeleted                     = "SUBSCRIPTION_DELETED"
	AuditEventTypeAccountRoleLocationChanged              = "ACCOUNT_ROLE_LOCATION_CHANGED"
	AuditEventTypeAccountAdded                            = "ACCOUNT_ADDED"
	AuditEventTypeAccountDeleted                          = "ACCOUNT_DELETED"
	AuditEventTypeExternalAccountAssociated               = "EXTERNAL_ACCOUNT_ASSOCIATED"
	AuditEventTypeExternalAccountDisassociated            = "EXTERNAL_ACCOUNT_DISASSOCIATED"
	AuditEventTypeDomainAdded                             = "DOMAIN_ADDED"
	AuditEventTypeDomainRemoved                           = "DOMAIN_REMOVED"
	AuditEventTypeDomainVerified                          = "DOMAIN_VERIFIED"
	AuditEventTypeAPIAccountCreatedWithKey                = "API_ACCOUNT_CREATED_WITH_KEY"
	AuditEventTypeAPIAccountCreatedWithoutKey             = "API_ACCOUNT_CREATED_WITHOUT_KEY"
	AuditEventTypeAPIAccountDeleted                       = "API_ACCOUNT_DELETED"
	AuditEventTypeAPIAccountKeyRevoked                    = "API_ACCOUNT_KEY_REVOKED"
	AuditEventTypeAPIAccountKeyGenerated                  = "API_ACCOUNT_KEY_GENERATED"
	AuditEventTypeAPIAccountRoleLocationChanged           = "API_ACCOUNT_ROLE_LOCATION_CHANGED"
	AuditEventTypeAPIAccountNameChanged                   = "API_ACCOUNT_NAME_CHANGED"
)

// AuditEventOutcome constants for outcome field values.
const (
	AuditEventOutcomeSuccess = "SUCCESS"
	AuditEventOutcomeFailure = "FAILURE"
)
