// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for Airplay.
func (Airplay) PayloadType() string { return "com.apple.airplay" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *Airplay) Validate() error {
	var errs []error
	for i := range p.AllowList {
		if err := p.AllowList[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AllowList", i, err))
		}
	}
	for i := range p.Passwords {
		if err := p.Passwords[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Passwords", i, err))
		}
	}
	for i := range p.Whitelist {
		if err := p.Whitelist[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Whitelist", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AirplayAllowListItem) Validate() error {
	var errs []error
	if p.DeviceID != nil {
		if err := validate.Format("DeviceID", *p.DeviceID, "^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$"); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. AirplayPasswordsItem has no
// constraints beyond its field types.
func (p *AirplayPasswordsItem) Validate() error { return nil }
