// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// AirplaySecurity — AirPlay Security.
// The payload that configures Apple TV for a particular style of AirPlay security.
//
// Supported: tvOS 11.0+.
type AirplaySecurity struct {
	// The security policy for AirPlay. Allowed values:
	SecurityType AirplaySecuritySecurityType `plist:"SecurityType" json:"SecurityType"`
	// The access policy for AirPlay.
	AccessType AirplaySecurityAccessType `plist:"AccessType" json:"AccessType"`
	// The AirPlay password; required if `SecurityType` is `PASSWORD`.
	Password *string `plist:"Password,omitempty" json:"Password,omitempty"`
}
