// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/ptr"
	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for Airprint.
func (Airprint) PayloadType() string { return "com.apple.airprint" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *Airprint) Validate() error {
	var errs []error
	if p.AirPrint == nil {
		errs = append(errs, validate.Required("AirPrint"))
	}
	for i := range p.AirPrint {
		if err := p.AirPrint[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AirPrint", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AirprintAirPrintItem) Validate() error {
	var errs []error
	if p.Port != nil {
		if err := validate.IntRange("Port", *p.Port, ptr.To(int64(0)), ptr.To(int64(65535))); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
