// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// ApnManaged — APN.
// The payload that configures access point names.
//
// Supported: iOS 4.0+.
type ApnManaged struct {
	// The list of access point names (APNs).
	DefaultsData ApnManagedDefaultsData `plist:"DefaultsData" json:"DefaultsData"`
	// The domain name.
	DefaultsDomainName string `plist:"DefaultsDomainName" json:"DefaultsDomainName"`
}

// ApnManagedDefaultsDataApnsItem is the apnsItem dictionary.
// A dictionary that describes an APN configuration.
type ApnManagedDefaultsDataApnsItem struct {
	// The access point name.
	Apn string `plist:"apn" json:"apn"`
	// The user name. If missing, the device prompts for it during profile installation.
	Username *string `plist:"username,omitempty" json:"username,omitempty"`
	// The password for the user. For obfuscation purposes, the system encodes the password. If
	// missing, the device prompts for the password during profile installation.
	Password []byte `plist:"password,omitempty" json:"password,omitempty"`
	// The IP address or URL of the APN proxy.
	Proxy *string `plist:"proxy,omitempty" json:"proxy,omitempty"`
	// The port number of the APN proxy.
	ProxyPort *int64 `plist:"proxyPort,omitempty" json:"proxyPort,omitempty"`
}

// ApnManagedDefaultsData is the DefaultsData dictionary.
// The list of access point names (APNs).
type ApnManagedDefaultsData struct {
	// An array of APN dictionaries (\`APN.DefaultsData.Apns\`).
	Apns []ApnManagedDefaultsDataApnsItem `plist:"apns" json:"apns"`
}
