// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// ApplicationaccessRatingRegion — allowed values for Applicationaccess.RatingRegion.
type ApplicationaccessRatingRegion string

// ApplicationaccessRatingRegion allowed values.
const (
	ApplicationaccessRatingRegionUs ApplicationaccessRatingRegion = "us"
	ApplicationaccessRatingRegionAu ApplicationaccessRatingRegion = "au"
	ApplicationaccessRatingRegionCa ApplicationaccessRatingRegion = "ca"
	ApplicationaccessRatingRegionDe ApplicationaccessRatingRegion = "de"
	ApplicationaccessRatingRegionFr ApplicationaccessRatingRegion = "fr"
	ApplicationaccessRatingRegionIe ApplicationaccessRatingRegion = "ie"
	ApplicationaccessRatingRegionJp ApplicationaccessRatingRegion = "jp"
	ApplicationaccessRatingRegionNz ApplicationaccessRatingRegion = "nz"
	ApplicationaccessRatingRegionGb ApplicationaccessRatingRegion = "gb"
)

// String returns the ApplicationaccessRatingRegion value as a plain string.
func (e ApplicationaccessRatingRegion) String() string { return string(e) }
