// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// ApplicationaccessNew — Parental Controls: Application Restrictions.
// The payload that configures parental controls for apps.
//
// Supported: macOS 10.7+.
type ApplicationaccessNew struct {
	// If `true`, enables app access restrictions.
	FamilyControlsEnabled bool `plist:"familyControlsEnabled" json:"familyControlsEnabled"`
	// The allow list of app item dictionaries.
	AllowList []ApplicationaccessNewAllowListItem `plist:"allowList,omitempty" json:"allowList,omitempty"`
	// The allow list of app item dictionaries. This property is deprecated in macOS 10.15 and later -
	// use `allowList` instead.
	WhiteList []ApplicationaccessNewAllowListItem `plist:"whiteList,omitempty" json:"whiteList,omitempty"`
	// The paths to apps in the deny list.
	PathDenyList []string `plist:"pathDenyList,omitempty" json:"pathDenyList,omitempty"`
	// The paths to apps in the deny list. This property is deprecated in macOS 10.15 and later - use
	// `pathDenyList` instead.
	PathBlackList []string `plist:"pathBlackList,omitempty" json:"pathBlackList,omitempty"`
	// The paths to apps in the allow list.
	PathAllowList []string `plist:"pathAllowList,omitempty" json:"pathAllowList,omitempty"`
	// The paths to apps in the allow list. This property is deprecated in macOS 10.15 and later - use
	// `pathAllowList` instead.
	PathWhiteList []string `plist:"pathWhiteList,omitempty" json:"pathWhiteList,omitempty"`
}

// ApplicationaccessNewAllowListItem is the allowListItem dictionary.
// A dictionary defining an app for parental control.
type ApplicationaccessNewAllowListItem struct {
	// The bundle ID of the app.
	BundleID string `plist:"bundleID" json:"bundleID"`
	// The identifier of the app. Obtain this value from the Security framework using
	// `SecCodeCopyDesignatedRequirement`.
	AppID []byte `plist:"appID" json:"appID"`
	// The signature for an unsigned binary.
	DetachedSignature []byte `plist:"detachedSignature,omitempty" json:"detachedSignature,omitempty"`
	// If `true`, this app isn't added to the allow list.
	//
	// Default: false.
	Disabled *bool `plist:"disabled,omitempty" json:"disabled,omitempty"`
	// An array of nested helper applications.
	SubApps []any `plist:"subApps,omitempty" json:"subApps,omitempty"`
	// The name used for display purposes.
	DisplayName *string `plist:"displayName,omitempty" json:"displayName,omitempty"`
}
