// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// Appstore — App Store.
// The payload that configures macOS App Store restrictions.
//
// Supported: macOS 10.9+.
type Appstore struct {
	// If `true`, the system restricts app installations to admin users only. Deprecated in macOS
	// 10.14. Use the `com.apple.SoftwareUpdate` payload key
	// `restrict-software-update-require-admin-to-install` instead.
	//
	// Default: false.
	RestrictStoreRequireAdminToInstall *bool `plist:"restrict-store-require-admin-to-install,omitempty" json:"restrict-store-require-admin-to-install,omitempty"`
	// If `true`, the system prevents App Store from launching. Restricts installations to software
	// updates only in macOS 10.10 through 10.13.
	//
	// Default: false.
	RestrictStoreSoftwareupdateOnly *bool `plist:"restrict-store-softwareupdate-only,omitempty" json:"restrict-store-softwareupdate-only,omitempty"`
	// If `true`, the system disables app adoption by users.
	//
	// Default: false.
	RestrictStoreDisableAppAdoption *bool `plist:"restrict-store-disable-app-adoption,omitempty" json:"restrict-store-disable-app-adoption,omitempty"`
	// If `true`, the system disables software update notifications.
	//
	// Default: false.
	DisableSoftwareUpdateNotifications *bool `plist:"DisableSoftwareUpdateNotifications,omitempty" json:"DisableSoftwareUpdateNotifications,omitempty"`
}
