// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for Asam.
func (Asam) PayloadType() string { return "com.apple.asam" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *Asam) Validate() error {
	var errs []error
	if p.AllowedApplications == nil {
		errs = append(errs, validate.Required("AllowedApplications"))
	}
	for i := range p.AllowedApplications {
		if err := p.AllowedApplications[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AllowedApplications", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. AsamAllowedApplicationsItem has no
// constraints beyond its field types.
func (p *AsamAllowedApplicationsItem) Validate() error { return nil }
