// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for CaldavAccount.
func (CaldavAccount) PayloadType() string { return "com.apple.caldav.account" }

// Validate checks the payload against Apple's spec. CaldavAccount has no
// constraints beyond its field types.
func (p *CaldavAccount) Validate() error { return nil }
