// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for Cellular.
func (Cellular) PayloadType() string { return "com.apple.cellular" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *Cellular) Validate() error {
	var errs []error
	if p.AttachAPN != nil {
		if err := p.AttachAPN.Validate(); err != nil {
			errs = append(errs, validate.Nested("AttachAPN", err))
		}
	}
	for i := range p.APNs {
		if err := p.APNs[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("APNs", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *CellularAttachAPN) Validate() error {
	var errs []error
	if p.AuthenticationType != nil {
		if err := validate.InList("AuthenticationType", *p.AuthenticationType, []CellularAttachAPNAuthenticationType{CellularAttachAPNAuthenticationTypeCHAP, CellularAttachAPNAuthenticationTypePAP}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.AllowedProtocolMask != nil {
		if err := validate.InList("AllowedProtocolMask", *p.AllowedProtocolMask, []CellularAttachAPNAllowedProtocolMask{CellularAttachAPNAllowedProtocolMaskValue1, CellularAttachAPNAllowedProtocolMaskValue2, CellularAttachAPNAllowedProtocolMaskValue3}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *CellularAPNsItem) Validate() error {
	var errs []error
	if p.AuthenticationType != nil {
		if err := validate.InList("AuthenticationType", *p.AuthenticationType, []CellularAPNsItemAuthenticationType{CellularAPNsItemAuthenticationTypeCHAP, CellularAPNsItemAuthenticationTypePAP}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.DefaultProtocolMask != nil {
		if err := validate.InList("DefaultProtocolMask", *p.DefaultProtocolMask, []CellularAPNsItemDefaultProtocolMask{CellularAPNsItemDefaultProtocolMaskValue1, CellularAPNsItemDefaultProtocolMaskValue2, CellularAPNsItemDefaultProtocolMaskValue3}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.AllowedProtocolMask != nil {
		if err := validate.InList("AllowedProtocolMask", *p.AllowedProtocolMask, []CellularAPNsItemAllowedProtocolMask{CellularAPNsItemAllowedProtocolMaskValue1, CellularAPNsItemAllowedProtocolMaskValue2, CellularAPNsItemAllowedProtocolMaskValue3}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.AllowedProtocolMaskInRoaming != nil {
		if err := validate.InList("AllowedProtocolMaskInRoaming", *p.AllowedProtocolMaskInRoaming, []CellularAPNsItemAllowedProtocolMaskInRoaming{CellularAPNsItemAllowedProtocolMaskInRoamingValue1, CellularAPNsItemAllowedProtocolMaskInRoamingValue2, CellularAPNsItemAllowedProtocolMaskInRoamingValue3}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.AllowedProtocolMaskInDomesticRoaming != nil {
		if err := validate.InList("AllowedProtocolMaskInDomesticRoaming", *p.AllowedProtocolMaskInDomesticRoaming, []CellularAPNsItemAllowedProtocolMaskInDomesticRoaming{CellularAPNsItemAllowedProtocolMaskInDomesticRoamingValue1, CellularAPNsItemAllowedProtocolMaskInDomesticRoamingValue2, CellularAPNsItemAllowedProtocolMaskInDomesticRoamingValue3}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
