// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// CommonPayloadKeys — Common Payload Keys.
// The properties common to all payloads.
//
// Supported: iOS 4.0+, macOS 10.7+, tvOS 9.0+, visionOS 1.0+, watchOS 1.0+.
type CommonPayloadKeys struct {
	// The reverse-DNS-style identifier for the payload. This identifier is usually the same as the
	// `TopLevel` value, with an additional appended component. This string must be unique within the
	// profile.
	PayloadIdentifier string `plist:"PayloadIdentifier" json:"PayloadIdentifier"`
	// The globally unique identifier for the payload. The actual content is unimportant, but must be
	// globally unique. In macOS, use `uuidgen` to generate UUIDs.
	PayloadUUID string `plist:"PayloadUUID" json:"PayloadUUID"`
	// The payload type, which each payload domain's reference page specifies.
	PayloadType2 string `plist:"PayloadType" json:"PayloadType"`
	// The version of this specific payload.
	PayloadVersion int64 `plist:"PayloadVersion" json:"PayloadVersion"`
	// The human-readable description of this payload. This description appears on the Detail screen.
	PayloadDescription *string `plist:"PayloadDescription,omitempty" json:"PayloadDescription,omitempty"`
	// The human-readable name for the profile payload. The name appears on the Detail screen and
	// doesn't need to be unique.
	PayloadDisplayName *string `plist:"PayloadDisplayName,omitempty" json:"PayloadDisplayName,omitempty"`
	// The human-readable string containing the name of the organization that provides the profile.
	// This value doesn't need to match the organization payload value in the enclosing dictionary.
	PayloadOrganization *string `plist:"PayloadOrganization,omitempty" json:"PayloadOrganization,omitempty"`
}
