// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// ConfigurationprofileIdentification — Identification.
// The payload that configures the names of the account user.
//
// Supported: macOS 10.7+.
type ConfigurationprofileIdentification struct {
	// The dictionary that contains details about the user.
	PayloadIdentification ConfigurationprofileIdentificationPayloadIdentification `plist:"PayloadIdentification" json:"PayloadIdentification"`
}

// ConfigurationprofileIdentificationPayloadIdentification is the PayloadIdentification dictionary.
// The dictionary that contains details about the user.
type ConfigurationprofileIdentificationPayloadIdentification struct {
	// The UNIX user name for the accounts.
	UserName string `plist:"UserName" json:"UserName"`
	// The full name of the account.
	FullName string `plist:"FullName" json:"FullName"`
	// The address for the account.
	EmailAddress string `plist:"EmailAddress" json:"EmailAddress"`
	// The authorization method. Either the profile contains the password or the user provides it.
	AuthMethod ConfigurationprofileIdentificationPayloadIdentificationAuthMethod `plist:"AuthMethod" json:"AuthMethod"`
	// The password for the account. Required when the `AuthMethod` is `Password`.
	Password string `plist:"Password" json:"Password"`
	// The custom instructions for the user, if needed.
	Prompt *string `plist:"Prompt,omitempty" json:"Prompt,omitempty"`
	// The additional descriptive text for the user prompt.
	PromptMessage *string `plist:"PromptMessage,omitempty" json:"PromptMessage,omitempty"`
}
