// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// ConfigurationprofileIdentificationPayloadIdentificationAuthMethod — allowed values for ConfigurationprofileIdentificationPayloadIdentification.AuthMethod.
type ConfigurationprofileIdentificationPayloadIdentificationAuthMethod string

// ConfigurationprofileIdentificationPayloadIdentificationAuthMethod allowed values.
const (
	ConfigurationprofileIdentificationPayloadIdentificationAuthMethodPassword            ConfigurationprofileIdentificationPayloadIdentificationAuthMethod = "Password"
	ConfigurationprofileIdentificationPayloadIdentificationAuthMethodUserEnteredPassword ConfigurationprofileIdentificationPayloadIdentificationAuthMethod = "UserEnteredPassword"
)

// String returns the ConfigurationprofileIdentificationPayloadIdentificationAuthMethod value as a plain string.
func (e ConfigurationprofileIdentificationPayloadIdentificationAuthMethod) String() string {
	return string(e)
}
