// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// Dashboard — Parental Controls: Dashboard Widget Restrictions.
// The payload that configures allowed dashboard widgets.
//
// Supported: macOS 10.7–10.15.
type Dashboard struct {
	// If `true`, enables the widget allow list.
	WhiteListEnabled bool `plist:"whiteListEnabled" json:"whiteListEnabled"`
	// An array of widget item dictionaries that are allowed.
	WhiteList []DashboardWhiteListItem `plist:"WhiteList" json:"WhiteList"`
}

// DashboardWhiteListItem is the WhiteListItem dictionary.
// The widget item dictionary.
type DashboardWhiteListItem struct {
	// The type of allow list item. Set to `bundleID` to use a widget's bundle ID as its main ID.
	Type string `plist:"Type" json:"Type"`
	// The bundle ID of a widget.
	ID string `plist:"ID" json:"ID"`
}
