// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// Dictionary — Parental Controls: Dictionary.
// The payload that configures parental control dictionary restrictions.
//
// Supported: macOS 10.7+.
type Dictionary struct {
	// If `true`, enables parental controls dictionary restrictions.
	ParentalControl bool `plist:"parentalControl" json:"parentalControl"`
}
