// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for DirectoryServiceManaged.
func (DirectoryServiceManaged) PayloadType() string { return "com.apple.DirectoryService.managed" }

// Validate checks the payload against Apple's spec. DirectoryServiceManaged has no
// constraints beyond its field types.
func (p *DirectoryServiceManaged) Validate() error { return nil }
