// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// DnsProxyManaged — DNS Proxy.
// The payload that configures DNS proxies.
//
// Supported: iOS 11.0+, macOS 10.15+, visionOS 1.1+.
type DnsProxyManaged struct {
	// The bundle identifier of the app containing the DNS proxy network extension.
	AppBundleIdentifier string `plist:"AppBundleIdentifier" json:"AppBundleIdentifier"`
	// The bundle identifier of the DNS proxy network extension to use. Declaring the bundle identifier
	// is useful for apps that contain more than one DNS proxy extension.
	ProviderBundleIdentifier *string `plist:"ProviderBundleIdentifier,omitempty" json:"ProviderBundleIdentifier,omitempty"`
	// The dictionary of vendor-specific configuration items.
	ProviderConfiguration *DnsProxyManagedProviderConfiguration `plist:"ProviderConfiguration,omitempty" json:"ProviderConfiguration,omitempty"`
	// A globally unique identifier for this DNS proxy configuration. The proxy processes DNS lookups
	// traffic for managed apps with the same `DNSProxyUUID` in their app attributes. This key is
	// required for user enrollment.
	DNSProxyUUID *string `plist:"DNSProxyUUID,omitempty" json:"DNSProxyUUID,omitempty"`
}

// DnsProxyManagedProviderConfiguration is the ProviderConfiguration dictionary.
// The dictionary of vendor-specific configuration items.
type DnsProxyManagedProviderConfiguration struct {
	// Key/value pairs.
	ANY any `plist:"ANY,omitempty" json:"ANY,omitempty"`
}
