// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// Dock — Dock.
// The payload that configures the Dock.
//
// Supported: macOS 10.7+.
type Dock struct {
	// The tile size. Values must be in the range from 16 to 128.
	Tilesize *int64 `plist:"tilesize,omitempty" json:"tilesize,omitempty"`
	// If `true`, locks the size slider.
	//
	// Default: false.
	SizeImmutable *bool `plist:"size-immutable,omitempty" json:"size-immutable,omitempty"`
	// If `true`, enables magnification.
	//
	// Default: false.
	Magnification *bool `plist:"magnification,omitempty" json:"magnification,omitempty"`
	// If `true`, locks magnification.
	//
	// Default: false.
	MagnifyImmutable *bool `plist:"magnify-immutable,omitempty" json:"magnify-immutable,omitempty"`
	// The size of the largest magnification.
	Largesize *int64 `plist:"largesize,omitempty" json:"largesize,omitempty"`
	// If `true`, locks the magnification slider.
	//
	// Default: false.
	MagsizeImmutable *bool `plist:"magsize-immutable,omitempty" json:"magsize-immutable,omitempty"`
	// The orientation of the Dock.
	Orientation *DockOrientation `plist:"orientation,omitempty" json:"orientation,omitempty"`
	// If `true`, locks the position.
	//
	// Default: false.
	PositionImmutable *bool `plist:"position-immutable,omitempty" json:"position-immutable,omitempty"`
	// The minimize effect.
	Mineffect *DockMineffect `plist:"mineffect,omitempty" json:"mineffect,omitempty"`
	// If `true`, locks "Minimize windows using."
	//
	// Default: false.
	MineffectImmutable *bool `plist:"mineffect-immutable,omitempty" json:"mineffect-immutable,omitempty"`
	// Set the "Prefer tabs when opening documents" to the provided value.
	Windowtabbing *DockWindowtabbing `plist:"windowtabbing,omitempty" json:"windowtabbing,omitempty"`
	// If `true`, disables "Prefer tabs when opening documents" checkbox.
	//
	// Default: false.
	WindowtabbingImmutable *bool `plist:"windowtabbing-immutable,omitempty" json:"windowtabbing-immutable,omitempty"`
	// The behavior when the window's title bar is double-clicked.
	Dblclickbehavior *DockDblclickbehavior `plist:"dblclickbehavior,omitempty" json:"dblclickbehavior,omitempty"`
	// If `true`, locks "Double-click a window's title bar."
	//
	// Default: false.
	DblclickbehaviorImmutable *bool `plist:"dblclickbehavior-immutable,omitempty" json:"dblclickbehavior-immutable,omitempty"`
	// If `true`, enables "Minimize windows into application icon."
	//
	// Default: false.
	MinimizeToApplication *bool `plist:"minimize-to-application,omitempty" json:"minimize-to-application,omitempty"`
	// If `true`, disables the "Minimize windows into application icon" checkbox.
	//
	// Default: false.
	MinintoappImmutable *bool `plist:"minintoapp-immutable,omitempty" json:"minintoapp-immutable,omitempty"`
	// If `true`, enables "Animate opening applications."
	//
	// Default: false.
	Launchanim *bool `plist:"launchanim,omitempty" json:"launchanim,omitempty"`
	// If `true`, locks "Animate opening applications."
	//
	// Default: false.
	LaunchanimImmutable *bool `plist:"launchanim-immutable,omitempty" json:"launchanim-immutable,omitempty"`
	// If `true`, enables "Automatically hide and show the Dock."
	//
	// Default: false.
	Autohide *bool `plist:"autohide,omitempty" json:"autohide,omitempty"`
	// If `true`, locks "Automatically hide."
	//
	// Default: false.
	AutohideImmutable *bool `plist:"autohide-immutable,omitempty" json:"autohide-immutable,omitempty"`
	// If true, shows the process indicator.
	//
	// Default: false.
	ShowProcessIndicators *bool `plist:"show-process-indicators,omitempty" json:"show-process-indicators,omitempty"`
	// If `true`, locks "Show indicators."
	//
	// Default: false.
	ShowindicatorsImmutable *bool `plist:"showindicators-immutable,omitempty" json:"showindicators-immutable,omitempty"`
	// If `true`, enables "Show recent items."
	//
	// Default: false.
	ShowRecents *bool `plist:"show-recents,omitempty" json:"show-recents,omitempty"`
	// If `true`, disables "Show recent applications" checkbox.
	//
	// Default: false.
	ShowrecentsImmutable *bool `plist:"showrecents-immutable,omitempty" json:"showrecents-immutable,omitempty"`
	// If `true`, disables changes to the Dock.
	//
	// Default: false.
	ContentsImmutable *bool `plist:"contents-immutable,omitempty" json:"contents-immutable,omitempty"`
	// One or more special folders that may be created at user login time and placed in the Dock.
	MCXDockSpecialFolders []string `plist:"MCXDockSpecialFolders,omitempty" json:"MCXDockSpecialFolders,omitempty"`
	// If `true`, use the file in `/Library/Preferences/com.apple.dockfixup.plist` when a new user or
	// migrated user logs in. This option has no effect for existing users. Available in macOS 10.12
	// and later. Only available on the device channel.
	//
	// Default: false.
	AllowDockFixupOverride *bool `plist:"AllowDockFixupOverride,omitempty" json:"AllowDockFixupOverride,omitempty"`
	// If `true`, uses the `static-apps` and `static-others` dictionaries for the Dock and ignores any
	// items in the `persistent-apps` and `persistent-others` dictionaries. If `false`, the contents
	// are merged with the static items listed first.
	//
	// Default: false.
	StaticOnly *bool `plist:"static-only,omitempty" json:"static-only,omitempty"`
	// An array of items located on the Documents side of the Dock and cannot be removed from that
	// location.
	StaticOthers []DockStaticItem `plist:"static-others,omitempty" json:"static-others,omitempty"`
	// An array of items located on the Applications side of the Dock and cannot be removed from that
	// location.
	StaticApps []DockStaticItem `plist:"static-apps,omitempty" json:"static-apps,omitempty"`
	// An array of items located on the Applications side of the Dock that can be removed from the
	// Dock.
	PersistentApps []DockStaticItem `plist:"persistent-apps,omitempty" json:"persistent-apps,omitempty"`
	// An array of items located on the Documents side of the Dock that can be removed from the Dock.
	PersistentOthers []DockStaticItem `plist:"persistent-others,omitempty" json:"persistent-others,omitempty"`
}

// DockStaticItemTileDataFileData is the file-data dictionary.
// The data in a file. For Apple use only.
type DockStaticItemTileDataFileData struct {
	// For Apple use only.
	ANY any `plist:"ANY,omitempty" json:"ANY,omitempty"`
}

// DockStaticItemTileData is the tile-data dictionary.
// The information about the Dock item.
type DockStaticItemTileData struct {
	// The label of the Dock item.
	Label string `plist:"label" json:"label"`
	// The URL string.
	Url *string `plist:"url,omitempty" json:"url,omitempty"`
	// The type of tile:
	FileType DockStaticItemTileDataFileType `plist:"file-type" json:"file-type"`
	// The data in a file. For Apple use only.
	FileData *DockStaticItemTileDataFileData `plist:"file-data,omitempty" json:"file-data,omitempty"`
}

// DockStaticItem is the StaticItem dictionary.
// Items that are located on the Documents side of the Dock and cannot be removed from that
// location.
type DockStaticItem struct {
	// The information about the Dock item.
	TileData DockStaticItemTileData `plist:"tile-data" json:"tile-data"`
	// The type of tile.
	TileType DockStaticItemTileType `plist:"tile-type" json:"tile-type"`
}
