// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for Domains.
func (Domains) PayloadType() string { return "com.apple.domains" }

// Validate checks the payload against Apple's spec. Domains has no
// constraints beyond its field types.
func (p *Domains) Validate() error { return nil }
