// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"fmt"
)

// EasAccountMailNumberOfPastDaysToSync — allowed values for EasAccount.MailNumberOfPastDaysToSync.
type EasAccountMailNumberOfPastDaysToSync int64

// EasAccountMailNumberOfPastDaysToSync allowed values.
const (
	EasAccountMailNumberOfPastDaysToSyncValue0  EasAccountMailNumberOfPastDaysToSync = 0
	EasAccountMailNumberOfPastDaysToSyncValue1  EasAccountMailNumberOfPastDaysToSync = 1
	EasAccountMailNumberOfPastDaysToSyncValue3  EasAccountMailNumberOfPastDaysToSync = 3
	EasAccountMailNumberOfPastDaysToSyncValue7  EasAccountMailNumberOfPastDaysToSync = 7
	EasAccountMailNumberOfPastDaysToSyncValue14 EasAccountMailNumberOfPastDaysToSync = 14
	EasAccountMailNumberOfPastDaysToSyncValue31 EasAccountMailNumberOfPastDaysToSync = 31
)

// String returns the EasAccountMailNumberOfPastDaysToSync constant's name, or its numeric form
// when the value is not a known constant.
func (e EasAccountMailNumberOfPastDaysToSync) String() string {
	switch e {
	case EasAccountMailNumberOfPastDaysToSyncValue0:
		return "EasAccountMailNumberOfPastDaysToSyncValue0"
	case EasAccountMailNumberOfPastDaysToSyncValue1:
		return "EasAccountMailNumberOfPastDaysToSyncValue1"
	case EasAccountMailNumberOfPastDaysToSyncValue3:
		return "EasAccountMailNumberOfPastDaysToSyncValue3"
	case EasAccountMailNumberOfPastDaysToSyncValue7:
		return "EasAccountMailNumberOfPastDaysToSyncValue7"
	case EasAccountMailNumberOfPastDaysToSyncValue14:
		return "EasAccountMailNumberOfPastDaysToSyncValue14"
	case EasAccountMailNumberOfPastDaysToSyncValue31:
		return "EasAccountMailNumberOfPastDaysToSyncValue31"
	default:
		return fmt.Sprintf("EasAccountMailNumberOfPastDaysToSync(%d)", int64(e))
	}
}
