// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for EasAccount.
func (EasAccount) PayloadType() string { return "com.apple.eas.account" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *EasAccount) Validate() error {
	var errs []error
	if p.PayloadCertificateUUID != nil {
		if err := validate.Format("PayloadCertificateUUID", *p.PayloadCertificateUUID, "^[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{12}$"); err != nil {
			errs = append(errs, err)
		}
	}
	if p.SMIMESigningCertificateUUID != nil {
		if err := validate.Format("SMIMESigningCertificateUUID", *p.SMIMESigningCertificateUUID, "^[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{12}$"); err != nil {
			errs = append(errs, err)
		}
	}
	if p.SMIMEEncryptionCertificateUUID != nil {
		if err := validate.Format("SMIMEEncryptionCertificateUUID", *p.SMIMEEncryptionCertificateUUID, "^[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{12}$"); err != nil {
			errs = append(errs, err)
		}
	}
	if p.MailNumberOfPastDaysToSync != nil {
		if err := validate.InList("MailNumberOfPastDaysToSync", *p.MailNumberOfPastDaysToSync, []EasAccountMailNumberOfPastDaysToSync{EasAccountMailNumberOfPastDaysToSyncValue0, EasAccountMailNumberOfPastDaysToSyncValue1, EasAccountMailNumberOfPastDaysToSyncValue3, EasAccountMailNumberOfPastDaysToSyncValue7, EasAccountMailNumberOfPastDaysToSyncValue14, EasAccountMailNumberOfPastDaysToSyncValue31}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.CommunicationServiceRules != nil {
		if err := p.CommunicationServiceRules.Validate(); err != nil {
			errs = append(errs, validate.Nested("CommunicationServiceRules", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. EasAccountCommunicationServiceRulesDefaultServiceHandlers has no
// constraints beyond its field types.
func (p *EasAccountCommunicationServiceRulesDefaultServiceHandlers) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *EasAccountCommunicationServiceRules) Validate() error {
	var errs []error
	if p.DefaultServiceHandlers != nil {
		if err := p.DefaultServiceHandlers.Validate(); err != nil {
			errs = append(errs, validate.Nested("DefaultServiceHandlers", err))
		}
	}
	return errors.Join(errs...)
}
