// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// EasAccount — Exchange ActiveSync.
// The payload that configures Exchange ActiveSync accounts.
//
// Supported: iOS 4.0+, visionOS 1.1+.
type EasAccount struct {
	// The full email address for the account. If not present in the payload, the device prompts for
	// this string during profile installation.
	EmailAddress *string `plist:"EmailAddress,omitempty" json:"EmailAddress,omitempty"`
	// The Exchange server host name or IP address.
	Host *string `plist:"Host,omitempty" json:"Host,omitempty"`
	// If `true`, the system enables SSL for authentication.
	//
	// Default: false.
	SSL *bool `plist:"SSL,omitempty" json:"SSL,omitempty"`
	// If `true`, enables OAuth for authentication. If enabled, don't specify a password.
	//
	// Default: false.
	OAuth *bool `plist:"OAuth,omitempty" json:"OAuth,omitempty"`
	// This user name for this Exchange account. Required for noninteractive installations like MDM in
	// iOS.
	UserName *string `plist:"UserName,omitempty" json:"UserName,omitempty"`
	// The password of the account. Use only with encrypted profiles.
	Password *string `plist:"Password,omitempty" json:"Password,omitempty"`
	// The `.p12` identity certificate in NSData blob format, for accounts that allow authentication
	// via certificate.
	Certificate []byte `plist:"Certificate,omitempty" json:"Certificate,omitempty"`
	// The name or description of the certificate.
	CertificateName *string `plist:"CertificateName,omitempty" json:"CertificateName,omitempty"`
	// The password necessary for the `.p12` identity certificate. Used with mandatory encryption of
	// profiles.
	CertificatePassword *string `plist:"CertificatePassword,omitempty" json:"CertificatePassword,omitempty"`
	// If `true`, the system prevents moving messages from out of this email account into another
	// account. This setting also prevents forwarding or replying from an account other than the
	// recipient of the message.
	//
	// Default: false.
	PreventMove *bool `plist:"PreventMove,omitempty" json:"PreventMove,omitempty"`
	// If `true`, prevents this account from sending mail in any app other than the Apple Mail app.
	//
	// Default: false.
	PreventAppSheet *bool `plist:"PreventAppSheet,omitempty" json:"PreventAppSheet,omitempty"`
	// The UUID of the certificate payload within the same profile to use for the identity credential.
	// If this field is present, the Certificate field isn't used.
	PayloadCertificateUUID *string `plist:"PayloadCertificateUUID,omitempty" json:"PayloadCertificateUUID,omitempty"`
	// If `true`, the system enables S/MIME encryption. In iOS 10.0 and later, this key is ignored. Use
	// `SMIMESigningEnabled` instead.
	//
	// Default: false.
	SMIMEEnabled *bool `plist:"SMIMEEnabled,omitempty" json:"SMIMEEnabled,omitempty"`
	// If `true`, the system enables S/MIME signing for this account. Available in iOS 10.0 and later.
	//
	// Default: false.
	SMIMESigningEnabled *bool `plist:"SMIMESigningEnabled,omitempty" json:"SMIMESigningEnabled,omitempty"`
	// The UUID of the identity certificate used to sign messages sent from this account.
	SMIMESigningCertificateUUID *string `plist:"SMIMESigningCertificateUUID,omitempty" json:"SMIMESigningCertificateUUID,omitempty"`
	// If `true`, the system enables S/MIME encryption for this account. Available in iOS 10.0 and
	// later. As of iOS 12.0, this key is deprecated. Use `SMIMEEncryptByDefault` instead.
	//
	// Default: false.
	SMIMEEncryptionEnabled *bool `plist:"SMIMEEncryptionEnabled,omitempty" json:"SMIMEEncryptionEnabled,omitempty"`
	// The payload UUID of the identity certificate used to decrypt messages sent to this account. The
	// system attaches the public certificate to outgoing mail to allow the user to receive encrypted
	// mail. When the user sends encrypted mail, the system uses the public certificate to encrypt the
	// copy of the mail in the user's Sent mailbox.
	SMIMEEncryptionCertificateUUID *string `plist:"SMIMEEncryptionCertificateUUID,omitempty" json:"SMIMEEncryptionCertificateUUID,omitempty"`
	// If `true`, the system displays the per-message encryption switch in the Mail Compose UI.
	//
	// Default: false.
	SMIMEEnablePerMessageSwitch *bool `plist:"SMIMEEnablePerMessageSwitch,omitempty" json:"SMIMEEnablePerMessageSwitch,omitempty"`
	// If `true`, the system excludes this account from Recent Addresses syncing.
	//
	// Default: false.
	DisableMailRecentsSyncing *bool `plist:"disableMailRecentsSyncing,omitempty" json:"disableMailRecentsSyncing,omitempty"`
	// The number of days in the past to sync mail on the device.
	//
	// Default: 7.
	MailNumberOfPastDaysToSync *EasAccountMailNumberOfPastDaysToSync `plist:"MailNumberOfPastDaysToSync,omitempty" json:"MailNumberOfPastDaysToSync,omitempty"`
	// The value of the `X-Apple-Config-Magic` header in each EAS HTTP request.
	HeaderMagic *string `plist:"HeaderMagic,omitempty" json:"HeaderMagic,omitempty"`
	// The communication service handler rules for this account.
	CommunicationServiceRules *EasAccountCommunicationServiceRules `plist:"CommunicationServiceRules,omitempty" json:"CommunicationServiceRules,omitempty"`
	// If `true`, the system enables this account to use Mail Drop.
	//
	// Default: false.
	AllowMailDrop *bool `plist:"allowMailDrop,omitempty" json:"allowMailDrop,omitempty"`
	// If `true`, the user can turn S/MIME signing on or off in Settings. Available in iOS 12.0 and
	// later.
	//
	// Default: false.
	SMIMESigningUserOverrideable *bool `plist:"SMIMESigningUserOverrideable,omitempty" json:"SMIMESigningUserOverrideable,omitempty"`
	// If `true`, the user can select the signing identity. Available in iOS 12.0 and later.
	//
	// Default: false.
	SMIMESigningCertificateUUIDUserOverrideable *bool `plist:"SMIMESigningCertificateUUIDUserOverrideable,omitempty" json:"SMIMESigningCertificateUUIDUserOverrideable,omitempty"`
	// If `true`, the system enables S/MIME encryption by default. If
	// `SMIMEEnableEncryptionPerMessageSwitch` is `false`, the user can't change this default.
	// Available in iOS 12.0 and later.
	//
	// Default: false.
	SMIMEEncryptByDefault *bool `plist:"SMIMEEncryptByDefault,omitempty" json:"SMIMEEncryptByDefault,omitempty"`
	// If `true`, the system enables encryption by default and the user can't change it. Available in
	// iOS 12.0 and later.
	//
	// Default: false.
	SMIMEEncryptByDefaultUserOverrideable *bool `plist:"SMIMEEncryptByDefaultUserOverrideable,omitempty" json:"SMIMEEncryptByDefaultUserOverrideable,omitempty"`
	// If `true`, the user can select the S/MIME encryption identity, and encryption is on.Available in
	// iOS 12.0 and later.
	//
	// Default: false.
	SMIMEEncryptionCertificateUUIDUserOverrideable *bool `plist:"SMIMEEncryptionCertificateUUIDUserOverrideable,omitempty" json:"SMIMEEncryptionCertificateUUIDUserOverrideable,omitempty"`
	// If `true`, the system displays the per-message encryption switch in the Mail Compose UI.
	// Available in iOS 12.0 and later.
	//
	// Default: false.
	SMIMEEnableEncryptionPerMessageSwitch *bool `plist:"SMIMEEnableEncryptionPerMessageSwitch,omitempty" json:"SMIMEEnableEncryptionPerMessageSwitch,omitempty"`
	// If `false`, the system disables the Mail service for this account. The user can reenable Mail
	// service in Settings unless `EnableMailUserOverridable` is `false`.
	//
	// Default: true.
	EnableMail *bool `plist:"EnableMail,omitempty" json:"EnableMail,omitempty"`
	// If `false`, the system disables the Contacts service for this account. The user can reenable
	// Contacts service in Settings unless `EnableContactsUserOverridable` is `false`.
	//
	// Default: true.
	EnableContacts *bool `plist:"EnableContacts,omitempty" json:"EnableContacts,omitempty"`
	// If `false`, the system disables the Calendars service for this account. The user can reenable
	// Calendars service in Settings unless `EnableCalendarsUserOverridable` is `false`.
	//
	// Default: true.
	EnableCalendars *bool `plist:"EnableCalendars,omitempty" json:"EnableCalendars,omitempty"`
	// If `false`, the system disables the Reminders service for this account. The user can reenable
	// Reminders service in Settings unless `EnableRemindersUserOverridable` is `false`.
	//
	// Default: true.
	EnableReminders *bool `plist:"EnableReminders,omitempty" json:"EnableReminders,omitempty"`
	// If `false`, the system disables the Notes service for this account. The user can reenable Notes
	// service in Settings unless `EnableNotesUserOverridable` is `false`.
	//
	// Default: true.
	EnableNotes *bool `plist:"EnableNotes,omitempty" json:"EnableNotes,omitempty"`
	// If `false`, the system prevents the user from changing the state of the Mail service for this
	// account in Settings.
	//
	// Default: true.
	EnableMailUserOverridable *bool `plist:"EnableMailUserOverridable,omitempty" json:"EnableMailUserOverridable,omitempty"`
	// If `false`, the system prevents the user from changing the state of the Contacts service for
	// this account in Settings.
	//
	// Default: true.
	EnableContactsUserOverridable *bool `plist:"EnableContactsUserOverridable,omitempty" json:"EnableContactsUserOverridable,omitempty"`
	// If `false`, the system prevents the user from changing the state of the Calendars service for
	// this account in Settings.
	//
	// Default: true.
	EnableCalendarsUserOverridable *bool `plist:"EnableCalendarsUserOverridable,omitempty" json:"EnableCalendarsUserOverridable,omitempty"`
	// If `false`, the system prevents the user from changing the state of the Reminders service for
	// this account in Settings.
	//
	// Default: true.
	EnableRemindersUserOverridable *bool `plist:"EnableRemindersUserOverridable,omitempty" json:"EnableRemindersUserOverridable,omitempty"`
	// If `false`, prevents the user from changing the state of the Notes service for this account in
	// Settings.
	//
	// Default: true.
	EnableNotesUserOverridable *bool `plist:"EnableNotesUserOverridable,omitempty" json:"EnableNotesUserOverridable,omitempty"`
	// The URL that this account should use for signing in through OAuth. Ignored unless `OAuth` is
	// `true`. If you specify this URL, auto-discovery isn't used for this account, so you need to also
	// specify a host.
	OAuthSignInURL *string `plist:"OAuthSignInURL,omitempty" json:"OAuthSignInURL,omitempty"`
	// The URL that this account should use for token requests through OAuth. Ignored unless `OAuth` is
	// `true`.
	OAuthTokenRequestURL *string `plist:"OAuthTokenRequestURL,omitempty" json:"OAuthTokenRequestURL,omitempty"`
	// If `true`, the system overrides the previous user/EAS password with the new EAS password in the
	// payload. Available in iOS 14 and later.
	//
	// Default: false.
	OverridePreviousPassword *bool `plist:"OverridePreviousPassword,omitempty" json:"OverridePreviousPassword,omitempty"`
	// The VPNUUID of the per-app VPN the account uses for network communication. Available in iOS 14
	// and later.
	VPNUUID *string `plist:"VPNUUID,omitempty" json:"VPNUUID,omitempty"`
}

// EasAccountCommunicationServiceRulesDefaultServiceHandlers is the DefaultServiceHandlers dictionary.
// The default handlers to use for contacts from this account.
type EasAccountCommunicationServiceRulesDefaultServiceHandlers struct {
	// The bundle identifier of the default application to use for audio calls made to contacts from
	// this account.
	AudioCall *string `plist:"AudioCall,omitempty" json:"AudioCall,omitempty"`
}

// EasAccountCommunicationServiceRules is the CommunicationServiceRules dictionary.
// The communication service handler rules for this account.
type EasAccountCommunicationServiceRules struct {
	// The default handlers to use for contacts from this account.
	DefaultServiceHandlers *EasAccountCommunicationServiceRulesDefaultServiceHandlers `plist:"DefaultServiceHandlers,omitempty" json:"DefaultServiceHandlers,omitempty"`
}
