// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for Education.
func (Education) PayloadType() string { return "com.apple.education" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *Education) Validate() error {
	var errs []error
	for i := range p.Departments {
		if err := p.Departments[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Departments", i, err))
		}
	}
	if p.Groups == nil {
		errs = append(errs, validate.Required("Groups"))
	}
	for i := range p.Groups {
		if err := p.Groups[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Groups", i, err))
		}
	}
	if p.Users == nil {
		errs = append(errs, validate.Required("Users"))
	}
	for i := range p.Users {
		if err := p.Users[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Users", i, err))
		}
	}
	for i := range p.DeviceGroups {
		if err := p.DeviceGroups[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("DeviceGroups", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *EducationDepartmentsItem) Validate() error {
	var errs []error
	if p.GroupBeaconIDs == nil {
		errs = append(errs, validate.Required("GroupBeaconIDs"))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *EducationGroupsItem) Validate() error {
	var errs []error
	if p.MemberIdentifiers == nil {
		errs = append(errs, validate.Required("MemberIdentifiers"))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *EducationUsersItem) Validate() error {
	var errs []error
	if p.PasscodeType != nil {
		if err := validate.InList("PasscodeType", *p.PasscodeType, []EducationUsersItemPasscodeType{EducationUsersItemPasscodeTypeComplex, EducationUsersItemPasscodeTypeFour, EducationUsersItemPasscodeTypeSix}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *EducationDeviceGroupsItem) Validate() error {
	var errs []error
	if p.SerialNumbers == nil {
		errs = append(errs, validate.Required("SerialNumbers"))
	}
	return errors.Join(errs...)
}
