// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// EwsAccount — Exchange Web Services.
// The payload that configures an Exchange Web Services accounts.
//
// Supported: macOS 10.7+.
type EwsAccount struct {
	// The full email address for the account. If the email address string isn't present in the
	// payload, the device prompts for it during profile installation.
	EmailAddress *string `plist:"EmailAddress,omitempty" json:"EmailAddress,omitempty"`
	// The Exchange server host name or IP address. Ignored if using OAuth.
	Host *string `plist:"Host,omitempty" json:"Host,omitempty"`
	// If `true`, the system enables SSL.
	//
	// Default: true.
	SSL *bool `plist:"SSL,omitempty" json:"SSL,omitempty"`
	// If `true`, the system enables OAuth for authentication. Don't specify a password if `OAuth` is
	// `true`. Available in macOS 10.14 and later
	//
	// Default: false.
	OAuth *bool `plist:"OAuth,omitempty" json:"OAuth,omitempty"`
	// The URL to load into a web view for authentication through OAuth when autodiscovery isn't used.
	// This setting requires a `Host` value.
	OAuthSignInURL *string `plist:"OAuthSignInURL,omitempty" json:"OAuthSignInURL,omitempty"`
	// The user name for this Exchange account. Required for noninteractive installation, such as
	// through MDM. If missing, the system prompts the user for it during interactive profile
	// installation.
	UserName *string `plist:"UserName,omitempty" json:"UserName,omitempty"`
	// The password of the account. Use only with encrypted profiles.
	Password *string `plist:"Password,omitempty" json:"Password,omitempty"`
	// The UUID of the certificate payload within the same profile to use for the identity credential.
	// Supported on macOS 10.12 or later.
	PayloadCertificateUUID *string `plist:"PayloadCertificateUUID,omitempty" json:"PayloadCertificateUUID,omitempty"`
	// The UUID of the certificate payload within the same profile to use for the identity credential.
	// Supported on macOS 10.11 or later. On macOS 10.12 or later use the PayloadCertificateUUID.
	AuthenticationCertificateUUID *string `plist:"AuthenticationCertificateUUID,omitempty" json:"AuthenticationCertificateUUID,omitempty"`
	// If `true`, the system enables Mail Drop.
	//
	// Default: false.
	AllowMailDrop *bool `plist:"allowMailDrop,omitempty" json:"allowMailDrop,omitempty"`
	// The server path.
	Path *string `plist:"Path,omitempty" json:"Path,omitempty"`
	// The server port number.
	Port *int64 `plist:"Port,omitempty" json:"Port,omitempty"`
	// The external server address.
	ExternalHost *string `plist:"ExternalHost,omitempty" json:"ExternalHost,omitempty"`
	// If `true`, the system enables SSL for connections to the external server.
	//
	// Default: true.
	ExternalSSL *bool `plist:"ExternalSSL,omitempty" json:"ExternalSSL,omitempty"`
	// The external server path.
	ExternalPath *string `plist:"ExternalPath,omitempty" json:"ExternalPath,omitempty"`
	// The external server port number.
	ExternalPort *int64 `plist:"ExternalPort,omitempty" json:"ExternalPort,omitempty"`
}
