// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// Extensiblesso2ExtensionDataCredentialUseMode — allowed values for Extensiblesso2ExtensionData.CredentialUseMode.
type Extensiblesso2ExtensionDataCredentialUseMode string

// Extensiblesso2ExtensionDataCredentialUseMode allowed values.
const (
	Extensiblesso2ExtensionDataCredentialUseModeAlways           Extensiblesso2ExtensionDataCredentialUseMode = "always"
	Extensiblesso2ExtensionDataCredentialUseModeWhenNotSpecified Extensiblesso2ExtensionDataCredentialUseMode = "whenNotSpecified"
	Extensiblesso2ExtensionDataCredentialUseModeKerberosDefault  Extensiblesso2ExtensionDataCredentialUseMode = "kerberosDefault"
)

// String returns the Extensiblesso2ExtensionDataCredentialUseMode value as a plain string.
func (e Extensiblesso2ExtensionDataCredentialUseMode) String() string { return string(e) }
