// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// FamilycontrolsTimelimitsV2 — Parental Controls: Time Limits.
// The payload that configures parental control time limits.
//
// Supported: macOS 10.7+.
type FamilycontrolsTimelimitsV2 struct {
	// If `true`, enables time limits.
	FamilyControlsEnabled bool `plist:"familyControlsEnabled" json:"familyControlsEnabled"`
	// The time limits to enforce if `familyControlsEnabled` is enabled.
	TimeLimits *FamilycontrolsTimelimitsV2TimeLimits `plist:"time-limits,omitempty" json:"time-limits,omitempty"`
}

// Allowance is the weekday-allowance dictionary.
// The weekday allowance settings.
type Allowance struct {
	// If `true`, enable these settings.
	Enabled bool `plist:"enabled" json:"enabled"`
	// The type of day range, which has the following possible values:
	RangeType AllowanceRangeType `plist:"rangeType" json:"rangeType"`
	// The curfew start time, in the format '%d:%d:%d'.
	Start *string `plist:"start,omitempty" json:"start,omitempty"`
	// The curfew end time, in the format `%d:%d:%d`.
	End *string `plist:"end,omitempty" json:"end,omitempty"`
	// The allowance for that day, in seconds.
	SecondsPerDay *int64 `plist:"secondsPerDay,omitempty" json:"secondsPerDay,omitempty"`
}

// FamilycontrolsTimelimitsV2TimeLimits is the time-limits dictionary.
// The time limits to enforce if `familyControlsEnabled` is enabled.
type FamilycontrolsTimelimitsV2TimeLimits struct {
	// The weekday allowance settings.
	WeekdayAllowance *Allowance `plist:"weekday-allowance,omitempty" json:"weekday-allowance,omitempty"`
	// The weekday curfew settings.
	WeekdayCurfew *Allowance `plist:"weekday-curfew,omitempty" json:"weekday-curfew,omitempty"`
	// The weekend allowance settings.
	WeekendAllowance *Allowance `plist:"weekend-allowance,omitempty" json:"weekend-allowance,omitempty"`
	// The weekend curfew settings.
	WeekendCurfew *Allowance `plist:"weekend-curfew,omitempty" json:"weekend-curfew,omitempty"`
}
