// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"fmt"
)

// AllowanceRangeType — allowed values for Allowance.RangeType.
type AllowanceRangeType int64

// AllowanceRangeType allowed values.
const (
	AllowanceRangeTypeValue0 AllowanceRangeType = 0
	AllowanceRangeTypeValue1 AllowanceRangeType = 1
)

// String returns the AllowanceRangeType constant's name, or its numeric form
// when the value is not a known constant.
func (e AllowanceRangeType) String() string {
	switch e {
	case AllowanceRangeTypeValue0:
		return "AllowanceRangeTypeValue0"
	case AllowanceRangeTypeValue1:
		return "AllowanceRangeTypeValue1"
	default:
		return fmt.Sprintf("AllowanceRangeType(%d)", int64(e))
	}
}
