// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for Fileproviderd.
func (Fileproviderd) PayloadType() string { return "com.apple.fileproviderd" }

// Validate checks the payload against Apple's spec. Fileproviderd has no
// constraints beyond its field types.
func (p *Fileproviderd) Validate() error { return nil }
