// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// FirstethernetManaged — 802.1X: First Ethernet.
// The payload that configures the first wired Ethernet interface.
//
// Supported: macOS 10.7+.
type FirstethernetManaged struct {
	// Keys relevant to 802.1x configuration. User enrollment payloads do not support the various proxy
	// keys including ProxyType, ProxyServer, ProxyServerPort, ProxyUsername, ProxyPassword,,
	// ProxyPACURL and ProxyPACFallbackAllowed.
	ANY any `plist:"ANY,omitempty" json:"ANY,omitempty"`
}
