// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for Gamed.
func (Gamed) PayloadType() string { return "com.apple.gamed" }

// Validate checks the payload against Apple's spec. Gamed has no
// constraints beyond its field types.
func (p *Gamed) Validate() error { return nil }
