// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// GoogleOauth — Google Account.
// The payload that configures a Google account.
//
// Supported: iOS 9.3+, visionOS 1.1+.
type GoogleOauth struct {
	// A user-visible description of the Google account, shown in the Mail and Settings apps.
	AccountDescription *string `plist:"AccountDescription,omitempty" json:"AccountDescription,omitempty"`
	// The user's full name for the Google account. This name appears in sent messages.
	AccountName *string `plist:"AccountName,omitempty" json:"AccountName,omitempty"`
	// The full Google email address for the account.
	EmailAddress string `plist:"EmailAddress" json:"EmailAddress"`
	// The communication service handler rules for this account.
	CommunicationServiceRules *GoogleOauthCommunicationServiceRules `plist:"CommunicationServiceRules,omitempty" json:"CommunicationServiceRules,omitempty"`
	// The VPNUUID of the per-app VPN the account uses for network communication. Available in iOS 14
	// and later.
	VPNUUID *string `plist:"VPNUUID,omitempty" json:"VPNUUID,omitempty"`
}

// GoogleOauthCommunicationServiceRulesDefaultServiceHandlers is the DefaultServiceHandlers dictionary.
// A dictionary that defines which app to use for audio calls from this account.
type GoogleOauthCommunicationServiceRulesDefaultServiceHandlers struct {
	// The bundle identifier for the default application that handles audio calls to contacts from this
	// account.
	AudioCall *string `plist:"AudioCall,omitempty" json:"AudioCall,omitempty"`
}

// GoogleOauthCommunicationServiceRules is the CommunicationServiceRules dictionary.
// The communication service handler rules for this account.
type GoogleOauthCommunicationServiceRules struct {
	// A dictionary that defines which app to use for audio calls from this account.
	DefaultServiceHandlers *GoogleOauthCommunicationServiceRulesDefaultServiceHandlers `plist:"DefaultServiceHandlers,omitempty" json:"DefaultServiceHandlers,omitempty"`
}
