// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// IronwoodSupport — Parental Control: Dictation and Profanity.
// The payload that configures parental control for dictation and profanity.
//
// Supported: macOS 10.9+.
type IronwoodSupport struct {
	// If `false`, suppresses profanity. Use `forceAssistantProfanityFilter` in Restrictions instead.
	//
	// Default: true.
	ProfanityAllowed *bool `plist:"Profanity Allowed,omitempty" json:"Profanity Allowed,omitempty"`
	// If `false`, disables dictation. Use `allowDictation` in Restrictions instead.
	//
	// Default: true.
	IronwoodAllowed *bool `plist:"Ironwood Allowed,omitempty" json:"Ironwood Allowed,omitempty"`
}
