// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for IronwoodSupport.
func (IronwoodSupport) PayloadType() string { return "com.apple.ironwood.support" }

// Validate checks the payload against Apple's spec. IronwoodSupport has no
// constraints beyond its field types.
func (p *IronwoodSupport) Validate() error { return nil }
