// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// JabberAccount — Jabber Account.
// The payload that configures a Jabber account.
//
// Supported: macOS 10.7–10.14.
type JabberAccount struct {
	// The description of the account.
	JabberAccountDescription *string `plist:"JabberAccountDescription,omitempty" json:"JabberAccountDescription,omitempty"`
	// The server's address.
	JabberHostName string `plist:"JabberHostName" json:"JabberHostName"`
	// The user's user name.
	JabberUserName *string `plist:"JabberUserName,omitempty" json:"JabberUserName,omitempty"`
	// The user's password.
	JabberPassword *string `plist:"JabberPassword,omitempty" json:"JabberPassword,omitempty"`
	// If `true`, enables SSL.
	//
	// Default: false.
	JabberUseSSL *bool `plist:"JabberUseSSL,omitempty" json:"JabberUseSSL,omitempty"`
	// The server's port.
	//
	// Default: 5222.
	JabberPort *int64 `plist:"JabberPort,omitempty" json:"JabberPort,omitempty"`
	// The authentication method for the account.
	JabberAuthentication string `plist:"JabberAuthentication" json:"JabberAuthentication"`
}
