// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// LoginitemsManaged — Login Items: Managed Items.
// The payload that configures a device's login items.
//
// Supported: macOS 10.13+.
type LoginitemsManaged struct {
	// An array of login item dictionaries.
	AutoLaunchedApplicationDictionaryManaged []LoginitemsManagedLoginItem `plist:"AutoLaunchedApplicationDictionary-managed" json:"AutoLaunchedApplicationDictionary-managed"`
}

// LoginitemsManagedLoginItem is the LoginItem dictionary.
// A login item.
type LoginitemsManagedLoginItem struct {
	// The URL or path string to the item's location.
	Path string `plist:"Path" json:"Path"`
	// If `true`, the system hides this item in the Users & Groups login items list.
	//
	// Default: false.
	Hide *bool `plist:"Hide,omitempty" json:"Hide,omitempty"`
}
