// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for LoginitemsManaged.
func (LoginitemsManaged) PayloadType() string { return "com.apple.loginitems.managed" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *LoginitemsManaged) Validate() error {
	var errs []error
	if p.AutoLaunchedApplicationDictionaryManaged == nil {
		errs = append(errs, validate.Required("AutoLaunchedApplicationDictionary-managed"))
	}
	for i := range p.AutoLaunchedApplicationDictionaryManaged {
		if err := p.AutoLaunchedApplicationDictionaryManaged[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AutoLaunchedApplicationDictionary-managed", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. LoginitemsManagedLoginItem has no
// constraints beyond its field types.
func (p *LoginitemsManagedLoginItem) Validate() error { return nil }
