// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// Lom — Lights Out Management (LOM).
// The payload that configures lights-out management (LOM) settings.
//
// Supported: macOS 11.0+.
type Lom struct {
	// The UUID certificate for the device. This key indicates the device can receive `PowerON`,
	// `PowerOFF`, and `Reset` requests from a LOM controller. This certificate must contain the Key
	// Usage attributes of Digital Signature, Key Encipherment and Data Encipherment. As well as the
	// Extended Key Usage attributes of Server Authentication and Client Authentication.
	DeviceCertificateUUID *string `plist:"DeviceCertificateUUID,omitempty" json:"DeviceCertificateUUID,omitempty"`
	// The UUID certificate for the LOM controller. This key configures the device to accept the
	// `LOMDeviceRequestCommand` from MDM and then send it to the target device.
	ControllerCertificateUUID *string `plist:"ControllerCertificateUUID,omitempty" json:"ControllerCertificateUUID,omitempty"`
	// An array of payload UUIDs containing CA certificates that controllers use to evaluate trust of
	// device certificates.
	DeviceCACertificateUUIDs []string `plist:"DeviceCACertificateUUIDs,omitempty" json:"DeviceCACertificateUUIDs,omitempty"`
	// An array of payload UUIDs containing CA certificates that devices use to evaluate trust of
	// controller certificates.
	ControllerCACertificateUUIDs []string `plist:"ControllerCACertificateUUIDs,omitempty" json:"ControllerCACertificateUUIDs,omitempty"`
}
