// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// MailManaged — Mail.
// The payload that configures a Mail account.
//
// Supported: iOS 4.0+, macOS 10.7+, visionOS 1.1+.
type MailManaged struct {
	// A user-visible description of the email account, shown in the Mail and Settings applications.
	EmailAccountDescription *string `plist:"EmailAccountDescription,omitempty" json:"EmailAccountDescription,omitempty"`
	// The full user name for the account. The system displays this name in sent messages.
	EmailAccountName *string `plist:"EmailAccountName,omitempty" json:"EmailAccountName,omitempty"`
	// Defines the protocol to use for the account.
	EmailAccountType MailManagedEmailAccountType `plist:"EmailAccountType" json:"EmailAccountType"`
	// The full email address for the account. If this string isn't present in the payload, the device
	// prompts the user for this string during interactive profile installation in Settings or System
	// Preferences.
	EmailAddress *string `plist:"EmailAddress,omitempty" json:"EmailAddress,omitempty"`
	// The authentication scheme for incoming mail.
	IncomingMailServerAuthentication MailManagedIncomingMailServerAuthentication `plist:"IncomingMailServerAuthentication" json:"IncomingMailServerAuthentication"`
	// The incoming mail server host name.
	IncomingMailServerHostName string `plist:"IncomingMailServerHostName" json:"IncomingMailServerHostName"`
	// The incoming mail server port number. If not set, the system uses the default port for a given
	// protocol.
	IncomingMailServerPortNumber *int64 `plist:"IncomingMailServerPortNumber,omitempty" json:"IncomingMailServerPortNumber,omitempty"`
	// If `true`, the system enables SSL for authentication on the incoming mail server.
	//
	// Default: false.
	IncomingMailServerUseSSL *bool `plist:"IncomingMailServerUseSSL,omitempty" json:"IncomingMailServerUseSSL,omitempty"`
	// The user name for the email account, usually the same as the email address up to the "@"
	// character. If not set and the account requires authentication for incoming email, the device
	// prompts the user for this string during interactive profile installation in Settings or System
	// Preferences.
	IncomingMailServerUsername *string `plist:"IncomingMailServerUsername,omitempty" json:"IncomingMailServerUsername,omitempty"`
	// The password for the incoming mail server. Only use this in encrypted profiles.
	IncomingPassword *string `plist:"IncomingPassword,omitempty" json:"IncomingPassword,omitempty"`
	// The password for the outgoing mail server. Only use this in encrypted profiles.
	OutgoingPassword *string `plist:"OutgoingPassword,omitempty" json:"OutgoingPassword,omitempty"`
	// If `true`, the system prompts the user only once for the password, which it uses for both
	// outgoing and incoming mail.
	//
	// Default: false.
	OutgoingPasswordSameAsIncomingPassword *bool `plist:"OutgoingPasswordSameAsIncomingPassword,omitempty" json:"OutgoingPasswordSameAsIncomingPassword,omitempty"`
	// The authentication scheme for outgoing mail.
	OutgoingMailServerAuthentication MailManagedOutgoingMailServerAuthentication `plist:"OutgoingMailServerAuthentication" json:"OutgoingMailServerAuthentication"`
	// The outgoing mail server host name.
	OutgoingMailServerHostName string `plist:"OutgoingMailServerHostName" json:"OutgoingMailServerHostName"`
	// The outgoing mail server port number. If not set, the system uses ports 25, 587, and 465, in
	// that order.
	OutgoingMailServerPortNumber *int64 `plist:"OutgoingMailServerPortNumber,omitempty" json:"OutgoingMailServerPortNumber,omitempty"`
	// If `true`, the system enables SSL authentication on the outgoing mail server.
	//
	// Default: false.
	OutgoingMailServerUseSSL *bool `plist:"OutgoingMailServerUseSSL,omitempty" json:"OutgoingMailServerUseSSL,omitempty"`
	// The user name for the email account, usually the same as the email address up to the "@"
	// character. If not set and the account requires authentication for outgoing email, the device
	// prompts the user for this string during interactive profile installation in Settings or System
	// Preferences.
	OutgoingMailServerUsername *string `plist:"OutgoingMailServerUsername,omitempty" json:"OutgoingMailServerUsername,omitempty"`
	// If `true`, the system prevents moving messages out of this email account and into another
	// account. It also prevents forwarding or replying from an account other than the recipient of the
	// message.
	//
	// Default: false.
	PreventMove *bool `plist:"PreventMove,omitempty" json:"PreventMove,omitempty"`
	// If `true`, the system prevents this account from sending mail in any app other than the Apple
	// Mail app.
	//
	// Default: false.
	PreventAppSheet *bool `plist:"PreventAppSheet,omitempty" json:"PreventAppSheet,omitempty"`
	// If `true`, the system enables S/MIME encryption. The system ignores this key in iOS 10.0 and
	// later.
	//
	// Default: false.
	SMIMEEnabled *bool `plist:"SMIMEEnabled,omitempty" json:"SMIMEEnabled,omitempty"`
	// If `true`, the system enables S/MIME signing for this account.
	//
	// Default: false.
	SMIMESigningEnabled *bool `plist:"SMIMESigningEnabled,omitempty" json:"SMIMESigningEnabled,omitempty"`
	// The payload UUID of the identity certificate used to sign messages sent from this account.
	SMIMESigningCertificateUUID *string `plist:"SMIMESigningCertificateUUID,omitempty" json:"SMIMESigningCertificateUUID,omitempty"`
	// If `true`, the system enables S/MIME encryption for this account.
	//
	// Default: false.
	SMIMEEncryptionEnabled *bool `plist:"SMIMEEncryptionEnabled,omitempty" json:"SMIMEEncryptionEnabled,omitempty"`
	// The UUID of the identity certificate used to decrypt messages sent to this account. The system
	// attaches the public certificate to outgoing mail to allow the user to receive encrypted mail.
	// When the user sends encrypted mail, the system uses the public certificate to encrypt the copy
	// of the mail in their Sent mailbox.
	SMIMEEncryptionCertificateUUID *string `plist:"SMIMEEncryptionCertificateUUID,omitempty" json:"SMIMEEncryptionCertificateUUID,omitempty"`
	// If `true`, the system displays the per-message encryption switch in the Mail Compose UI.
	// Deprecated in iOS 12.0. Use `SMIMEEnableEncryptionPerMessageSwitch` instead.
	//
	// Default: false.
	SMIMEEnablePerMessageSwitch *bool `plist:"SMIMEEnablePerMessageSwitch,omitempty" json:"SMIMEEnablePerMessageSwitch,omitempty"`
	// If `true`, the system excludes this account from Recent Addresses syncing.
	//
	// Default: false.
	DisableMailRecentsSyncing *bool `plist:"disableMailRecentsSyncing,omitempty" json:"disableMailRecentsSyncing,omitempty"`
	// If `true`, the system enables this account to use Mail Drop.
	//
	// Default: false.
	AllowMailDrop *bool `plist:"allowMailDrop,omitempty" json:"allowMailDrop,omitempty"`
	// The path prefix for the IMAP mail server.
	IncomingMailServerIMAPPathPrefix *string `plist:"IncomingMailServerIMAPPathPrefix,omitempty" json:"IncomingMailServerIMAPPathPrefix,omitempty"`
	// If `true`, the user can turn S/MIME signing on or off in Settings.
	//
	// Default: false.
	SMIMESigningUserOverrideable *bool `plist:"SMIMESigningUserOverrideable,omitempty" json:"SMIMESigningUserOverrideable,omitempty"`
	// If `true`, the user can select the signing identity.
	//
	// Default: false.
	SMIMESigningCertificateUUIDUserOverrideable *bool `plist:"SMIMESigningCertificateUUIDUserOverrideable,omitempty" json:"SMIMESigningCertificateUUIDUserOverrideable,omitempty"`
	// If `true`, the system enables S/MIME encryption by default.
	//
	// Default: false.
	SMIMEEncryptByDefault *bool `plist:"SMIMEEncryptByDefault,omitempty" json:"SMIMEEncryptByDefault,omitempty"`
	// If `true`, the user can turn encryption by default on/off, and encryption is on.
	//
	// Default: false.
	SMIMEEncryptByDefaultUserOverrideable *bool `plist:"SMIMEEncryptByDefaultUserOverrideable,omitempty" json:"SMIMEEncryptByDefaultUserOverrideable,omitempty"`
	// If `true`, the user can select the S/MIME encryption identity, and encryption is on.
	//
	// Default: false.
	SMIMEEncryptionCertificateUUIDUserOverrideable *bool `plist:"SMIMEEncryptionCertificateUUIDUserOverrideable,omitempty" json:"SMIMEEncryptionCertificateUUIDUserOverrideable,omitempty"`
	// If `true`, the system displays the per-message encryption switch in the Mail Compose UI.
	//
	// Default: false.
	SMIMEEnableEncryptionPerMessageSwitch *bool `plist:"SMIMEEnableEncryptionPerMessageSwitch,omitempty" json:"SMIMEEnableEncryptionPerMessageSwitch,omitempty"`
	// The VPNUUID of the per-app VPN the account uses for network communication. Available in iOS 14
	// and later.
	VPNUUID *string `plist:"VPNUUID,omitempty" json:"VPNUUID,omitempty"`
}
