// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// ManagedClientPreferences — Managed Preferences.
// The payload that configures managed preferences.
//
// Supported: macOS 10.7+.
type ManagedClientPreferences struct {
	// The dictionary containing app preference domains. The key names are application preference
	// domain identifiers (for example, `com.example.my-app`), or the string `.GlobalPreferences` for
	// the global domain. The values are the corresponding forced and set-once preferences.
	PayloadContent ManagedClientPreferencesPayloadContent `plist:"PayloadContent" json:"PayloadContent"`
}

// PreferenceDomainSettingsMcxPreferenceSettings is the mcx_preference_settings dictionary.
// The dictionary of settings.
type PreferenceDomainSettingsMcxPreferenceSettings struct {
	// The setting/value pairs.
	ANY any `plist:"ANY,omitempty" json:"ANY,omitempty"`
}

// PreferenceDomainSettings is the Settings dictionary.
type PreferenceDomainSettings struct {
	// The dictionary of settings.
	McxPreferenceSettings PreferenceDomainSettingsMcxPreferenceSettings `plist:"mcx_preference_settings" json:"mcx_preference_settings"`
}

// PreferenceDomain is the ANY dictionary.
// The dictionary containing app preference domains.
type PreferenceDomain struct {
	// The dictionary of forced settings.
	Forced []PreferenceDomainSettings `plist:"Forced,omitempty" json:"Forced,omitempty"`
	// The dictionary of one-time settings.
	SetOnce []PreferenceDomainSettings `plist:"Set-Once,omitempty" json:"Set-Once,omitempty"`
}

// ManagedClientPreferencesPayloadContent is the PayloadContent dictionary.
// The dictionary containing app preference domains. The key names are application preference
// domain identifiers (for example, `com.example.my-app`), or the string `.GlobalPreferences` for
// the global domain. The values are the corresponding forced and set-once preferences.
type ManagedClientPreferencesPayloadContent struct {
	// The dictionary containing app preference domains.
	ANY PreferenceDomain `plist:"ANY" json:"ANY"`
}
