// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for MCX3.
func (MCX3) PayloadType() string { return "com.apple.MCX" }

// Validate checks the payload against Apple's spec. MCX3 has no
// constraints beyond its field types.
func (p *MCX3) Validate() error { return nil }
