// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// MCX — FDE FileVault Options.
// The payload that configures FileVault options.
//
// Supported: macOS 10.7+.
type MCX3 struct {
	// If `true`, the system won't disable FileVault.
	//
	// Default: false.
	DontAllowFDEDisable *bool `plist:"dontAllowFDEDisable,omitempty" json:"dontAllowFDEDisable,omitempty"`
	// If `true`, the system won't enable FileVault.
	//
	// Default: false.
	DontAllowFDEEnable *bool `plist:"dontAllowFDEEnable,omitempty" json:"dontAllowFDEEnable,omitempty"`
	// If `true`, the system won't store th FileVault key across restarts.
	//
	// Default: false.
	DestroyFVKeyOnStandby *bool `plist:"DestroyFVKeyOnStandby,omitempty" json:"DestroyFVKeyOnStandby,omitempty"`
}
