// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/ptr"
	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for FileVault2.
func (FileVault2) PayloadType() string { return "com.apple.MCX.FileVault2" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *FileVault2) Validate() error {
	var errs []error
	if err := validate.InList("Enable", p.Enable, []FileVault2Enable{FileVault2EnableOn, FileVault2EnableOff}); err != nil {
		errs = append(errs, err)
	}
	if p.DeferForceAtUserLoginMaxBypassAttempts != nil {
		if err := validate.IntRange("DeferForceAtUserLoginMaxBypassAttempts", *p.DeferForceAtUserLoginMaxBypassAttempts, ptr.To(int64(-1)), ptr.To(int64(9999))); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
