// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// Mcxloginscripts — Login Window: Scripts.
// The payload that configures scripts to run at login and logout.
//
// Supported: macOS 10.7+.
type Mcxloginscripts struct {
	// An array of one or more dictionaries of scripts to run at user login time.
	Loginscripts []McxloginscriptsScriptsItems `plist:"loginscripts,omitempty" json:"loginscripts,omitempty"`
	// An array of one or more dictionaries of scripts to run at user logout time.
	Logoutscripts []McxloginscriptsScriptsItems `plist:"logoutscripts,omitempty" json:"logoutscripts,omitempty"`
	// If `true`, the system doesn't execute the login scripts during login.
	//
	// Default: false.
	SkipLoginHook *bool `plist:"skipLoginHook,omitempty" json:"skipLoginHook,omitempty"`
	// If `true`, the system doesn't execute the logout scripts during logout.
	//
	// Default: false.
	SkipLogoutHook *bool `plist:"skipLogoutHook,omitempty" json:"skipLogoutHook,omitempty"`
}

// McxloginscriptsScriptsItems is the ScriptsItems dictionary.
// A dictionary of login scripts.
type McxloginscriptsScriptsItems struct {
	// The filename for display purposes.
	Filename string `plist:"filename" json:"filename"`
	// The UTF-8 encoded data object representing the executable script.
	Filedata []byte `plist:"filedata" json:"filedata"`
}
