// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for Mcxprinting.
func (Mcxprinting) PayloadType() string { return "com.apple.mcxprinting" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *Mcxprinting) Validate() error {
	var errs []error
	if p.DefaultPrinter != nil {
		if err := p.DefaultPrinter.Validate(); err != nil {
			errs = append(errs, validate.Nested("DefaultPrinter", err))
		}
	}
	if p.UserPrinterList != nil {
		if err := p.UserPrinterList.Validate(); err != nil {
			errs = append(errs, validate.Nested("UserPrinterList", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. McxprintingDefaultPrinter has no
// constraints beyond its field types.
func (p *McxprintingDefaultPrinter) Validate() error { return nil }

// Validate checks the payload against Apple's spec. McxprintingUserPrinterListPrinter has no
// constraints beyond its field types.
func (p *McxprintingUserPrinterListPrinter) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *McxprintingUserPrinterList) Validate() error {
	var errs []error
	if p.Printer != nil {
		if err := p.Printer.Validate(); err != nil {
			errs = append(errs, validate.Nested("Printer", err))
		}
	}
	return errors.Join(errs...)
}
