// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for MCX6.
func (MCX6) PayloadType() string { return "com.apple.MCX" }

// Validate checks the payload against Apple's spec. MCX6 has no
// constraints beyond its field types.
func (p *MCX6) Validate() error { return nil }
