// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// MdmEnrollmentMode — allowed values for Mdm.EnrollmentMode.
type MdmEnrollmentMode string

// MdmEnrollmentMode allowed values.
const (
	MdmEnrollmentModeBYOD MdmEnrollmentMode = "BYOD"
	MdmEnrollmentModeADDE MdmEnrollmentMode = "ADDE"
)

// String returns the MdmEnrollmentMode value as a plain string.
func (e MdmEnrollmentMode) String() string { return string(e) }
