// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for Mdm.
func (Mdm) PayloadType() string { return "com.apple.mdm" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *Mdm) Validate() error {
	var errs []error
	if err := validate.Format("IdentityCertificateUUID", p.IdentityCertificateUUID, "^[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{12}$"); err != nil {
		errs = append(errs, err)
	}
	if err := validate.Format("ServerURL", p.ServerURL, "^https://.*$"); err != nil {
		errs = append(errs, err)
	}
	if p.CheckInURL != nil {
		if err := validate.Format("CheckInURL", *p.CheckInURL, "^https://.*$"); err != nil {
			errs = append(errs, err)
		}
	}
	if p.EnrollmentMode != nil {
		if err := validate.InList("EnrollmentMode", *p.EnrollmentMode, []MdmEnrollmentMode{MdmEnrollmentModeBYOD, MdmEnrollmentModeADDE}); err != nil {
			errs = append(errs, err)
		}
	}
	for i := range p.ServerCapabilities {
		if err := validate.InList("ServerCapabilities", p.ServerCapabilities[i], []string{"com.apple.mdm.per-user-connections", "com.apple.mdm.bootstraptoken", "com.apple.mdm.token"}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
