// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// MobiledevicePasswordpolicy — Passcode.
// The payload that configures a passcode policy.
//
// Supported: iOS 4.0+, macOS 10.7+, visionOS 2.0+, watchOS 10.0+.
type MobiledevicePasswordpolicy struct {
	// If `false`, the system prevents use of a simple passcode. A simple passcode contains repeated
	// characters, or increasing or decreasing characters, such as `123` or `CBA`.
	//
	// Default: true.
	AllowSimple *bool `plist:"allowSimple,omitempty" json:"allowSimple,omitempty"`
	// If `true`, the system forces the user to enter a PIN.
	//
	// Default: false.
	ForcePIN *bool `plist:"forcePIN,omitempty" json:"forcePIN,omitempty"`
	// The number of failed passcode attempts that the system allows the user before it erases or locks
	// the device. After six failed attempts, the device imposes a time delay before the user can enter
	// a passcode again. The time delay increases with each failed attempt. On macOS, set
	// `minutesUntilFailedLoginReset` to define the time delay. The time delay begins after the sixth
	// attempt, so if `MaximumFailedAttempts` is six or lower, the system has no time delay and
	// triggers the erase or lock as soon as the user exceeds the limit.
	//
	// Default: 11.
	MaxFailedAttempts *int64 `plist:"maxFailedAttempts,omitempty" json:"maxFailedAttempts,omitempty"`
	// The maximum number of minutes for which the device can be idle without the user unlocking it,
	// before the system locks it. When this limit is reached, the system locks the device and the
	// passcode is required to unlock it. The user can edit this setting, but the value can't exceed
	// the `maxInactivity` value.
	MaxInactivity *int64 `plist:"maxInactivity,omitempty" json:"maxInactivity,omitempty"`
	// The number of days for which the passcode can remain unchanged. After this number of days, the
	// system forces the user to change the passcode before it unlocks the device.
	MaxPINAgeInDays *int64 `plist:"maxPINAgeInDays,omitempty" json:"maxPINAgeInDays,omitempty"`
	// The minimum number of complex characters that a passcode needs to contain. A _complex_ character
	// is a character other than a number or a letter, such as `&`, `%`, `$`, and `#`.
	//
	// Default: 0.
	MinComplexChars *int64 `plist:"minComplexChars,omitempty" json:"minComplexChars,omitempty"`
	// The minimum overall length of the passcode. This value is independent of the value for
	// `minComplexChars`.
	//
	// Default: 0.
	MinLength *int64 `plist:"minLength,omitempty" json:"minLength,omitempty"`
	// If `true`, the system requires alphabetic characters instead of only numeric characters.
	//
	// Default: false.
	RequireAlphanumeric *bool `plist:"requireAlphanumeric,omitempty" json:"requireAlphanumeric,omitempty"`
	// This value defines _N_, where the new passcode must be unique within the last _N_ entries in the
	// passcode history.
	PinHistory *int64 `plist:"pinHistory,omitempty" json:"pinHistory,omitempty"`
	// The maximum grace period, in minutes, to unlock the phone without entering a passcode. The
	// default is `0`, which is no grace period and requires a passcode immediately. On macOS, the
	// system translates this grace period value to screen-saver settings.
	//
	// Default: 0.
	MaxGracePeriod *int64 `plist:"maxGracePeriod,omitempty" json:"maxGracePeriod,omitempty"`
	// The number of minutes before the system resets the login after the maximum number of
	// unsuccessful login attempts is reached. This key requires setting `maxFailedAttempts`. Available
	// in macOS 10.10 and later.
	MinutesUntilFailedLoginReset *int64 `plist:"minutesUntilFailedLoginReset,omitempty" json:"minutesUntilFailedLoginReset,omitempty"`
	// If `true`, the system causes a password reset to occur the next time the user tries to
	// authenticate. If this key is set in a device profile, the setting takes effect for all users,
	// and admin authentications may fail until the admin user password is also reset. Available in
	// macOS 10.13 and later.
	//
	// Default: false.
	ChangeAtNextAuth *bool `plist:"changeAtNextAuth,omitempty" json:"changeAtNextAuth,omitempty"`
	// Specifies a regular expression, and its description, used to enforce password compliance. Use
	// the simpler passcode restrictions whenever possible, and rely on regular expression matching
	// only when necessary. Mistakes in regular expressions can lead to frustrating user experiences,
	// such as unsatisfiable passcode policies, or policy descriptions that don't match the enforced
	// policy.
	CustomRegex *MobiledevicePasswordpolicyCustomRegex `plist:"customRegex,omitempty" json:"customRegex,omitempty"`
}

// MobiledevicePasswordpolicyCustomRegexPasswordContentDescription is the passwordContentDescription dictionary.
// Contains a dictionary of keys for supported OS language IDs (for example, "en-US"), and whose
// values represent a localized description of the policy enforced by the regular expression. Use
// the special `default` key can for languages that aren't contained in the dictionary.
type MobiledevicePasswordpolicyCustomRegexPasswordContentDescription struct {
	// A localized description.
	ANY *string `plist:"ANY,omitempty" json:"ANY,omitempty"`
}

// MobiledevicePasswordpolicyCustomRegex is the customRegex dictionary.
// Specifies a regular expression, and its description, used to enforce password compliance. Use
// the simpler passcode restrictions whenever possible, and rely on regular expression matching
// only when necessary. Mistakes in regular expressions can lead to frustrating user experiences,
// such as unsatisfiable passcode policies, or policy descriptions that don't match the enforced
// policy.
type MobiledevicePasswordpolicyCustomRegex struct {
	// A regular expression string that the system matches against the password to determine whether it
	// complies with a policy. The regular expression uses the ICU syntax
	// ([https://unicode-org.github.io/icu/userguide/strings/regexp.html](https://unicode-org.github.io/icu/userguide/strings/regexp.html)).
	// The string must not exceed 2048 characters in length.
	PasswordContentRegex string `plist:"passwordContentRegex" json:"passwordContentRegex"`
	// Contains a dictionary of keys for supported OS language IDs (for example, "en-US"), and whose
	// values represent a localized description of the policy enforced by the regular expression. Use
	// the special `default` key can for languages that aren't contained in the dictionary.
	PasswordContentDescription *MobiledevicePasswordpolicyCustomRegexPasswordContentDescription `plist:"passwordContentDescription,omitempty" json:"passwordContentDescription,omitempty"`
}
