// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"fmt"
)

// NetworkusagerulesSIMRulesItemWiFiAssistPolicy — allowed values for NetworkusagerulesSIMRulesItem.WiFiAssistPolicy.
type NetworkusagerulesSIMRulesItemWiFiAssistPolicy int64

// NetworkusagerulesSIMRulesItemWiFiAssistPolicy allowed values.
const (
	NetworkusagerulesSIMRulesItemWiFiAssistPolicyValue2 NetworkusagerulesSIMRulesItemWiFiAssistPolicy = 2
	NetworkusagerulesSIMRulesItemWiFiAssistPolicyValue3 NetworkusagerulesSIMRulesItemWiFiAssistPolicy = 3
)

// String returns the NetworkusagerulesSIMRulesItemWiFiAssistPolicy constant's name, or its numeric form
// when the value is not a known constant.
func (e NetworkusagerulesSIMRulesItemWiFiAssistPolicy) String() string {
	switch e {
	case NetworkusagerulesSIMRulesItemWiFiAssistPolicyValue2:
		return "NetworkusagerulesSIMRulesItemWiFiAssistPolicyValue2"
	case NetworkusagerulesSIMRulesItemWiFiAssistPolicyValue3:
		return "NetworkusagerulesSIMRulesItemWiFiAssistPolicyValue3"
	default:
		return fmt.Sprintf("NetworkusagerulesSIMRulesItemWiFiAssistPolicy(%d)", int64(e))
	}
}
