// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for Networkusagerules.
func (Networkusagerules) PayloadType() string { return "com.apple.networkusagerules" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *Networkusagerules) Validate() error {
	var errs []error
	for i := range p.ApplicationRules {
		if err := p.ApplicationRules[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ApplicationRules", i, err))
		}
	}
	for i := range p.SIMRules {
		if err := p.SIMRules[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SIMRules", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. NetworkusagerulesApplicationRulesItem has no
// constraints beyond its field types.
func (p *NetworkusagerulesApplicationRulesItem) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkusagerulesSIMRulesItem) Validate() error {
	var errs []error
	if p.ICCIDs == nil {
		errs = append(errs, validate.Required("ICCIDs"))
	}
	if err := validate.InList("WiFiAssistPolicy", p.WiFiAssistPolicy, []NetworkusagerulesSIMRulesItemWiFiAssistPolicy{NetworkusagerulesSIMRulesItemWiFiAssistPolicyValue2, NetworkusagerulesSIMRulesItemWiFiAssistPolicyValue3}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}
