// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"fmt"
)

// NotificationsettingsNotificationSettingsItemAlertType — allowed values for NotificationsettingsNotificationSettingsItem.AlertType.
type NotificationsettingsNotificationSettingsItemAlertType int64

// NotificationsettingsNotificationSettingsItemAlertType allowed values.
const (
	NotificationsettingsNotificationSettingsItemAlertTypeValue0 NotificationsettingsNotificationSettingsItemAlertType = 0
	NotificationsettingsNotificationSettingsItemAlertTypeValue1 NotificationsettingsNotificationSettingsItemAlertType = 1
	NotificationsettingsNotificationSettingsItemAlertTypeValue2 NotificationsettingsNotificationSettingsItemAlertType = 2
)

// String returns the NotificationsettingsNotificationSettingsItemAlertType constant's name, or its numeric form
// when the value is not a known constant.
func (e NotificationsettingsNotificationSettingsItemAlertType) String() string {
	switch e {
	case NotificationsettingsNotificationSettingsItemAlertTypeValue0:
		return "NotificationsettingsNotificationSettingsItemAlertTypeValue0"
	case NotificationsettingsNotificationSettingsItemAlertTypeValue1:
		return "NotificationsettingsNotificationSettingsItemAlertTypeValue1"
	case NotificationsettingsNotificationSettingsItemAlertTypeValue2:
		return "NotificationsettingsNotificationSettingsItemAlertTypeValue2"
	default:
		return fmt.Sprintf("NotificationsettingsNotificationSettingsItemAlertType(%d)", int64(e))
	}
}

// NotificationsettingsNotificationSettingsItemGroupingType — allowed values for NotificationsettingsNotificationSettingsItem.GroupingType.
type NotificationsettingsNotificationSettingsItemGroupingType int64

// NotificationsettingsNotificationSettingsItemGroupingType allowed values.
const (
	NotificationsettingsNotificationSettingsItemGroupingTypeValue0 NotificationsettingsNotificationSettingsItemGroupingType = 0
	NotificationsettingsNotificationSettingsItemGroupingTypeValue1 NotificationsettingsNotificationSettingsItemGroupingType = 1
	NotificationsettingsNotificationSettingsItemGroupingTypeValue2 NotificationsettingsNotificationSettingsItemGroupingType = 2
)

// String returns the NotificationsettingsNotificationSettingsItemGroupingType constant's name, or its numeric form
// when the value is not a known constant.
func (e NotificationsettingsNotificationSettingsItemGroupingType) String() string {
	switch e {
	case NotificationsettingsNotificationSettingsItemGroupingTypeValue0:
		return "NotificationsettingsNotificationSettingsItemGroupingTypeValue0"
	case NotificationsettingsNotificationSettingsItemGroupingTypeValue1:
		return "NotificationsettingsNotificationSettingsItemGroupingTypeValue1"
	case NotificationsettingsNotificationSettingsItemGroupingTypeValue2:
		return "NotificationsettingsNotificationSettingsItemGroupingTypeValue2"
	default:
		return fmt.Sprintf("NotificationsettingsNotificationSettingsItemGroupingType(%d)", int64(e))
	}
}

// NotificationsettingsNotificationSettingsItemPreviewType — allowed values for NotificationsettingsNotificationSettingsItem.PreviewType.
type NotificationsettingsNotificationSettingsItemPreviewType int64

// NotificationsettingsNotificationSettingsItemPreviewType allowed values.
const (
	NotificationsettingsNotificationSettingsItemPreviewTypeValue0 NotificationsettingsNotificationSettingsItemPreviewType = 0
	NotificationsettingsNotificationSettingsItemPreviewTypeValue1 NotificationsettingsNotificationSettingsItemPreviewType = 1
	NotificationsettingsNotificationSettingsItemPreviewTypeValue2 NotificationsettingsNotificationSettingsItemPreviewType = 2
)

// String returns the NotificationsettingsNotificationSettingsItemPreviewType constant's name, or its numeric form
// when the value is not a known constant.
func (e NotificationsettingsNotificationSettingsItemPreviewType) String() string {
	switch e {
	case NotificationsettingsNotificationSettingsItemPreviewTypeValue0:
		return "NotificationsettingsNotificationSettingsItemPreviewTypeValue0"
	case NotificationsettingsNotificationSettingsItemPreviewTypeValue1:
		return "NotificationsettingsNotificationSettingsItemPreviewTypeValue1"
	case NotificationsettingsNotificationSettingsItemPreviewTypeValue2:
		return "NotificationsettingsNotificationSettingsItemPreviewTypeValue2"
	default:
		return fmt.Sprintf("NotificationsettingsNotificationSettingsItemPreviewType(%d)", int64(e))
	}
}
