// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PreferenceSecurity — Security Preferences.
// The payload that configures security preferences.
//
// Supported: macOS 10.10+.
type PreferenceSecurity struct {
	// If `true`, disables user changes to the password.
	//
	// Default: false.
	DontAllowPasswordResetUI *bool `plist:"dontAllowPasswordResetUI,omitempty" json:"dontAllowPasswordResetUI,omitempty"`
	// If `true`, disables user changes to the lock message.
	//
	// Default: false.
	DontAllowLockMessageUI *bool `plist:"dontAllowLockMessageUI,omitempty" json:"dontAllowLockMessageUI,omitempty"`
	// If `true`, disables user changes to the firewall settings.
	//
	// Default: false.
	DontAllowFireWallUI *bool `plist:"dontAllowFireWallUI,omitempty" json:"dontAllowFireWallUI,omitempty"`
}
