// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for ProfileRemovalPassword.
func (ProfileRemovalPassword) PayloadType() string { return "com.apple.profileRemovalPassword" }

// Validate checks the payload against Apple's spec. ProfileRemovalPassword has no
// constraints beyond its field types.
func (p *ProfileRemovalPassword) Validate() error { return nil }
