// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// ProfileRemovalPassword — Profile Removal Password.
// The payload that configures profile removal.
//
// Supported: iOS 4.0+, macOS 10.7+, tvOS 9.0+.
type ProfileRemovalPassword struct {
	// The password to allow removing the profile.
	RemovalPassword *string `plist:"RemovalPassword,omitempty" json:"RemovalPassword,omitempty"`
}
