// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for RelayManaged.
func (RelayManaged) PayloadType() string { return "com.apple.relay.managed" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *RelayManaged) Validate() error {
	var errs []error
	if p.Relays == nil {
		errs = append(errs, validate.Required("Relays"))
	}
	for i := range p.Relays {
		if err := p.Relays[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Relays", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. RelayManagedRelayAdditionalHTTPHeaderFields has no
// constraints beyond its field types.
func (p *RelayManagedRelayAdditionalHTTPHeaderFields) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *RelayManagedRelay) Validate() error {
	var errs []error
	if p.AdditionalHTTPHeaderFields != nil {
		if err := p.AdditionalHTTPHeaderFields.Validate(); err != nil {
			errs = append(errs, validate.Nested("AdditionalHTTPHeaderFields", err))
		}
	}
	if p.PayloadCertificateUUID != nil {
		if err := validate.Format("PayloadCertificateUUID", *p.PayloadCertificateUUID, "^[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{12}$"); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
