// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// SecondactiveethernetManaged — 802.1X: Second Active Ethernet.
// The payload that configures the second wired, active Ethernet interface.
//
// Supported: macOS 10.7+.
type SecondactiveethernetManaged struct {
	// Keys relevant to 802.1x configuration. User enrollment payloads do not support the various proxy
	// keys including ProxyType, ProxyServer, ProxyServerPort, ProxyUsername, ProxyPassword,,
	// ProxyPACURL and ProxyPACFallbackAllowed.
	ANY any `plist:"ANY,omitempty" json:"ANY,omitempty"`
}
