// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for SecondethernetManaged.
func (SecondethernetManaged) PayloadType() string { return "com.apple.secondethernet.managed" }

// Validate checks the payload against Apple's spec. SecondethernetManaged has no
// constraints beyond its field types.
func (p *SecondethernetManaged) Validate() error { return nil }
