// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// SecurityPem — Certificate (PEM).
// The payload that configures a PEM-formatted certificate.
//
// Supported: iOS 4.0+, macOS 10.7+, tvOS 9.0+, visionOS 1.0+, watchOS 3.0+.
type SecurityPem struct {
	// The file name of the enclosed certificate.
	PayloadCertificateFileName *string `plist:"PayloadCertificateFileName,omitempty" json:"PayloadCertificateFileName,omitempty"`
	// The binary representation of the payload, encoded in Base64.
	PayloadContent []byte `plist:"PayloadContent" json:"PayloadContent"`
}
