// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"fmt"
)

// SecuritySmartcardCheckCertificateTrust — allowed values for SecuritySmartcard.CheckCertificateTrust.
type SecuritySmartcardCheckCertificateTrust int64

// SecuritySmartcardCheckCertificateTrust allowed values.
const (
	SecuritySmartcardCheckCertificateTrustValue0 SecuritySmartcardCheckCertificateTrust = 0
	SecuritySmartcardCheckCertificateTrustValue1 SecuritySmartcardCheckCertificateTrust = 1
	SecuritySmartcardCheckCertificateTrustValue2 SecuritySmartcardCheckCertificateTrust = 2
	SecuritySmartcardCheckCertificateTrustValue3 SecuritySmartcardCheckCertificateTrust = 3
)

// String returns the SecuritySmartcardCheckCertificateTrust constant's name, or its numeric form
// when the value is not a known constant.
func (e SecuritySmartcardCheckCertificateTrust) String() string {
	switch e {
	case SecuritySmartcardCheckCertificateTrustValue0:
		return "SecuritySmartcardCheckCertificateTrustValue0"
	case SecuritySmartcardCheckCertificateTrustValue1:
		return "SecuritySmartcardCheckCertificateTrustValue1"
	case SecuritySmartcardCheckCertificateTrustValue2:
		return "SecuritySmartcardCheckCertificateTrustValue2"
	case SecuritySmartcardCheckCertificateTrustValue3:
		return "SecuritySmartcardCheckCertificateTrustValue3"
	default:
		return fmt.Sprintf("SecuritySmartcardCheckCertificateTrust(%d)", int64(e))
	}
}

// SecuritySmartcardTokenRemovalAction — allowed values for SecuritySmartcard.TokenRemovalAction.
type SecuritySmartcardTokenRemovalAction int64

// SecuritySmartcardTokenRemovalAction allowed values.
const (
	SecuritySmartcardTokenRemovalActionValue0 SecuritySmartcardTokenRemovalAction = 0
	SecuritySmartcardTokenRemovalActionValue1 SecuritySmartcardTokenRemovalAction = 1
)

// String returns the SecuritySmartcardTokenRemovalAction constant's name, or its numeric form
// when the value is not a known constant.
func (e SecuritySmartcardTokenRemovalAction) String() string {
	switch e {
	case SecuritySmartcardTokenRemovalActionValue0:
		return "SecuritySmartcardTokenRemovalActionValue0"
	case SecuritySmartcardTokenRemovalActionValue1:
		return "SecuritySmartcardTokenRemovalActionValue1"
	default:
		return fmt.Sprintf("SecuritySmartcardTokenRemovalAction(%d)", int64(e))
	}
}
