// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for SecurityAcme.
func (SecurityAcme) PayloadType() string { return "com.apple.security.acme" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *SecurityAcme) Validate() error {
	var errs []error
	if err := validate.InList("KeyType", p.KeyType, []SecurityAcmeKeyType{SecurityAcmeKeyTypeRSA, SecurityAcmeKeyTypeECSECPrimeRandom}); err != nil {
		errs = append(errs, err)
	}
	if p.Subject == nil {
		errs = append(errs, validate.Required("Subject"))
	}
	if p.SubjectAltName != nil {
		if err := p.SubjectAltName.Validate(); err != nil {
			errs = append(errs, validate.Nested("SubjectAltName", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. SecurityAcmeSubjectAltName has no
// constraints beyond its field types.
func (p *SecurityAcmeSubjectAltName) Validate() error { return nil }
