// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"fmt"
)

// SecurityScepPayloadContentKeysize — allowed values for SecurityScepPayloadContent.Keysize.
type SecurityScepPayloadContentKeysize int64

// SecurityScepPayloadContentKeysize allowed values.
const (
	SecurityScepPayloadContentKeysizeValue1024 SecurityScepPayloadContentKeysize = 1024
	SecurityScepPayloadContentKeysizeValue2048 SecurityScepPayloadContentKeysize = 2048
	SecurityScepPayloadContentKeysizeValue4096 SecurityScepPayloadContentKeysize = 4096
)

// String returns the SecurityScepPayloadContentKeysize constant's name, or its numeric form
// when the value is not a known constant.
func (e SecurityScepPayloadContentKeysize) String() string {
	switch e {
	case SecurityScepPayloadContentKeysizeValue1024:
		return "SecurityScepPayloadContentKeysizeValue1024"
	case SecurityScepPayloadContentKeysizeValue2048:
		return "SecurityScepPayloadContentKeysizeValue2048"
	case SecurityScepPayloadContentKeysizeValue4096:
		return "SecurityScepPayloadContentKeysizeValue4096"
	default:
		return fmt.Sprintf("SecurityScepPayloadContentKeysize(%d)", int64(e))
	}
}
