// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-sdk-appleservices/device_management/validate"
)

// PayloadType returns the wire type identifier for SecurityFirewall.
func (SecurityFirewall) PayloadType() string { return "com.apple.security.firewall" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *SecurityFirewall) Validate() error {
	var errs []error
	for i := range p.Applications {
		if err := p.Applications[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Applications", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. SecurityFirewallApplicationsItem has no
// constraints beyond its field types.
func (p *SecurityFirewallApplicationsItem) Validate() error { return nil }
