// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// SecurityCertificatepreference — Certificate Preference.
// The payload that configures a certificate preference.
//
// Supported: macOS 10.12+.
type SecurityCertificatepreference struct {
	// An email address (in RFC 822 format) or other name for which a preferred certificate is
	// requested.
	Name string `plist:"Name" json:"Name"`
	// The UUID of the certificate payload within the same profile to use for the identity credential.
	PayloadCertificateUUID string `plist:"PayloadCertificateUUID" json:"PayloadCertificateUUID"`
}
