// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// SecuritySmartcard — SmartCard.
// The payload that configures a smart card.
//
// Supported: macOS 10.12.4+.
type SecuritySmartcard struct {
	// If `false`, users don't get the pairing dialog, although existing pairings still work.
	//
	// Default: true.
	UserPairing *bool `plist:"UserPairing,omitempty" json:"UserPairing,omitempty"`
	// If `false`, the system disables smart cards for logins, authorizations, and screen saver
	// unlocking. It's still allowed for other functions, such as signing emails and accessing the web.
	// The device requires a restart for a setting change to take effect.
	//
	// Default: true.
	AllowSmartCard *bool `plist:"allowSmartCard,omitempty" json:"allowSmartCard,omitempty"`
	// Configures the certificate trust check and has one of the following possible values:
	//
	// Default: 0.
	CheckCertificateTrust *SecuritySmartcardCheckCertificateTrust `plist:"checkCertificateTrust,omitempty" json:"checkCertificateTrust,omitempty"`
	// If `true`, a user can pair with only one smart card, although existing pairings are allowed if
	// already set up.
	//
	// Default: false.
	OneCardPerUser *bool `plist:"oneCardPerUser,omitempty" json:"oneCardPerUser,omitempty"`
	// If `1`, the device enables the screen saver when the user removes the smart card.
	//
	// Default: 0.
	TokenRemovalAction *SecuritySmartcardTokenRemovalAction `plist:"tokenRemovalAction,omitempty" json:"tokenRemovalAction,omitempty"`
	// If `true`, a user can only log in or authenticate with a smart card.
	//
	// Default: false.
	EnforceSmartCard *bool `plist:"enforceSmartCard,omitempty" json:"enforceSmartCard,omitempty"`
}
