// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// SecurityFirewallLoggingOption — allowed values for SecurityFirewall.LoggingOption.
type SecurityFirewallLoggingOption string

// SecurityFirewallLoggingOption allowed values.
const (
	SecurityFirewallLoggingOptionThrottled SecurityFirewallLoggingOption = "throttled"
	SecurityFirewallLoggingOptionBrief     SecurityFirewallLoggingOption = "brief"
	SecurityFirewallLoggingOptionDetail    SecurityFirewallLoggingOption = "detail"
)

// String returns the SecurityFirewallLoggingOption value as a plain string.
func (e SecurityFirewallLoggingOption) String() string { return string(e) }
