// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// SecurityFirewall — Firewall.
// The payload that configures the firewall.
//
// Supported: macOS 10.12+.
type SecurityFirewall struct {
	// If `true`, the system enables the firewall.
	EnableFirewall bool `plist:"EnableFirewall" json:"EnableFirewall"`
	// If `true`, the system enables blocking all incoming connections.
	BlockAllIncoming *bool `plist:"BlockAllIncoming,omitempty" json:"BlockAllIncoming,omitempty"`
	// If `true`, the system enables stealth mode.
	EnableStealthMode *bool `plist:"EnableStealthMode,omitempty" json:"EnableStealthMode,omitempty"`
	// The list of apps with connections that the firewall controls.
	Applications []SecurityFirewallApplicationsItem `plist:"Applications,omitempty" json:"Applications,omitempty"`
	// If `true`, the system enables logging. Available in macOS 12 through macOS 14.6.
	EnableLogging *bool `plist:"EnableLogging,omitempty" json:"EnableLogging,omitempty"`
	// The type of logging. Available in macOS 12 and through macOS 14.6.
	LoggingOption *SecurityFirewallLoggingOption `plist:"LoggingOption,omitempty" json:"LoggingOption,omitempty"`
	// If `true`, the system allows built-in software to receive incoming connections. Available in
	// macOS 12.3 and later.
	//
	// Default: true.
	AllowSigned *bool `plist:"AllowSigned,omitempty" json:"AllowSigned,omitempty"`
	// If `true`, the system allows downloaded signed software to receive incoming connections.
	// Available in macOS 12.3 and later.
	//
	// Default: true.
	AllowSignedApp *bool `plist:"AllowSignedApp,omitempty" json:"AllowSignedApp,omitempty"`
}

// SecurityFirewallApplicationsItem is the ApplicationsItem dictionary.
type SecurityFirewallApplicationsItem struct {
	// The bundle identifier for the app.
	BundleID string `plist:"BundleID" json:"BundleID"`
	// If `true`, the system allows connections for the app.
	Allowed bool `plist:"Allowed" json:"Allowed"`
}
