// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// Servicemanagement — Service Management - Managed Login Items.
// This payload that configures managed login items, which auto-enables and auto-allows matched
// items.
//
// Supported: macOS 13.0+.
type Servicemanagement struct {
	// An array of service management rules.
	Rules []ServicemanagementRule `plist:"Rules" json:"Rules"`
}

// ServicemanagementRule is the Rule dictionary.
// A specification for matching one or more login items.
type ServicemanagementRule struct {
	// The type of comparison to make.
	RuleType ServicemanagementRuleRuleType `plist:"RuleType" json:"RuleType"`
	// The value to compare with each login item's value, to determine if this rule is a match.
	RuleValue string `plist:"RuleValue" json:"RuleValue"`
	// An optional description of the rule.
	Comment *string `plist:"Comment,omitempty" json:"Comment,omitempty"`
	// An additional constraint to limit the scope of the rule that the system tests after matching the
	// `RuleType` and `RuleValue`.
	TeamIdentifier *string `plist:"TeamIdentifier,omitempty" json:"TeamIdentifier,omitempty"`
}
