// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for SetupAssistantManaged.
func (SetupAssistantManaged) PayloadType() string { return "com.apple.SetupAssistant.managed" }

// Validate checks the payload against Apple's spec. SetupAssistantManaged has no
// constraints beyond its field types.
func (p *SetupAssistantManaged) Validate() error { return nil }
