// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// PayloadType returns the wire type identifier for Shareddeviceconfiguration.
func (Shareddeviceconfiguration) PayloadType() string { return "com.apple.shareddeviceconfiguration" }

// Validate checks the payload against Apple's spec. Shareddeviceconfiguration has no
// constraints beyond its field types.
func (p *Shareddeviceconfiguration) Validate() error { return nil }
