// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// SubscribedcalendarAccount — Subscribed Calendars.
// The payload that configures subscribed calendars.
//
// Supported: iOS 4.0+, visionOS 1.1+.
type SubscribedcalendarAccount struct {
	// The description of the account.
	SubCalAccountDescription *string `plist:"SubCalAccountDescription,omitempty" json:"SubCalAccountDescription,omitempty"`
	// The server's address.
	SubCalAccountHostName string `plist:"SubCalAccountHostName" json:"SubCalAccountHostName"`
	// The user's user name.
	SubCalAccountUsername *string `plist:"SubCalAccountUsername,omitempty" json:"SubCalAccountUsername,omitempty"`
	// The user's password.
	SubCalAccountPassword *string `plist:"SubCalAccountPassword,omitempty" json:"SubCalAccountPassword,omitempty"`
	// If `true`, the system enables SSL.
	//
	// Default: false.
	SubCalAccountUseSSL *bool `plist:"SubCalAccountUseSSL,omitempty" json:"SubCalAccountUseSSL,omitempty"`
	// The VPNUUID of the per-app VPN the account uses for network communication. Available in iOS 14
	// and later.
	VPNUUID *string `plist:"VPNUUID,omitempty" json:"VPNUUID,omitempty"`
}
