// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// SystempolicyRuleOperationType — allowed values for SystempolicyRule.OperationType.
type SystempolicyRuleOperationType string

// SystempolicyRuleOperationType allowed values.
const (
	SystempolicyRuleOperationTypeOperationExecute SystempolicyRuleOperationType = "operation:execute"
	SystempolicyRuleOperationTypeOperationInstall SystempolicyRuleOperationType = "operation:install"
	SystempolicyRuleOperationTypeOperationLsopen  SystempolicyRuleOperationType = "operation:lsopen"
)

// String returns the SystempolicyRuleOperationType value as a plain string.
func (e SystempolicyRuleOperationType) String() string { return string(e) }
