// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for Systemmigration.
func (Systemmigration) PayloadType() string { return "com.apple.systemmigration" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *Systemmigration) Validate() error {
	var errs []error
	for i := range p.CustomBehavior {
		if err := p.CustomBehavior[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("CustomBehavior", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. SystemmigrationCustomBehaviorItemPathsItem has no
// constraints beyond its field types.
func (p *SystemmigrationCustomBehaviorItemPathsItem) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *SystemmigrationCustomBehaviorItem) Validate() error {
	var errs []error
	if p.Paths == nil {
		errs = append(errs, validate.Required("Paths"))
	}
	for i := range p.Paths {
		if err := p.Paths[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Paths", i, err))
		}
	}
	return errors.Join(errs...)
}
