// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for SystempolicyRule.
func (SystempolicyRule) PayloadType() string { return "com.apple.systempolicy.rule" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *SystempolicyRule) Validate() error {
	var errs []error
	if p.OperationType != nil {
		if err := validate.InList("OperationType", *p.OperationType, []SystempolicyRuleOperationType{SystempolicyRuleOperationTypeOperationExecute, SystempolicyRuleOperationTypeOperationInstall, SystempolicyRuleOperationTypeOperationLsopen}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
