// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// SystemLogging — System Logging.
// The payload that configures system logging.
//
// Supported: macOS 10.12+.
type SystemLogging struct {
	// Not to be used.
	Processes *Item `plist:"Processes,omitempty" json:"Processes,omitempty"`
	// A dictionary enabling the logging level for subsystems. See `Customizing Logging Behavior While
	// Debugging` for more details about the format of the dictionary.
	Subsystems *Item `plist:"Subsystems,omitempty" json:"Subsystems,omitempty"`
	// This dictionary has one key, `Enable-Private-Data`. Setting that value to `true` enables private
	// data logging for the entire system.
	System *Item `plist:"System,omitempty" json:"System,omitempty"`
}

// Item is the Processes dictionary.
// Not to be used.
type Item struct {
	// TBD
	ANY any `plist:"ANY,omitempty" json:"ANY,omitempty"`
}
