// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for SystemConfiguration.
func (SystemConfiguration) PayloadType() string { return "com.apple.SystemConfiguration" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *SystemConfiguration) Validate() error {
	var errs []error
	if err := p.Proxies.Validate(); err != nil {
		errs = append(errs, validate.Nested("Proxies", err))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. SystemConfigurationProxies has no
// constraints beyond its field types.
func (p *SystemConfigurationProxies) Validate() error { return nil }
