// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for SystemExtensionPolicy.
func (SystemExtensionPolicy) PayloadType() string { return "com.apple.system-extension-policy" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *SystemExtensionPolicy) Validate() error {
	var errs []error
	if p.AllowedSystemExtensionTypes != nil {
		if err := p.AllowedSystemExtensionTypes.Validate(); err != nil {
			errs = append(errs, validate.Nested("AllowedSystemExtensionTypes", err))
		}
	}
	if p.AllowedSystemExtensions != nil {
		if err := p.AllowedSystemExtensions.Validate(); err != nil {
			errs = append(errs, validate.Nested("AllowedSystemExtensions", err))
		}
	}
	if p.RemovableSystemExtensions != nil {
		if err := p.RemovableSystemExtensions.Validate(); err != nil {
			errs = append(errs, validate.Nested("RemovableSystemExtensions", err))
		}
	}
	if p.NonRemovableSystemExtensions != nil {
		if err := p.NonRemovableSystemExtensions.Validate(); err != nil {
			errs = append(errs, validate.Nested("NonRemovableSystemExtensions", err))
		}
	}
	if p.NonRemovableFromUISystemExtensions != nil {
		if err := p.NonRemovableFromUISystemExtensions.Validate(); err != nil {
			errs = append(errs, validate.Nested("NonRemovableFromUISystemExtensions", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. SystemExtensionPolicyAllowedSystemExtensionTypes has no
// constraints beyond its field types.
func (p *SystemExtensionPolicyAllowedSystemExtensionTypes) Validate() error { return nil }

// Validate checks the payload against Apple's spec. SystemExtensionPolicyAllowedSystemExtensions has no
// constraints beyond its field types.
func (p *SystemExtensionPolicyAllowedSystemExtensions) Validate() error { return nil }

// Validate checks the payload against Apple's spec. SystemExtensionPolicyRemovableSystemExtensions has no
// constraints beyond its field types.
func (p *SystemExtensionPolicyRemovableSystemExtensions) Validate() error { return nil }

// Validate checks the payload against Apple's spec. SystemExtensionPolicyNonRemovableSystemExtensions has no
// constraints beyond its field types.
func (p *SystemExtensionPolicyNonRemovableSystemExtensions) Validate() error { return nil }

// Validate checks the payload against Apple's spec. SystemExtensionPolicyNonRemovableFromUISystemExtensions has no
// constraints beyond its field types.
func (p *SystemExtensionPolicyNonRemovableFromUISystemExtensions) Validate() error { return nil }
