// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// Systemmigration — System Migration.
// The payload that configures system migration.
//
// Supported: macOS 10.12.4+.
type Systemmigration struct {
	// The list of custom behavior dictionaries.
	CustomBehavior []SystemmigrationCustomBehaviorItem `plist:"CustomBehavior,omitempty" json:"CustomBehavior,omitempty"`
}

// SystemmigrationCustomBehaviorItemPathsItem is the PathsItem dictionary.
// The custom behavior path dictionary.
type SystemmigrationCustomBehaviorItemPathsItem struct {
	// The path to the migrating file or directory on the source system.
	SourcePath string `plist:"SourcePath" json:"SourcePath"`
	// If `true`, the source path is located within a user home directory.
	SourcePathInUserHome bool `plist:"SourcePathInUserHome" json:"SourcePathInUserHome"`
	// The path to the destination file or directory on the target system.
	TargetPath string `plist:"TargetPath" json:"TargetPath"`
	// If `true`, the target path is located within a user home directory.
	TargetPathInUserHome bool `plist:"TargetPathInUserHome" json:"TargetPathInUserHome"`
}

// SystemmigrationCustomBehaviorItem is the CustomBehaviorItem dictionary.
// The custom behavior dictionary.
type SystemmigrationCustomBehaviorItem struct {
	// The context that custom paths apply to.
	Context string `plist:"Context" json:"Context"`
	// The list of custom behavior path dictionaries.
	Paths []SystemmigrationCustomBehaviorItemPathsItem `plist:"Paths" json:"Paths"`
}
