// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// SystemExtensionPolicy — System Extensions.
// The payload that configures system extensions.
//
// Supported: macOS 10.15+.
type SystemExtensionPolicy struct {
	// If `false`, restricts users from approving additional system extensions that configuration
	// profiles don't explicitly allow.
	//
	// Default: true.
	AllowUserOverrides *bool `plist:"AllowUserOverrides,omitempty" json:"AllowUserOverrides,omitempty"`
	// An array of team identifiers that defines valid, signed system extensions that are allowable to
	// load. Approved system extensions are those signed with any of the specified team identifiers.
	AllowedTeamIdentifiers []string `plist:"AllowedTeamIdentifiers,omitempty" json:"AllowedTeamIdentifiers,omitempty"`
	// A dictionary that maps a team identifier to an array of strings, where each string is a type of
	// system extension that you can install for that team identifier. The allowed extension types are
	// `DriverExtension`, `NetworkExtension`, and `EndpointSecurityExtension`.
	AllowedSystemExtensionTypes *SystemExtensionPolicyAllowedSystemExtensionTypes `plist:"AllowedSystemExtensionTypes,omitempty" json:"AllowedSystemExtensionTypes,omitempty"`
	// A dictionary of approved system extensions on the computer. The dictionary maps the team
	// identifiers (keys) to arrays of bundle identifiers, where the bundle identifier defines the
	// system extension to install.
	AllowedSystemExtensions *SystemExtensionPolicyAllowedSystemExtensions `plist:"AllowedSystemExtensions,omitempty" json:"AllowedSystemExtensions,omitempty"`
	// A dictionary of system extensions that are allowed to remove themselves from the machine. The
	// dictionary maps team identifiers (keys) to arrays of bundle identifiers, where the bundle
	// identifier defines the system extension. An application using the
	// `OSSystemExtensionDeactivationRequest` API can deactivate the specified system extensions
	// without requiring an administrator to authorize the operation.
	RemovableSystemExtensions *SystemExtensionPolicyRemovableSystemExtensions `plist:"RemovableSystemExtensions,omitempty" json:"RemovableSystemExtensions,omitempty"`
	// A dictionary of system extensions on the computer. The dictionary maps the team identifiers
	// (keys) to arrays of bundle identifiers, where the bundle identifier defines the system extension
	// which can't be disabled or uninstalled when SIP is enabled. It's an error for the same mapping
	// to appear in the dictionary values corresponding to `RemovableSystemExtensions` and
	// `NonRemovableSystemExtensions` keys.
	NonRemovableSystemExtensions *SystemExtensionPolicyNonRemovableSystemExtensions `plist:"NonRemovableSystemExtensions,omitempty" json:"NonRemovableSystemExtensions,omitempty"`
	// A dictionary of system extensions on the computer. The dictionary maps the team identifiers
	// (keys) to arrays of bundle identifiers, where the bundle identifier defines the system extension
	// which can't be disabled or uninstalled from System Settings or Finder. The set of system
	// extensions between `RemovableSystemExtensions` and `NonRemovableFromUISystemExtensions` can to
	// overlap.
	NonRemovableFromUISystemExtensions *SystemExtensionPolicyNonRemovableFromUISystemExtensions `plist:"NonRemovableFromUISystemExtensions,omitempty" json:"NonRemovableFromUISystemExtensions,omitempty"`
}

// SystemExtensionPolicyAllowedSystemExtensionTypes is the AllowedSystemExtensionTypes dictionary.
// A dictionary that maps a team identifier to an array of strings, where each string is a type of
// system extension that you can install for that team identifier. The allowed extension types are
// `DriverExtension`, `NetworkExtension`, and `EndpointSecurityExtension`.
type SystemExtensionPolicyAllowedSystemExtensionTypes struct {
	// The mapping of team identifier to an array of strings, where each string is a type of system
	// extension that may be installed for that team identifier.
	ANY []string `plist:"ANY,omitempty" json:"ANY,omitempty"`
}

// SystemExtensionPolicyAllowedSystemExtensions is the AllowedSystemExtensions dictionary.
// A dictionary of approved system extensions on the computer. The dictionary maps the team
// identifiers (keys) to arrays of bundle identifiers, where the bundle identifier defines the
// system extension to install.
type SystemExtensionPolicyAllowedSystemExtensions struct {
	// The mapping of team identifiers to arrays of bundle identifiers, where the bundle identifier is
	// that of the system extension to be installed.
	ANY []string `plist:"ANY,omitempty" json:"ANY,omitempty"`
}

// SystemExtensionPolicyRemovableSystemExtensions is the RemovableSystemExtensions dictionary.
// A dictionary of system extensions that are allowed to remove themselves from the machine. The
// dictionary maps team identifiers (keys) to arrays of bundle identifiers, where the bundle
// identifier defines the system extension. An application using the
// `OSSystemExtensionDeactivationRequest` API can deactivate the specified system extensions
// without requiring an administrator to authorize the operation.
type SystemExtensionPolicyRemovableSystemExtensions struct {
	// The dictionary maps team identifiers (keys) to arrays of bundle identifiers, where the bundle
	// identifier defines the system extension.
	ANY []string `plist:"ANY,omitempty" json:"ANY,omitempty"`
}

// SystemExtensionPolicyNonRemovableSystemExtensions is the NonRemovableSystemExtensions dictionary.
// A dictionary of system extensions on the computer. The dictionary maps the team identifiers
// (keys) to arrays of bundle identifiers, where the bundle identifier defines the system extension
// which can't be disabled or uninstalled when SIP is enabled. It's an error for the same mapping
// to appear in the dictionary values corresponding to `RemovableSystemExtensions` and
// `NonRemovableSystemExtensions` keys.
type SystemExtensionPolicyNonRemovableSystemExtensions struct {
	// System extension bundle identifiers
	ANY []string `plist:"ANY,omitempty" json:"ANY,omitempty"`
}

// SystemExtensionPolicyNonRemovableFromUISystemExtensions is the NonRemovableFromUISystemExtensions dictionary.
// A dictionary of system extensions on the computer. The dictionary maps the team identifiers
// (keys) to arrays of bundle identifiers, where the bundle identifier defines the system extension
// which can't be disabled or uninstalled from System Settings or Finder. The set of system
// extensions between `RemovableSystemExtensions` and `NonRemovableFromUISystemExtensions` can to
// overlap.
type SystemExtensionPolicyNonRemovableFromUISystemExtensions struct {
	// System extension bundle identifiers
	ANY []string `plist:"ANY,omitempty" json:"ANY,omitempty"`
}
