// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for TCCConfigurationProfilePolicy.
func (TCCConfigurationProfilePolicy) PayloadType() string {
	return "com.apple.TCC.configuration-profile-policy"
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *TCCConfigurationProfilePolicy) Validate() error {
	var errs []error
	if err := p.Services.Validate(); err != nil {
		errs = append(errs, validate.Nested("Services", err))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *TCCConfigurationProfilePolicyServicesIdentityDict) Validate() error {
	var errs []error
	if err := validate.InList("IdentifierType", p.IdentifierType, []TCCConfigurationProfilePolicyServicesIdentityDictIdentifierType{TCCConfigurationProfilePolicyServicesIdentityDictIdentifierTypeBundleID, TCCConfigurationProfilePolicyServicesIdentityDictIdentifierTypePath}); err != nil {
		errs = append(errs, err)
	}
	if p.Authorization != nil {
		if err := validate.InList("Authorization", *p.Authorization, []TCCConfigurationProfilePolicyServicesIdentityDictAuthorization{TCCConfigurationProfilePolicyServicesIdentityDictAuthorizationAllow, TCCConfigurationProfilePolicyServicesIdentityDictAuthorizationDeny, TCCConfigurationProfilePolicyServicesIdentityDictAuthorizationAllowStandardUserToSetSystemService}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.AEReceiverIdentifierType != nil {
		if err := validate.InList("AEReceiverIdentifierType", *p.AEReceiverIdentifierType, []TCCConfigurationProfilePolicyServicesIdentityDictAEReceiverIdentifierType{TCCConfigurationProfilePolicyServicesIdentityDictAEReceiverIdentifierTypeBundleID, TCCConfigurationProfilePolicyServicesIdentityDictAEReceiverIdentifierTypePath}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *TCCConfigurationProfilePolicyServices) Validate() error {
	var errs []error
	for i := range p.AddressBook {
		if err := p.AddressBook[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AddressBook", i, err))
		}
	}
	for i := range p.Calendar {
		if err := p.Calendar[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Calendar", i, err))
		}
	}
	for i := range p.Reminders {
		if err := p.Reminders[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Reminders", i, err))
		}
	}
	for i := range p.Photos {
		if err := p.Photos[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Photos", i, err))
		}
	}
	for i := range p.Camera {
		if err := p.Camera[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Camera", i, err))
		}
	}
	for i := range p.Microphone {
		if err := p.Microphone[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Microphone", i, err))
		}
	}
	for i := range p.Accessibility {
		if err := p.Accessibility[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Accessibility", i, err))
		}
	}
	for i := range p.PostEvent {
		if err := p.PostEvent[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("PostEvent", i, err))
		}
	}
	for i := range p.SystemPolicyAllFiles {
		if err := p.SystemPolicyAllFiles[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SystemPolicyAllFiles", i, err))
		}
	}
	for i := range p.SystemPolicySysAdminFiles {
		if err := p.SystemPolicySysAdminFiles[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SystemPolicySysAdminFiles", i, err))
		}
	}
	for i := range p.AppleEvents {
		if err := p.AppleEvents[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AppleEvents", i, err))
		}
	}
	for i := range p.MediaLibrary {
		if err := p.MediaLibrary[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("MediaLibrary", i, err))
		}
	}
	for i := range p.FileProviderPresence {
		if err := p.FileProviderPresence[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("FileProviderPresence", i, err))
		}
	}
	for i := range p.ListenEvent {
		if err := p.ListenEvent[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ListenEvent", i, err))
		}
	}
	for i := range p.ScreenCapture {
		if err := p.ScreenCapture[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ScreenCapture", i, err))
		}
	}
	for i := range p.SpeechRecognition {
		if err := p.SpeechRecognition[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SpeechRecognition", i, err))
		}
	}
	for i := range p.SystemPolicyDesktopFolder {
		if err := p.SystemPolicyDesktopFolder[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SystemPolicyDesktopFolder", i, err))
		}
	}
	for i := range p.SystemPolicyDocumentsFolder {
		if err := p.SystemPolicyDocumentsFolder[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SystemPolicyDocumentsFolder", i, err))
		}
	}
	for i := range p.SystemPolicyDownloadsFolder {
		if err := p.SystemPolicyDownloadsFolder[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SystemPolicyDownloadsFolder", i, err))
		}
	}
	for i := range p.SystemPolicyNetworkVolumes {
		if err := p.SystemPolicyNetworkVolumes[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SystemPolicyNetworkVolumes", i, err))
		}
	}
	for i := range p.SystemPolicyRemovableVolumes {
		if err := p.SystemPolicyRemovableVolumes[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SystemPolicyRemovableVolumes", i, err))
		}
	}
	for i := range p.SystemPolicyAppBundles {
		if err := p.SystemPolicyAppBundles[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SystemPolicyAppBundles", i, err))
		}
	}
	for i := range p.SystemPolicyAppData {
		if err := p.SystemPolicyAppData[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SystemPolicyAppData", i, err))
		}
	}
	for i := range p.BluetoothAlways {
		if err := p.BluetoothAlways[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("BluetoothAlways", i, err))
		}
	}
	return errors.Join(errs...)
}
