// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for TopLevel.
func (TopLevel) PayloadType() string { return "TopLevel" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *TopLevel) Validate() error {
	var errs []error
	if err := validate.InList("PayloadType", p.PayloadType2, []string{"Configuration"}); err != nil {
		errs = append(errs, err)
	}
	if err := validate.InList("PayloadVersion", p.PayloadVersion, []int64{1}); err != nil {
		errs = append(errs, err)
	}
	if p.PayloadContent == nil {
		errs = append(errs, validate.Required("PayloadContent"))
	}
	for i := range p.PayloadContent {
		if err := p.PayloadContent[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("PayloadContent", i, err))
		}
	}
	if p.PayloadScope != nil {
		if err := validate.InList("PayloadScope", *p.PayloadScope, []TopLevelPayloadScope{TopLevelPayloadScopeSystem, TopLevelPayloadScopeUser}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.TargetDeviceType != nil {
		if err := validate.InList("TargetDeviceType", *p.TargetDeviceType, []TopLevelTargetDeviceType{TopLevelTargetDeviceTypeValue0, TopLevelTargetDeviceTypeValue1, TopLevelTargetDeviceTypeValue2, TopLevelTargetDeviceTypeValue3, TopLevelTargetDeviceTypeValue4, TopLevelTargetDeviceTypeValue5, TopLevelTargetDeviceTypeValue6}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ConsentText != nil {
		if err := p.ConsentText.Validate(); err != nil {
			errs = append(errs, validate.Nested("ConsentText", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *TopLevelPayloadContentItem) Validate() error {
	var errs []error
	if p.ANY == nil {
		errs = append(errs, validate.Required("ANY"))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. TopLevelConsentTextConsentTextItem has no
// constraints beyond its field types.
func (p *TopLevelConsentTextConsentTextItem) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *TopLevelConsentText) Validate() error {
	var errs []error
	if err := p.ConsentTextItem.Validate(); err != nil {
		errs = append(errs, validate.Nested("ConsentTextItem", err))
	}
	return errors.Join(errs...)
}
