// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// Tvremote — TV Remote.
// The payload that configures the Apple TV remote.
//
// Supported: iOS 11.3+, tvOS 11.3+.
type Tvremote struct {
	// The array of valid devices that Apple TV can connect to.
	AllowedRemotes []TvremoteAllowedRemotesItem `plist:"AllowedRemotes,omitempty" json:"AllowedRemotes,omitempty"`
	// The array of valid Apple TV identifiers that the remote can connect to.
	AllowedTVs []TvremoteAllowedTVsItem `plist:"AllowedTVs,omitempty" json:"AllowedTVs,omitempty"`
}

// TvremoteAllowedRemotesItem is the AllowedRemotesItem dictionary.
// The array of valid devices that Apple TV can connect to.
type TvremoteAllowedRemotesItem struct {
	// The MAC address of a permitted iOS device that can control this Apple TV. Use the format
	// `xx:xx:xx:xx:xx:xx`, which isn't case-sensitive.
	RemoteDeviceID string `plist:"RemoteDeviceID" json:"RemoteDeviceID"`
}

// TvremoteAllowedTVsItem is the AllowedTVsItem dictionary.
// The array of valid Apple TV identifiers that the remote can connect to.
type TvremoteAllowedTVsItem struct {
	// The MAC address of an Apple TV device that the system permits this iOS device to control. Use
	// the format `xx:xx:xx:xx:xx:xx`, which isn't case-sensitive.
	TVDeviceID string `plist:"TVDeviceID" json:"TVDeviceID"`
	// The name of an Apple TV device that the system permits this iOS device to control.
	TVDeviceName *string `plist:"TVDeviceName,omitempty" json:"TVDeviceName,omitempty"`
}
