// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for VpnManagedAppmapping.
func (VpnManagedAppmapping) PayloadType() string { return "com.apple.vpn.managed.appmapping" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedAppmapping) Validate() error {
	var errs []error
	if p.AppLayerVPNMapping == nil {
		errs = append(errs, validate.Required("AppLayerVPNMapping"))
	}
	for i := range p.AppLayerVPNMapping {
		if err := p.AppLayerVPNMapping[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AppLayerVPNMapping", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. VpnManagedAppmappingAppLayerVPNMappingItemMatchToolsItem has no
// constraints beyond its field types.
func (p *VpnManagedAppmappingAppLayerVPNMappingItemMatchToolsItem) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedAppmappingAppLayerVPNMappingItem) Validate() error {
	var errs []error
	for i := range p.MatchTools {
		if err := p.MatchTools[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("MatchTools", i, err))
		}
	}
	return errors.Join(errs...)
}
