// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/ptr"
	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// PayloadType returns the wire type identifier for VpnManaged.
func (VpnManaged) PayloadType() string { return "com.apple.vpn.managed" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManaged) Validate() error {
	var errs []error
	if err := validate.InList("VPNType", p.VPNType, []VpnManagedVPNType{VpnManagedVPNTypeVPN, VpnManagedVPNTypeL2TP, VpnManagedVPNTypeIPSec, VpnManagedVPNTypeIKEv2, VpnManagedVPNTypeAlwaysOn, VpnManagedVPNTypeTransparentProxy}); err != nil {
		errs = append(errs, err)
	}
	if p.VendorConfig != nil {
		if err := p.VendorConfig.Validate(); err != nil {
			errs = append(errs, validate.Nested("VendorConfig", err))
		}
	}
	if p.VPN != nil {
		if err := p.VPN.Validate(); err != nil {
			errs = append(errs, validate.Nested("VPN", err))
		}
	}
	if p.IPv4 != nil {
		if err := p.IPv4.Validate(); err != nil {
			errs = append(errs, validate.Nested("IPv4", err))
		}
	}
	if p.PPP != nil {
		if err := p.PPP.Validate(); err != nil {
			errs = append(errs, validate.Nested("PPP", err))
		}
	}
	if p.IPSec != nil {
		if err := p.IPSec.Validate(); err != nil {
			errs = append(errs, validate.Nested("IPSec", err))
		}
	}
	if p.IKEv2 != nil {
		if err := p.IKEv2.Validate(); err != nil {
			errs = append(errs, validate.Nested("IKEv2", err))
		}
	}
	if p.DNS != nil {
		if err := p.DNS.Validate(); err != nil {
			errs = append(errs, validate.Nested("DNS", err))
		}
	}
	if p.Proxies != nil {
		if err := p.Proxies.Validate(); err != nil {
			errs = append(errs, validate.Nested("Proxies", err))
		}
	}
	if p.AlwaysOn != nil {
		if err := p.AlwaysOn.Validate(); err != nil {
			errs = append(errs, validate.Nested("AlwaysOn", err))
		}
	}
	if p.TransparentProxy != nil {
		if err := p.TransparentProxy.Validate(); err != nil {
			errs = append(errs, validate.Nested("TransparentProxy", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. VpnManagedVendorConfig has no
// constraints beyond its field types.
func (p *VpnManagedVendorConfig) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedVPNOnDemandRulesElementActionParameter) Validate() error {
	var errs []error
	if p.Domains == nil {
		errs = append(errs, validate.Required("Domains"))
	}
	if err := validate.InList("DomainAction", p.DomainAction, []VpnManagedVPNOnDemandRulesElementActionParameterDomainAction{VpnManagedVPNOnDemandRulesElementActionParameterDomainActionConnectIfNeeded, VpnManagedVPNOnDemandRulesElementActionParameterDomainActionNeverConnect}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedVPNOnDemandRulesElement) Validate() error {
	var errs []error
	if err := validate.InList("Action", p.Action, []VpnManagedVPNOnDemandRulesElementAction{VpnManagedVPNOnDemandRulesElementActionAllow, VpnManagedVPNOnDemandRulesElementActionConnect, VpnManagedVPNOnDemandRulesElementActionDisconnect, VpnManagedVPNOnDemandRulesElementActionEvaluateConnection, VpnManagedVPNOnDemandRulesElementActionIgnore}); err != nil {
		errs = append(errs, err)
	}
	for i := range p.ActionParameters {
		if err := p.ActionParameters[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ActionParameters", i, err))
		}
	}
	if p.InterfaceTypeMatch != nil {
		if err := validate.InList("InterfaceTypeMatch", *p.InterfaceTypeMatch, []VpnManagedVPNOnDemandRulesElementInterfaceTypeMatch{VpnManagedVPNOnDemandRulesElementInterfaceTypeMatchEthernet, VpnManagedVPNOnDemandRulesElementInterfaceTypeMatchWiFi, VpnManagedVPNOnDemandRulesElementInterfaceTypeMatchCellular}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedVPN) Validate() error {
	var errs []error
	if p.AuthenticationMethod != nil {
		if err := validate.InList("AuthenticationMethod", *p.AuthenticationMethod, []VpnManagedVPNAuthenticationMethod{VpnManagedVPNAuthenticationMethodPassword, VpnManagedVPNAuthenticationMethodCertificate, VpnManagedVPNAuthenticationMethodPasswordCertificate}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.DisconnectOnIdle != nil {
		if err := validate.InList("DisconnectOnIdle", *p.DisconnectOnIdle, []VpnManagedVPNDisconnectOnIdle{VpnManagedVPNDisconnectOnIdleValue0, VpnManagedVPNDisconnectOnIdleValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ProviderType != nil {
		if err := validate.InList("ProviderType", *p.ProviderType, []VpnManagedVPNProviderType{VpnManagedVPNProviderTypePacketTunnel, VpnManagedVPNProviderTypeAppProxy}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.IncludeAllNetworks != nil {
		if err := validate.InList("IncludeAllNetworks", *p.IncludeAllNetworks, []VpnManagedVPNIncludeAllNetworks{VpnManagedVPNIncludeAllNetworksValue0, VpnManagedVPNIncludeAllNetworksValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.EnforceRoutes != nil {
		if err := validate.InList("EnforceRoutes", *p.EnforceRoutes, []VpnManagedVPNEnforceRoutes{VpnManagedVPNEnforceRoutesValue0, VpnManagedVPNEnforceRoutesValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ExcludeLocalNetworks != nil {
		if err := validate.InList("ExcludeLocalNetworks", *p.ExcludeLocalNetworks, []VpnManagedVPNExcludeLocalNetworks{VpnManagedVPNExcludeLocalNetworksValue0, VpnManagedVPNExcludeLocalNetworksValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ExcludeCellularServices != nil {
		if err := validate.InList("ExcludeCellularServices", *p.ExcludeCellularServices, []VpnManagedVPNExcludeCellularServices{VpnManagedVPNExcludeCellularServicesValue0, VpnManagedVPNExcludeCellularServicesValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ExcludeAPNs != nil {
		if err := validate.InList("ExcludeAPNs", *p.ExcludeAPNs, []VpnManagedVPNExcludeAPNs{VpnManagedVPNExcludeAPNsValue0, VpnManagedVPNExcludeAPNsValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ExcludeDeviceCommunication != nil {
		if err := validate.InList("ExcludeDeviceCommunication", *p.ExcludeDeviceCommunication, []VpnManagedVPNExcludeDeviceCommunication{VpnManagedVPNExcludeDeviceCommunicationValue0, VpnManagedVPNExcludeDeviceCommunicationValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.OnDemandEnabled != nil {
		if err := validate.InList("OnDemandEnabled", *p.OnDemandEnabled, []VpnManagedVPNOnDemandEnabled{VpnManagedVPNOnDemandEnabledValue0, VpnManagedVPNOnDemandEnabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.OnDemandUserOverrideDisabled != nil {
		if err := validate.InList("OnDemandUserOverrideDisabled", *p.OnDemandUserOverrideDisabled, []VpnManagedVPNOnDemandUserOverrideDisabled{VpnManagedVPNOnDemandUserOverrideDisabledValue0, VpnManagedVPNOnDemandUserOverrideDisabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	for i := range p.OnDemandRules {
		if err := p.OnDemandRules[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("OnDemandRules", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedIPv4) Validate() error {
	var errs []error
	if p.OverridePrimary != nil {
		if err := validate.InList("OverridePrimary", *p.OverridePrimary, []VpnManagedIPv4OverridePrimary{VpnManagedIPv4OverridePrimaryValue0, VpnManagedIPv4OverridePrimaryValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedPPP) Validate() error {
	var errs []error
	if p.TokenCard != nil {
		if err := validate.InList("TokenCard", *p.TokenCard, []VpnManagedPPPTokenCard{VpnManagedPPPTokenCardValue0, VpnManagedPPPTokenCardValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	for i := range p.AuthEAPPlugins {
		if err := validate.InList("AuthEAPPlugins", p.AuthEAPPlugins[i], []string{"EAP-RSA", "EAP-TLS", "EAP-KRB"}); err != nil {
			errs = append(errs, err)
		}
	}
	for i := range p.AuthProtocol {
		if err := validate.InList("AuthProtocol", p.AuthProtocol[i], []string{"EAP"}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.CCPMPPE40Enabled != nil {
		if err := validate.InList("CCPMPPE40Enabled", *p.CCPMPPE40Enabled, []VpnManagedPPPCCPMPPE40Enabled{VpnManagedPPPCCPMPPE40EnabledValue0, VpnManagedPPPCCPMPPE40EnabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.CCPMPPE128Enabled != nil {
		if err := validate.InList("CCPMPPE128Enabled", *p.CCPMPPE128Enabled, []VpnManagedPPPCCPMPPE128Enabled{VpnManagedPPPCCPMPPE128EnabledValue0, VpnManagedPPPCCPMPPE128EnabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.CCPEnabled != nil {
		if err := validate.InList("CCPEnabled", *p.CCPEnabled, []VpnManagedPPPCCPEnabled{VpnManagedPPPCCPEnabledValue0, VpnManagedPPPCCPEnabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.DisconnectOnIdle != nil {
		if err := validate.InList("DisconnectOnIdle", *p.DisconnectOnIdle, []VpnManagedPPPDisconnectOnIdle{VpnManagedPPPDisconnectOnIdleValue0, VpnManagedPPPDisconnectOnIdleValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedIPSecOnDemandRulesElementActionParameter) Validate() error {
	var errs []error
	if p.Domains == nil {
		errs = append(errs, validate.Required("Domains"))
	}
	if err := validate.InList("DomainAction", p.DomainAction, []VpnManagedIPSecOnDemandRulesElementActionParameterDomainAction{VpnManagedIPSecOnDemandRulesElementActionParameterDomainActionConnectIfNeeded, VpnManagedIPSecOnDemandRulesElementActionParameterDomainActionNeverConnect}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedIPSecOnDemandRulesElement) Validate() error {
	var errs []error
	if err := validate.InList("Action", p.Action, []VpnManagedIPSecOnDemandRulesElementAction{VpnManagedIPSecOnDemandRulesElementActionAllow, VpnManagedIPSecOnDemandRulesElementActionConnect, VpnManagedIPSecOnDemandRulesElementActionDisconnect, VpnManagedIPSecOnDemandRulesElementActionEvaluateConnection, VpnManagedIPSecOnDemandRulesElementActionIgnore}); err != nil {
		errs = append(errs, err)
	}
	for i := range p.ActionParameters {
		if err := p.ActionParameters[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ActionParameters", i, err))
		}
	}
	if p.InterfaceTypeMatch != nil {
		if err := validate.InList("InterfaceTypeMatch", *p.InterfaceTypeMatch, []VpnManagedIPSecOnDemandRulesElementInterfaceTypeMatch{VpnManagedIPSecOnDemandRulesElementInterfaceTypeMatchEthernet, VpnManagedIPSecOnDemandRulesElementInterfaceTypeMatchWiFi, VpnManagedIPSecOnDemandRulesElementInterfaceTypeMatchCellular}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedIPSec) Validate() error {
	var errs []error
	if p.AuthenticationMethod != nil {
		if err := validate.InList("AuthenticationMethod", *p.AuthenticationMethod, []VpnManagedIPSecAuthenticationMethod{VpnManagedIPSecAuthenticationMethodSharedSecret, VpnManagedIPSecAuthenticationMethodCertificate}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.XAuthEnabled != nil {
		if err := validate.InList("XAuthEnabled", *p.XAuthEnabled, []VpnManagedIPSecXAuthEnabled{VpnManagedIPSecXAuthEnabledValue0, VpnManagedIPSecXAuthEnabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.XAuthPasswordEncryption != nil {
		if err := validate.InList("XAuthPasswordEncryption", *p.XAuthPasswordEncryption, []string{"Prompt"}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.LocalIdentifierType != nil {
		if err := validate.InList("LocalIdentifierType", *p.LocalIdentifierType, []string{"KeyID"}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.DisconnectOnIdle != nil {
		if err := validate.InList("DisconnectOnIdle", *p.DisconnectOnIdle, []VpnManagedIPSecDisconnectOnIdle{VpnManagedIPSecDisconnectOnIdleValue0, VpnManagedIPSecDisconnectOnIdleValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.OnDemandEnabled != nil {
		if err := validate.InList("OnDemandEnabled", *p.OnDemandEnabled, []VpnManagedIPSecOnDemandEnabled{VpnManagedIPSecOnDemandEnabledValue0, VpnManagedIPSecOnDemandEnabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	for i := range p.OnDemandRules {
		if err := p.OnDemandRules[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("OnDemandRules", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedIKEv2OnDemandRulesElementActionParameter) Validate() error {
	var errs []error
	if p.Domains == nil {
		errs = append(errs, validate.Required("Domains"))
	}
	if err := validate.InList("DomainAction", p.DomainAction, []VpnManagedIKEv2OnDemandRulesElementActionParameterDomainAction{VpnManagedIKEv2OnDemandRulesElementActionParameterDomainActionConnectIfNeeded, VpnManagedIKEv2OnDemandRulesElementActionParameterDomainActionNeverConnect}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedIKEv2OnDemandRulesElement) Validate() error {
	var errs []error
	if err := validate.InList("Action", p.Action, []VpnManagedIKEv2OnDemandRulesElementAction{VpnManagedIKEv2OnDemandRulesElementActionAllow, VpnManagedIKEv2OnDemandRulesElementActionConnect, VpnManagedIKEv2OnDemandRulesElementActionDisconnect, VpnManagedIKEv2OnDemandRulesElementActionEvaluateConnection, VpnManagedIKEv2OnDemandRulesElementActionIgnore}); err != nil {
		errs = append(errs, err)
	}
	for i := range p.ActionParameters {
		if err := p.ActionParameters[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ActionParameters", i, err))
		}
	}
	if p.InterfaceTypeMatch != nil {
		if err := validate.InList("InterfaceTypeMatch", *p.InterfaceTypeMatch, []VpnManagedIKEv2OnDemandRulesElementInterfaceTypeMatch{VpnManagedIKEv2OnDemandRulesElementInterfaceTypeMatchEthernet, VpnManagedIKEv2OnDemandRulesElementInterfaceTypeMatchWiFi, VpnManagedIKEv2OnDemandRulesElementInterfaceTypeMatchCellular}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *SecurityAssociationParameters) Validate() error {
	var errs []error
	if p.EncryptionAlgorithm != nil {
		if err := validate.InList("EncryptionAlgorithm", *p.EncryptionAlgorithm, []SecurityAssociationParametersEncryptionAlgorithm{SecurityAssociationParametersEncryptionAlgorithmDES, SecurityAssociationParametersEncryptionAlgorithmN3DES, SecurityAssociationParametersEncryptionAlgorithmAES128, SecurityAssociationParametersEncryptionAlgorithmAES256, SecurityAssociationParametersEncryptionAlgorithmAES128GCM, SecurityAssociationParametersEncryptionAlgorithmAES256GCM, SecurityAssociationParametersEncryptionAlgorithmChaCha20Poly1305}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.IntegrityAlgorithm != nil {
		if err := validate.InList("IntegrityAlgorithm", *p.IntegrityAlgorithm, []SecurityAssociationParametersIntegrityAlgorithm{SecurityAssociationParametersIntegrityAlgorithmSHA196, SecurityAssociationParametersIntegrityAlgorithmSHA1160, SecurityAssociationParametersIntegrityAlgorithmSHA2256, SecurityAssociationParametersIntegrityAlgorithmSHA2384, SecurityAssociationParametersIntegrityAlgorithmSHA2512}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.DiffieHellmanGroup != nil {
		if err := validate.InList("DiffieHellmanGroup", *p.DiffieHellmanGroup, []SecurityAssociationParametersDiffieHellmanGroup{SecurityAssociationParametersDiffieHellmanGroupValue1, SecurityAssociationParametersDiffieHellmanGroupValue2, SecurityAssociationParametersDiffieHellmanGroupValue5, SecurityAssociationParametersDiffieHellmanGroupValue14, SecurityAssociationParametersDiffieHellmanGroupValue15, SecurityAssociationParametersDiffieHellmanGroupValue16, SecurityAssociationParametersDiffieHellmanGroupValue17, SecurityAssociationParametersDiffieHellmanGroupValue18, SecurityAssociationParametersDiffieHellmanGroupValue19, SecurityAssociationParametersDiffieHellmanGroupValue20, SecurityAssociationParametersDiffieHellmanGroupValue21, SecurityAssociationParametersDiffieHellmanGroupValue31, SecurityAssociationParametersDiffieHellmanGroupValue32}); err != nil {
			errs = append(errs, err)
		}
	}
	for i := range p.PostQuantumKeyExchangeMethods {
		if err := validate.InList("PostQuantumKeyExchangeMethods", p.PostQuantumKeyExchangeMethods[i], []int64{0, 36, 37}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.LifeTimeInMinutes != nil {
		if err := validate.IntRange("LifeTimeInMinutes", *p.LifeTimeInMinutes, ptr.To(int64(10)), ptr.To(int64(1440))); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedIKEv2) Validate() error {
	var errs []error
	if err := validate.InList("AuthenticationMethod", p.AuthenticationMethod, []VpnManagedIKEv2AuthenticationMethod{VpnManagedIKEv2AuthenticationMethodNone, VpnManagedIKEv2AuthenticationMethodSharedSecret, VpnManagedIKEv2AuthenticationMethodCertificate}); err != nil {
		errs = append(errs, err)
	}
	if p.CertificateType != nil {
		if err := validate.InList("CertificateType", *p.CertificateType, []VpnManagedIKEv2CertificateType{VpnManagedIKEv2CertificateTypeRSA, VpnManagedIKEv2CertificateTypeECDSA256, VpnManagedIKEv2CertificateTypeECDSA384, VpnManagedIKEv2CertificateTypeECDSA521, VpnManagedIKEv2CertificateTypeRSAPSS}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ExtendedAuthEnabled != nil {
		if err := validate.InList("ExtendedAuthEnabled", *p.ExtendedAuthEnabled, []VpnManagedIKEv2ExtendedAuthEnabled{VpnManagedIKEv2ExtendedAuthEnabledValue0, VpnManagedIKEv2ExtendedAuthEnabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.OnDemandEnabled != nil {
		if err := validate.InList("OnDemandEnabled", *p.OnDemandEnabled, []VpnManagedIKEv2OnDemandEnabled{VpnManagedIKEv2OnDemandEnabledValue0, VpnManagedIKEv2OnDemandEnabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.OnDemandUserOverrideDisabled != nil {
		if err := validate.InList("OnDemandUserOverrideDisabled", *p.OnDemandUserOverrideDisabled, []VpnManagedIKEv2OnDemandUserOverrideDisabled{VpnManagedIKEv2OnDemandUserOverrideDisabledValue0, VpnManagedIKEv2OnDemandUserOverrideDisabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	for i := range p.OnDemandRules {
		if err := p.OnDemandRules[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("OnDemandRules", i, err))
		}
	}
	if p.DeadPeerDetectionRate != nil {
		if err := validate.InList("DeadPeerDetectionRate", *p.DeadPeerDetectionRate, []VpnManagedIKEv2DeadPeerDetectionRate{VpnManagedIKEv2DeadPeerDetectionRateNone, VpnManagedIKEv2DeadPeerDetectionRateLow, VpnManagedIKEv2DeadPeerDetectionRateMedium, VpnManagedIKEv2DeadPeerDetectionRateHigh}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.TLSMinimumVersion != nil {
		if err := validate.InList("TLSMinimumVersion", *p.TLSMinimumVersion, []VpnManagedIKEv2TLSMinimumVersion{VpnManagedIKEv2TLSMinimumVersionN10, VpnManagedIKEv2TLSMinimumVersionN11, VpnManagedIKEv2TLSMinimumVersionN12}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.TLSMaximumVersion != nil {
		if err := validate.InList("TLSMaximumVersion", *p.TLSMaximumVersion, []VpnManagedIKEv2TLSMaximumVersion{VpnManagedIKEv2TLSMaximumVersionN10, VpnManagedIKEv2TLSMaximumVersionN11, VpnManagedIKEv2TLSMaximumVersionN12}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.UseConfigurationAttributeInternalIPSubnet != nil {
		if err := validate.InList("UseConfigurationAttributeInternalIPSubnet", *p.UseConfigurationAttributeInternalIPSubnet, []VpnManagedIKEv2UseConfigurationAttributeInternalIPSubnet{VpnManagedIKEv2UseConfigurationAttributeInternalIPSubnetValue0, VpnManagedIKEv2UseConfigurationAttributeInternalIPSubnetValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.DisableMOBIKE != nil {
		if err := validate.InList("DisableMOBIKE", *p.DisableMOBIKE, []VpnManagedIKEv2DisableMOBIKE{VpnManagedIKEv2DisableMOBIKEValue0, VpnManagedIKEv2DisableMOBIKEValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.DisableRedirect != nil {
		if err := validate.InList("DisableRedirect", *p.DisableRedirect, []VpnManagedIKEv2DisableRedirect{VpnManagedIKEv2DisableRedirectValue0, VpnManagedIKEv2DisableRedirectValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.DisconnectOnIdle != nil {
		if err := validate.InList("DisconnectOnIdle", *p.DisconnectOnIdle, []VpnManagedIKEv2DisconnectOnIdle{VpnManagedIKEv2DisconnectOnIdleValue0, VpnManagedIKEv2DisconnectOnIdleValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.NATKeepAliveOffloadEnable != nil {
		if err := validate.InList("NATKeepAliveOffloadEnable", *p.NATKeepAliveOffloadEnable, []VpnManagedIKEv2NATKeepAliveOffloadEnable{VpnManagedIKEv2NATKeepAliveOffloadEnableValue0, VpnManagedIKEv2NATKeepAliveOffloadEnableValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.EnablePFS != nil {
		if err := validate.InList("EnablePFS", *p.EnablePFS, []VpnManagedIKEv2EnablePFS{VpnManagedIKEv2EnablePFSValue0, VpnManagedIKEv2EnablePFSValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.EnableCertificateRevocationCheck != nil {
		if err := validate.InList("EnableCertificateRevocationCheck", *p.EnableCertificateRevocationCheck, []VpnManagedIKEv2EnableCertificateRevocationCheck{VpnManagedIKEv2EnableCertificateRevocationCheckValue0, VpnManagedIKEv2EnableCertificateRevocationCheckValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.EnableFallback != nil {
		if err := validate.InList("EnableFallback", *p.EnableFallback, []VpnManagedIKEv2EnableFallback{VpnManagedIKEv2EnableFallbackValue0, VpnManagedIKEv2EnableFallbackValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.MTU != nil {
		if err := validate.IntRange("MTU", *p.MTU, ptr.To(int64(1280)), ptr.To(int64(1400))); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ProviderType != nil {
		if err := validate.InList("ProviderType", *p.ProviderType, []VpnManagedIKEv2ProviderType{VpnManagedIKEv2ProviderTypePacketTunnel, VpnManagedIKEv2ProviderTypeAppProxy}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.IncludeAllNetworks != nil {
		if err := validate.InList("IncludeAllNetworks", *p.IncludeAllNetworks, []VpnManagedIKEv2IncludeAllNetworks{VpnManagedIKEv2IncludeAllNetworksValue0, VpnManagedIKEv2IncludeAllNetworksValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.EnforceRoutes != nil {
		if err := validate.InList("EnforceRoutes", *p.EnforceRoutes, []VpnManagedIKEv2EnforceRoutes{VpnManagedIKEv2EnforceRoutesValue0, VpnManagedIKEv2EnforceRoutesValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ExcludeLocalNetworks != nil {
		if err := validate.InList("ExcludeLocalNetworks", *p.ExcludeLocalNetworks, []VpnManagedIKEv2ExcludeLocalNetworks{VpnManagedIKEv2ExcludeLocalNetworksValue0, VpnManagedIKEv2ExcludeLocalNetworksValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ExcludeCellularServices != nil {
		if err := validate.InList("ExcludeCellularServices", *p.ExcludeCellularServices, []VpnManagedIKEv2ExcludeCellularServices{VpnManagedIKEv2ExcludeCellularServicesValue0, VpnManagedIKEv2ExcludeCellularServicesValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ExcludeAPNs != nil {
		if err := validate.InList("ExcludeAPNs", *p.ExcludeAPNs, []VpnManagedIKEv2ExcludeAPNs{VpnManagedIKEv2ExcludeAPNsValue0, VpnManagedIKEv2ExcludeAPNsValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ExcludeDeviceCommunication != nil {
		if err := validate.InList("ExcludeDeviceCommunication", *p.ExcludeDeviceCommunication, []VpnManagedIKEv2ExcludeDeviceCommunication{VpnManagedIKEv2ExcludeDeviceCommunicationValue0, VpnManagedIKEv2ExcludeDeviceCommunicationValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.PPKMandatory != nil {
		if err := validate.InList("PPKMandatory", *p.PPKMandatory, []VpnManagedIKEv2PPKMandatory{VpnManagedIKEv2PPKMandatoryValue0, VpnManagedIKEv2PPKMandatoryValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.AllowPostQuantumKeyExchangeFallback != nil {
		if err := validate.InList("AllowPostQuantumKeyExchangeFallback", *p.AllowPostQuantumKeyExchangeFallback, []VpnManagedIKEv2AllowPostQuantumKeyExchangeFallback{VpnManagedIKEv2AllowPostQuantumKeyExchangeFallbackValue0, VpnManagedIKEv2AllowPostQuantumKeyExchangeFallbackValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.EnforceStrictAlgorithmSelection != nil {
		if err := validate.InList("EnforceStrictAlgorithmSelection", *p.EnforceStrictAlgorithmSelection, []VpnManagedIKEv2EnforceStrictAlgorithmSelection{VpnManagedIKEv2EnforceStrictAlgorithmSelectionValue0, VpnManagedIKEv2EnforceStrictAlgorithmSelectionValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.IKESecurityAssociationParameters != nil {
		if err := p.IKESecurityAssociationParameters.Validate(); err != nil {
			errs = append(errs, validate.Nested("IKESecurityAssociationParameters", err))
		}
	}
	if p.ChildSecurityAssociationParameters != nil {
		if err := p.ChildSecurityAssociationParameters.Validate(); err != nil {
			errs = append(errs, validate.Nested("ChildSecurityAssociationParameters", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedDNS) Validate() error {
	var errs []error
	if err := validate.InList("DNSProtocol", p.DNSProtocol, []VpnManagedDNSDNSProtocol{VpnManagedDNSDNSProtocolCleartext, VpnManagedDNSDNSProtocolHTTPS, VpnManagedDNSDNSProtocolTLS}); err != nil {
		errs = append(errs, err)
	}
	if p.ServerAddresses == nil {
		errs = append(errs, validate.Required("ServerAddresses"))
	}
	if p.SupplementalMatchDomainsNoSearch != nil {
		if err := validate.InList("SupplementalMatchDomainsNoSearch", *p.SupplementalMatchDomainsNoSearch, []VpnManagedDNSSupplementalMatchDomainsNoSearch{VpnManagedDNSSupplementalMatchDomainsNoSearchValue0, VpnManagedDNSSupplementalMatchDomainsNoSearchValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.PayloadCertificateUUID != nil {
		if err := validate.Format("PayloadCertificateUUID", *p.PayloadCertificateUUID, "^[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{12}$"); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedProxies) Validate() error {
	var errs []error
	if p.ProxyAutoConfigEnable != nil {
		if err := validate.InList("ProxyAutoConfigEnable", *p.ProxyAutoConfigEnable, []VpnManagedProxiesProxyAutoConfigEnable{VpnManagedProxiesProxyAutoConfigEnableValue0, VpnManagedProxiesProxyAutoConfigEnableValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.ProxyAutoDiscoveryEnable != nil {
		if err := validate.InList("ProxyAutoDiscoveryEnable", *p.ProxyAutoDiscoveryEnable, []VpnManagedProxiesProxyAutoDiscoveryEnable{VpnManagedProxiesProxyAutoDiscoveryEnableValue0, VpnManagedProxiesProxyAutoDiscoveryEnableValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.HTTPEnable != nil {
		if err := validate.InList("HTTPEnable", *p.HTTPEnable, []VpnManagedProxiesHTTPEnable{VpnManagedProxiesHTTPEnableValue0, VpnManagedProxiesHTTPEnableValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.HTTPPort != nil {
		if err := validate.IntRange("HTTPPort", *p.HTTPPort, ptr.To(int64(0)), ptr.To(int64(65535))); err != nil {
			errs = append(errs, err)
		}
	}
	if p.HTTPSEnable != nil {
		if err := validate.InList("HTTPSEnable", *p.HTTPSEnable, []VpnManagedProxiesHTTPSEnable{VpnManagedProxiesHTTPSEnableValue0, VpnManagedProxiesHTTPSEnableValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.HTTPSPort != nil {
		if err := validate.IntRange("HTTPSPort", *p.HTTPSPort, ptr.To(int64(0)), ptr.To(int64(65535))); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedAlwaysOnTunnelConfigurationElement) Validate() error {
	var errs []error
	if err := validate.InList("ProtocolType", p.ProtocolType, []string{"IKEv2"}); err != nil {
		errs = append(errs, err)
	}
	for i := range p.Interfaces {
		if err := validate.InList("Interfaces", p.Interfaces[i], []string{"Cellular", "WiFi"}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedAlwaysOnServiceExceptionElement) Validate() error {
	var errs []error
	if err := validate.InList("ServiceName", p.ServiceName, []VpnManagedAlwaysOnServiceExceptionElementServiceName{VpnManagedAlwaysOnServiceExceptionElementServiceNameVoiceMail, VpnManagedAlwaysOnServiceExceptionElementServiceNameAirPrint, VpnManagedAlwaysOnServiceExceptionElementServiceNameCellularServices, VpnManagedAlwaysOnServiceExceptionElementServiceNameDeviceCommunication}); err != nil {
		errs = append(errs, err)
	}
	if err := validate.InList("Action", p.Action, []VpnManagedAlwaysOnServiceExceptionElementAction{VpnManagedAlwaysOnServiceExceptionElementActionAllow, VpnManagedAlwaysOnServiceExceptionElementActionDrop}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedAlwaysOnApplicationExceptionElement) Validate() error {
	var errs []error
	for i := range p.LimitToProtocols {
		if err := validate.InList("LimitToProtocols", p.LimitToProtocols[i], []string{"UDP"}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. VpnManagedAlwaysOnAllowedCaptiveNetworkPluginElement has no
// constraints beyond its field types.
func (p *VpnManagedAlwaysOnAllowedCaptiveNetworkPluginElement) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedAlwaysOn) Validate() error {
	var errs []error
	if p.UIToggleEnabled != nil {
		if err := validate.InList("UIToggleEnabled", *p.UIToggleEnabled, []VpnManagedAlwaysOnUIToggleEnabled{VpnManagedAlwaysOnUIToggleEnabledValue0, VpnManagedAlwaysOnUIToggleEnabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.TunnelConfigurations == nil {
		errs = append(errs, validate.Required("TunnelConfigurations"))
	}
	for i := range p.TunnelConfigurations {
		if err := p.TunnelConfigurations[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("TunnelConfigurations", i, err))
		}
	}
	for i := range p.ServiceExceptions {
		if err := p.ServiceExceptions[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ServiceExceptions", i, err))
		}
	}
	for i := range p.ApplicationExceptions {
		if err := p.ApplicationExceptions[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ApplicationExceptions", i, err))
		}
	}
	if p.AllowCaptiveWebSheet != nil {
		if err := validate.InList("AllowCaptiveWebSheet", *p.AllowCaptiveWebSheet, []VpnManagedAlwaysOnAllowCaptiveWebSheet{VpnManagedAlwaysOnAllowCaptiveWebSheetValue0, VpnManagedAlwaysOnAllowCaptiveWebSheetValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.AllowAllCaptiveNetworkPlugins != nil {
		if err := validate.InList("AllowAllCaptiveNetworkPlugins", *p.AllowAllCaptiveNetworkPlugins, []VpnManagedAlwaysOnAllowAllCaptiveNetworkPlugins{VpnManagedAlwaysOnAllowAllCaptiveNetworkPluginsValue0, VpnManagedAlwaysOnAllowAllCaptiveNetworkPluginsValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	for i := range p.AllowedCaptiveNetworkPlugins {
		if err := p.AllowedCaptiveNetworkPlugins[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AllowedCaptiveNetworkPlugins", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedTransparentProxyOnDemandRulesElementActionParameter) Validate() error {
	var errs []error
	if p.Domains == nil {
		errs = append(errs, validate.Required("Domains"))
	}
	if err := validate.InList("DomainAction", p.DomainAction, []VpnManagedTransparentProxyOnDemandRulesElementActionParameterDomainAction{VpnManagedTransparentProxyOnDemandRulesElementActionParameterDomainActionConnectIfNeeded, VpnManagedTransparentProxyOnDemandRulesElementActionParameterDomainActionNeverConnect}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedTransparentProxyOnDemandRulesElement) Validate() error {
	var errs []error
	if err := validate.InList("Action", p.Action, []VpnManagedTransparentProxyOnDemandRulesElementAction{VpnManagedTransparentProxyOnDemandRulesElementActionAllow, VpnManagedTransparentProxyOnDemandRulesElementActionConnect, VpnManagedTransparentProxyOnDemandRulesElementActionDisconnect, VpnManagedTransparentProxyOnDemandRulesElementActionEvaluateConnection, VpnManagedTransparentProxyOnDemandRulesElementActionIgnore}); err != nil {
		errs = append(errs, err)
	}
	for i := range p.ActionParameters {
		if err := p.ActionParameters[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ActionParameters", i, err))
		}
	}
	if p.InterfaceTypeMatch != nil {
		if err := validate.InList("InterfaceTypeMatch", *p.InterfaceTypeMatch, []VpnManagedTransparentProxyOnDemandRulesElementInterfaceTypeMatch{VpnManagedTransparentProxyOnDemandRulesElementInterfaceTypeMatchEthernet, VpnManagedTransparentProxyOnDemandRulesElementInterfaceTypeMatchWiFi, VpnManagedTransparentProxyOnDemandRulesElementInterfaceTypeMatchCellular}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *VpnManagedTransparentProxy) Validate() error {
	var errs []error
	if p.AuthenticationMethod != nil {
		if err := validate.InList("AuthenticationMethod", *p.AuthenticationMethod, []VpnManagedTransparentProxyAuthenticationMethod{VpnManagedTransparentProxyAuthenticationMethodPassword, VpnManagedTransparentProxyAuthenticationMethodCertificate, VpnManagedTransparentProxyAuthenticationMethodPasswordCertificate}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.DisconnectOnIdle != nil {
		if err := validate.InList("DisconnectOnIdle", *p.DisconnectOnIdle, []VpnManagedTransparentProxyDisconnectOnIdle{VpnManagedTransparentProxyDisconnectOnIdleValue0, VpnManagedTransparentProxyDisconnectOnIdleValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.EnforceRoutes != nil {
		if err := validate.InList("EnforceRoutes", *p.EnforceRoutes, []VpnManagedTransparentProxyEnforceRoutes{VpnManagedTransparentProxyEnforceRoutesValue0, VpnManagedTransparentProxyEnforceRoutesValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.OnDemandEnabled != nil {
		if err := validate.InList("OnDemandEnabled", *p.OnDemandEnabled, []VpnManagedTransparentProxyOnDemandEnabled{VpnManagedTransparentProxyOnDemandEnabledValue0, VpnManagedTransparentProxyOnDemandEnabledValue1}); err != nil {
			errs = append(errs, err)
		}
	}
	for i := range p.OnDemandRules {
		if err := p.OnDemandRules[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("OnDemandRules", i, err))
		}
	}
	if p.ProviderType != nil {
		if err := validate.InList("ProviderType", *p.ProviderType, []VpnManagedTransparentProxyProviderType{VpnManagedTransparentProxyProviderTypePacketTunnel, VpnManagedTransparentProxyProviderTypeAppProxy}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
