// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// VpnManagedAppmapping — App-to-App-Layer VPN Mapping.
// The payload that configures per-app VPN settings.
//
// Supported: macOS 10.9+.
type VpnManagedAppmapping struct {
	// The array of VPN mapping dictionaries.
	AppLayerVPNMapping []VpnManagedAppmappingAppLayerVPNMappingItem `plist:"AppLayerVPNMapping" json:"AppLayerVPNMapping"`
}

// VpnManagedAppmappingAppLayerVPNMappingItemMatchToolsItem is the MatchToolsItem dictionary.
// Specifies a per-app VPN rule to match network traffic that the app's spawned command-line tool
// generates.
type VpnManagedAppmappingAppLayerVPNMappingItemMatchToolsItem struct {
	// The code signature designated requirement of the command-line tool using the per-app VPN.
	DesignatedRequirement string `plist:"DesignatedRequirement" json:"DesignatedRequirement"`
	// The code signature signing identifier of the command-line tool using the per-app VPN.
	SigningIdentifier string `plist:"SigningIdentifier" json:"SigningIdentifier"`
	// The file-system path of the command-line tool using the per-app VPN.
	Path *string `plist:"Path,omitempty" json:"Path,omitempty"`
}

// VpnManagedAppmappingAppLayerVPNMappingItem is the AppLayerVPNMappingItem dictionary.
// A dictionary defining a per-app VPN relationship.
type VpnManagedAppmappingAppLayerVPNMappingItem struct {
	// The bundle identifier of the app using the per-app VPN.
	Identifier string `plist:"Identifier" json:"Identifier"`
	// The identifier of the per-app VPN payload, which defines the per-app VPN that the app uses. See
	// the `VPNUUID` key of the `AppLayerVPN` payload.
	VPNUUID string `plist:"VPNUUID" json:"VPNUUID"`
	// The code signature designated requirement of the app using the per-app VPN.
	DesignatedRequirement string `plist:"DesignatedRequirement" json:"DesignatedRequirement"`
	// The code signature signing identifier of the app using the per-app VPN.
	SigningIdentifier string `plist:"SigningIdentifier" json:"SigningIdentifier"`
	// The file-system path of the executable using the per-app VPN.
	Path *string `plist:"Path,omitempty" json:"Path,omitempty"`
	// An array of dictionaries. Each dictionary specifies a per-app VPN rule. Use this property to
	// restrict this per-app VPN rule to only match the app's spawned _helper tool_ network traffic.
	MatchTools []VpnManagedAppmappingAppLayerVPNMappingItemMatchToolsItem `plist:"MatchTools,omitempty" json:"MatchTools,omitempty"`
}
