// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// WebClipManaged — Web Clip.
// The profile that configures web clips on the device.
//
// Supported: iOS 4.0+, macOS 10.7+.
type WebClipManaged struct {
	// If `true`, the system prevents SpringBoard from adding shine to the icon.
	//
	// Default: false.
	Precomposed *bool `plist:"Precomposed,omitempty" json:"Precomposed,omitempty"`
	// If `true`, the system launches the web clip as a full-screen web app.
	//
	// Default: false.
	FullScreen *bool `plist:"FullScreen,omitempty" json:"FullScreen,omitempty"`
	// The URL of the web clip.
	URL string `plist:"URL" json:"URL"`
	// The PNG icon to show on the Home Screen. If not set, the system displays a white square. For
	// best results, provide a square image that's no larger than 400 x 400 pixels and less than 1 MB
	// when uncompressed. The graphics file is automatically scaled and cropped to fit, if necessary,
	// and converted to PNG format. Web clip icons are 144 x 144 pixels for iPad devices with a Retina
	// display, and 114 x 114 pixels for iPhone devices. To prevent the device from adding a shine to
	// the image, set `Precomposed` to `true`.
	Icon []byte `plist:"Icon,omitempty" json:"Icon,omitempty"`
	// If `true`, the system enables removing the web clip.
	//
	// Default: true.
	IsRemovable *bool `plist:"IsRemovable,omitempty" json:"IsRemovable,omitempty"`
	// The name of the web clip that the system displays on the Home Screen.
	Label string `plist:"Label" json:"Label"`
	// If `true`, a full screen web clip can navigate to an external web site without showing Safari
	// UI. Otherwise, Safari UI appears when navigating away from the web clip's URL. This key has no
	// effect when `FullScreen` is `false`. Available in iOS 14 and later.
	//
	// Default: false.
	IgnoreManifestScope *bool `plist:"IgnoreManifestScope,omitempty" json:"IgnoreManifestScope,omitempty"`
	// The application bundle identifier of the application that opens the URL. To use this property,
	// install the profile through MDM. Available in iOS 14 and later.
	TargetApplicationBundleIdentifier *string `plist:"TargetApplicationBundleIdentifier,omitempty" json:"TargetApplicationBundleIdentifier,omitempty"`
}
