// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// WebcontentFilterFilterType — allowed values for WebcontentFilter.FilterType.
type WebcontentFilterFilterType string

// WebcontentFilterFilterType allowed values.
const (
	WebcontentFilterFilterTypeBuiltIn WebcontentFilterFilterType = "BuiltIn"
	WebcontentFilterFilterTypePlugin  WebcontentFilterFilterType = "Plugin"
)

// String returns the WebcontentFilterFilterType value as a plain string.
func (e WebcontentFilterFilterType) String() string { return string(e) }

// WebcontentFilterFilterGrade — allowed values for WebcontentFilter.FilterGrade.
type WebcontentFilterFilterGrade string

// WebcontentFilterFilterGrade allowed values.
const (
	WebcontentFilterFilterGradeFirewall  WebcontentFilterFilterGrade = "firewall"
	WebcontentFilterFilterGradeInspector WebcontentFilterFilterGrade = "inspector"
)

// String returns the WebcontentFilterFilterGrade value as a plain string.
func (e WebcontentFilterFilterGrade) String() string { return string(e) }
