// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// WebcontentFilter — Web Content Filter.
// The payload that configures web content filters.
//
// Supported: iOS 7.0+, macOS 10.15+, visionOS 1.1+.
type WebcontentFilter struct {
	// The type of filter, built-in or plug-in. In macOS, the system only supports the plug-in value.
	//
	// Default: BuiltIn.
	FilterType *WebcontentFilterFilterType `plist:"FilterType,omitempty" json:"FilterType,omitempty"`
	// If `true`, this payload enforces a policy which requires retention of browsing history. This
	// causes Safari to disable clearing of browsing history, and prevents the use of private browsing
	// mode because that mode doesn't keep browsing history.
	//
	// Default: true.
	SafariHistoryRetentionEnabled *bool `plist:"SafariHistoryRetentionEnabled,omitempty" json:"SafariHistoryRetentionEnabled,omitempty"`
	// If `true`, the system enables automatic filtering. Use when `FilterType` is `BuiltIn`.
	//
	// Default: false.
	AutoFilterEnabled *bool `plist:"AutoFilterEnabled,omitempty" json:"AutoFilterEnabled,omitempty"`
	// An array or URLs that are accessible whether or not the automatic filter allows access. Use when
	// `FilterType` is `BuiltIn`. Requires that `AutoFilterEnabled` is `true`.
	PermittedURLs []string `plist:"PermittedURLs,omitempty" json:"PermittedURLs,omitempty"`
	// Use `DenyListURLs` instead.
	BlacklistedURLs []string `plist:"BlacklistedURLs,omitempty" json:"BlacklistedURLs,omitempty"`
	// An array of URLs that are inaccessible. Use when `FilterType` is `BuiltIn`. Limit the number of
	// these URLs to no more than 500.
	DenyListURLs []string `plist:"DenyListURLs,omitempty" json:"DenyListURLs,omitempty"`
	// If `true`, the device hides the `DenyListURLs` item in the profiles that display in Settings >
	// General > VPN & Device Management.
	//
	// Default: false.
	HideDenyListURLs *bool `plist:"HideDenyListURLs,omitempty" json:"HideDenyListURLs,omitempty"`
	// Use `AllowListBookmarks` instead.
	WhitelistedBookmarks []WebcontentFilterWhitelistedBookmarksItem `plist:"WhitelistedBookmarks,omitempty" json:"WhitelistedBookmarks,omitempty"`
	// An array of dictionaries that define the pages that the user can bookmark or visit. Use when
	// `FilterType` is `BuiltIn`.
	AllowListBookmarks []WebcontentFilterAllowListBookmarksItem `plist:"AllowListBookmarks,omitempty" json:"AllowListBookmarks,omitempty"`
	// The display name for this filtering configuration. Required when `FilterType` is `Plugin`.
	UserDefinedName *string `plist:"UserDefinedName,omitempty" json:"UserDefinedName,omitempty"`
	// The bundle ID of the plug-in that provides filtering service. Required when `FilterType` is
	// `Plugin`. Otherwise, it ignores this value. Consult your filtering solution vendor to determine
	// what to specify for this value. Required when `FilterType` is `Plugin`.
	PluginBundleID *string `plist:"PluginBundleID,omitempty" json:"PluginBundleID,omitempty"`
	// The server address, which may be the IP address, hostname, or URL. Use when `FilterType` is
	// `Plugin`.
	ServerAddress *string `plist:"ServerAddress,omitempty" json:"ServerAddress,omitempty"`
	// The user name for the service. Use when `FilterType` is `Plugin`.
	UserName *string `plist:"UserName,omitempty" json:"UserName,omitempty"`
	// The password for the service. Use when `FilterType` is `Plugin`.
	Password *string `plist:"Password,omitempty" json:"Password,omitempty"`
	// The UUID of the certificate payload within the same profile that the system uses to authenticate
	// the user. Use when `FilterType` is `Plugin`.
	PayloadCertificateUUID *string `plist:"PayloadCertificateUUID,omitempty" json:"PayloadCertificateUUID,omitempty"`
	// The organization string to pass to the third-party plug-in. Use when `FilterType` is `Plugin`.
	Organization *string `plist:"Organization,omitempty" json:"Organization,omitempty"`
	// The custom dictionary that the filtering service plug-in needs. Use when `FilterType` is
	// `Plugin`.
	VendorConfig *WebcontentFilterVendorConfig `plist:"VendorConfig,omitempty" json:"VendorConfig,omitempty"`
	// If `true`, the system enables filtering WebKit traffic. Use when `FilterType` is `Plugin`.
	//
	// Default: false.
	FilterBrowsers *bool `plist:"FilterBrowsers,omitempty" json:"FilterBrowsers,omitempty"`
	// If `true`, enables the filtering of socket traffic. Use when `FilterType` is `Plugin`.
	//
	// Default: false.
	FilterSockets *bool `plist:"FilterSockets,omitempty" json:"FilterSockets,omitempty"`
	// The designated requirement string that the system embeds in the code signature of the filter
	// data provider system extension. This string identifies the filter data provider when the filter
	// starts running. Required if `FilterSockets` is `true`.
	FilterDataProviderDesignatedRequirement *string `plist:"FilterDataProviderDesignatedRequirement,omitempty" json:"FilterDataProviderDesignatedRequirement,omitempty"`
	// The bundle identifier string of the filter data provider system extension. This string
	// identifies the filter data provider when the filter starts running. Required if `FilterSockets`
	// is `true`.
	FilterDataProviderBundleIdentifier *string `plist:"FilterDataProviderBundleIdentifier,omitempty" json:"FilterDataProviderBundleIdentifier,omitempty"`
	// If `true` and `FilterType` is `Plugin`, the system enables filtering network packets. Use when
	// `FilterType` is `Plugin`.
	//
	// Default: false.
	FilterPackets *bool `plist:"FilterPackets,omitempty" json:"FilterPackets,omitempty"`
	// The designated requirement string that the system embeds in the code signature of the filter
	// packet provider system extension. This string identifies the filter packet provider when the
	// filter starts running. Required if `FilterPackets` is `true`.
	FilterPacketProviderDesignatedRequirement *string `plist:"FilterPacketProviderDesignatedRequirement,omitempty" json:"FilterPacketProviderDesignatedRequirement,omitempty"`
	// The bundle identifier string of the filter packet provider system extension. This string
	// identifies the filter packet provider when the filter starts running. Required if
	// `FilterPackets` is `true`.
	FilterPacketProviderBundleIdentifier *string `plist:"FilterPacketProviderBundleIdentifier,omitempty" json:"FilterPacketProviderBundleIdentifier,omitempty"`
	// The system uses this value to derive the relative order of content filters. Filters with a grade
	// of `firewall` see network traffic before filters with a grade of `inspector`. However, the
	// system doesn't define the order of filters within a grade.
	//
	// Default: firewall.
	FilterGrade *WebcontentFilterFilterGrade `plist:"FilterGrade,omitempty" json:"FilterGrade,omitempty"`
	// A globally unique identifier for this content filter configuration. The content filter processes
	// network traffic for managed apps with the same `ContentFilterUUID` in their app attributes. Use
	// when `FilterType` is `Plugin`.This key must be present for unsupervised devices and user
	// enrollment.
	ContentFilterUUID *string `plist:"ContentFilterUUID,omitempty" json:"ContentFilterUUID,omitempty"`
	// If `true`, the system filters URL requests. Use when `FilterType` is `Plugin`. Available in iOS
	// 26 and macOS 26, and later.
	//
	// Default: false.
	FilterURLs *bool `plist:"FilterURLs,omitempty" json:"FilterURLs,omitempty"`
	// A dictionary containing URL filter parameters. Required when `FilterURLs` is `true`. Available
	// in iOS 26 and macOS 26 and later.
	URLFilterParameters *WebcontentFilterURLFilterParameters `plist:"URLFilterParameters,omitempty" json:"URLFilterParameters,omitempty"`
}

// WebcontentFilterWhitelistedBookmarksItem is the WhitelistedBookmarksItem dictionary.
type WebcontentFilterWhitelistedBookmarksItem struct {
	// The URL of the bookmark in the allow list.
	URL string `plist:"URL" json:"URL"`
	// The title of the bookmark.
	Title string `plist:"Title" json:"Title"`
}

// WebcontentFilterAllowListBookmarksItem is the AllowListBookmarksItem dictionary.
type WebcontentFilterAllowListBookmarksItem struct {
	// The URL of the bookmark in the allow list.
	URL string `plist:"URL" json:"URL"`
	// The title of the bookmark.
	Title string `plist:"Title" json:"Title"`
}

// WebcontentFilterVendorConfig is the VendorConfig dictionary.
// The custom dictionary that the filtering service plug-in needs. Use when `FilterType` is
// `Plugin`.
type WebcontentFilterVendorConfig struct {
	// The custom key/value pairs for the filtering service.
	ANY any `plist:"ANY" json:"ANY"`
}

// WebcontentFilterURLFilterParameters is the URLFilterParameters dictionary.
// A dictionary containing URL filter parameters. Required when `FilterURLs` is `true`. Available
// in iOS 26 and macOS 26 and later.
type WebcontentFilterURLFilterParameters struct {
	// The designated requirement string in the code signature of the URL filter control provider app
	// extension. The system uses this string to identify the URL filter control provider when the
	// filter starts running. Required in macOS.
	URLFilterControlProviderDesignatedRequirement *string `plist:"URLFilterControlProviderDesignatedRequirement,omitempty" json:"URLFilterControlProviderDesignatedRequirement,omitempty"`
	// The bundle identifier string of the URL filter control provider app extension. The system uses
	// this string to identify the URL filter control provider when the filter starts running.
	URLFilterControlProviderBundleIdentifier string `plist:"URLFilterControlProviderBundleIdentifier" json:"URLFilterControlProviderBundleIdentifier"`
	// The URL containing the domain name of the private information retrieval server.
	PIRServerURL string `plist:"PIRServerURL" json:"PIRServerURL"`
	// The URL containing the domain name of Privacy Pass Issuer.
	PIRPrivacyPassIssuerURL string `plist:"PIRPrivacyPassIssuerURL" json:"PIRPrivacyPassIssuerURL"`
	// The per-user authentication token string, which is an HTTP bearer token for the person using
	// your app. The system uses this token to attest that it is a valid user when requesting anonymous
	// authentication tokens for PIR exchanges.
	PIRAuthenticationToken string `plist:"PIRAuthenticationToken" json:"PIRAuthenticationToken"`
	// If `true`, the system blocks URLs if the filter is enabled, but it fails to make any filtering
	// decision; for example, if there's a communication failure with the PIR server. If `false`, the
	// system allows URLs if the filter is enabled, but it fails to make any filtering decision.
	//
	// Default: false.
	URLFilterFailClosed *bool `plist:"URLFilterFailClosed,omitempty" json:"URLFilterFailClosed,omitempty"`
	// The time interval in seconds that the system uses to periodically run the
	// `NEURLFilterControlProvider` app extension. The default value is 86400 seconds (1 day). The
	// minimum allowed value is 2700 seconds (45 minutes). The system allows
	// `NEURLFilterControlProvider` implementations to download prefilter Bloom filter data onto the
	// device periodically at the specified interval. Implementations need to allow for a slight
	// difference between the scheduled time and the actual runtime of the task, due to the scheduling
	// mechanism on the system.
	//
	// Default: 86400.
	URLPrefilterFetchFrequency *int64 `plist:"URLPrefilterFetchFrequency,omitempty" json:"URLPrefilterFetchFrequency,omitempty"`
}
