// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package profiles

// WifiManaged — Wi-Fi.
// The payload that configures Wi-Fi settings.
//
// Supported: iOS 4.0+, macOS 10.7+, tvOS 9.0+, visionOS 1.0+, watchOS 3.2+.
type WifiManaged struct {
	// If `true`, the device joins the network automatically.
	//
	// Default: true.
	AutoJoin *bool `plist:"AutoJoin,omitempty" json:"AutoJoin,omitempty"`
	// The SSID of the Wi-Fi network to use. In iOS 7.0 and later, the SSID is optional if a value
	// exists for `DomainName` value.
	SSIDSTR *string `plist:"SSID_STR,omitempty" json:"SSID_STR,omitempty"`
	// If `true`, defines this network as hidden.
	//
	// Default: false.
	HIDDENNETWORK *bool `plist:"HIDDEN_NETWORK,omitempty" json:"HIDDEN_NETWORK,omitempty"`
	// The proxy type, if any, to use. If you choose the manual proxy type, you need the proxy server
	// address, including its port and optionally a user name and password into the proxy server. If
	// you choose the auto proxy type, you can enter a proxy autoconfiguration (PAC) URL.
	//
	// Default: None.
	ProxyType *WifiManagedProxyType `plist:"ProxyType,omitempty" json:"ProxyType,omitempty"`
	// The encryption type for the network.
	//
	// Default: Any.
	EncryptionType *WifiManagedEncryptionType `plist:"EncryptionType,omitempty" json:"EncryptionType,omitempty"`
	// The password for the access point.
	Password *string `plist:"Password,omitempty" json:"Password,omitempty"`
	// The UUID of the certificate payload within the same profile to use for the client credential.
	PayloadCertificateUUID *string `plist:"PayloadCertificateUUID,omitempty" json:"PayloadCertificateUUID,omitempty"`
	// The enterprise network configuration.
	EAPClientConfiguration *WifiManagedEAPClientConfiguration `plist:"EAPClientConfiguration,omitempty" json:"EAPClientConfiguration,omitempty"`
	// The operator name to display when connected to this network. Used only with Wi-Fi Hotspot 2.0
	// access points.
	DisplayedOperatorName *string `plist:"DisplayedOperatorName,omitempty" json:"DisplayedOperatorName,omitempty"`
	// The primary domain of the tunnel.
	DomainName *string `plist:"DomainName,omitempty" json:"DomainName,omitempty"`
	// An array of Roaming Consortium Organization Identifiers used for Wi-Fi Hotspot 2.0 negotiation.
	RoamingConsortiumOIs []string `plist:"RoamingConsortiumOIs,omitempty" json:"RoamingConsortiumOIs,omitempty"`
	// If `true`, allows connection to roaming service providers.
	//
	// Default: false.
	ServiceProviderRoamingEnabled *bool `plist:"ServiceProviderRoamingEnabled,omitempty" json:"ServiceProviderRoamingEnabled,omitempty"`
	// If `true`, the device treats the network as a hotspot.
	//
	// Default: false.
	IsHotspot *bool `plist:"IsHotspot,omitempty" json:"IsHotspot,omitempty"`
	// The HESSID used for Wi-Fi Hotspot 2.0 negotiation.
	HESSID *string `plist:"HESSID,omitempty" json:"HESSID,omitempty"`
	// An array of Network Access Identifier Realm names used for Wi-Fi Hotspot 2.0 negotiation.
	NAIRealmNames []string `plist:"NAIRealmNames,omitempty" json:"NAIRealmNames,omitempty"`
	// An array of Mobile Country Code/Mobile Network Code (MCC/MNC) pairs used for Wi-Fi Hotspot 2.0
	// negotiation. Each string must contain exactly six digits.
	MCCAndMNCs []string `plist:"MCCAndMNCs,omitempty" json:"MCCAndMNCs,omitempty"`
	// If `true`, the system bypasses Captive Network detection when the device connects to the
	// network.
	//
	// Default: false.
	CaptiveBypass *bool `plist:"CaptiveBypass,omitempty" json:"CaptiveBypass,omitempty"`
	// A dictionary that contains the list of apps that the system allows to benefit from L2 and L3
	// marking. When this dictionary isn't present, the system allows all apps to use L2 and L3 marking
	// when the Wi-Fi network supports Cisco QoS fast lane.
	QoSMarkingPolicy *WifiManagedQoSMarkingPolicy `plist:"QoSMarkingPolicy,omitempty" json:"QoSMarkingPolicy,omitempty"`
	// An array of strings that contain the type of connection mode to attach.
	SetupModes []string `plist:"SetupModes,omitempty" json:"SetupModes,omitempty"`
	// If `true`, enables IPv6 on this interface.
	//
	// Default: true.
	EnableIPv6 *bool `plist:"EnableIPv6,omitempty" json:"EnableIPv6,omitempty"`
	// If `true`, allows for two-factor authentication for EAP-TTLS, PEAP, or EAP-FAST. If `false`,
	// allows for zero-factor authentication for EAP-TLS.
	//
	// Default: false.
	TLSCertificateRequired *bool `plist:"TLSCertificateRequired,omitempty" json:"TLSCertificateRequired,omitempty"`
	// The proxy server's network address.
	ProxyServer *string `plist:"ProxyServer,omitempty" json:"ProxyServer,omitempty"`
	// The proxy server's port number.
	ProxyServerPort *int64 `plist:"ProxyServerPort,omitempty" json:"ProxyServerPort,omitempty"`
	// The user name used to authenticate to the proxy server.
	ProxyUsername *string `plist:"ProxyUsername,omitempty" json:"ProxyUsername,omitempty"`
	// The password used to authenticate to the proxy server.
	ProxyPassword *string `plist:"ProxyPassword,omitempty" json:"ProxyPassword,omitempty"`
	// The URL of the PAC file that defines the proxy configuration.
	ProxyPACURL *string `plist:"ProxyPACURL,omitempty" json:"ProxyPACURL,omitempty"`
	// If `true`, allows connecting directly to the destination if the PAC file is unreachable.
	//
	// Default: false.
	ProxyPACFallbackAllowed *bool `plist:"ProxyPACFallbackAllowed,omitempty" json:"ProxyPACFallbackAllowed,omitempty"`
	// If `true,` disables MAC address randomization for a Wi-Fi network while associated with that
	// network. This feature also shows a privacy warning in Settings indicating that the network has
	// reduced privacy protections.
	//
	// Default: false.
	DisableAssociationMACRandomization *bool `plist:"DisableAssociationMACRandomization,omitempty" json:"DisableAssociationMACRandomization,omitempty"`
	// If `true`, the device makes this network available for joining before the device is unlocked for
	// the first time following a reboot, on a device configured for return to service. Any network
	// credentials are placed into Class D storage within the keychain, and information about the
	// network is stored on disk in Class D.
	//
	// Default: false.
	AllowJoinBeforeFirstUnlock *bool `plist:"AllowJoinBeforeFirstUnlock,omitempty" json:"AllowJoinBeforeFirstUnlock,omitempty"`
}

// WifiManagedEAPClientConfiguration is the EAPClientConfiguration dictionary.
// The enterprise network configuration.
type WifiManagedEAPClientConfiguration struct {
	// The EAP types that the system accepts. Allowed values:
	AcceptEAPTypes []int64 `plist:"AcceptEAPTypes" json:"AcceptEAPTypes"`
	// The user name for the account. If you don't specify a value, the system prompts the user during
	// login.
	UserName *string `plist:"UserName,omitempty" json:"UserName,omitempty"`
	// The user's password. If you don't specify a value, the system prompts the user during login.
	UserPassword *string `plist:"UserPassword,omitempty" json:"UserPassword,omitempty"`
	// An array of the UUID of each certificate payload in the same profile to trust for
	// authentication. Use this key to prevent the device from asking the user whether to trust the
	// listed certificates. Dynamic trust (the certificate dialogue) is in a disabled state if you
	// specify this property without also enabling 'TLSAllowTrustExceptions'.
	PayloadCertificateAnchorUUID []string `plist:"PayloadCertificateAnchorUUID,omitempty" json:"PayloadCertificateAnchorUUID,omitempty"`
	// An array of trusted certificates. Each entry in the array must contain certificate data that
	// represents an anchor certificate used for verifying the server certificate.
	TLSTrustedCertificates []string `plist:"TLSTrustedCertificates,omitempty" json:"TLSTrustedCertificates,omitempty"`
	// The list of accepted server certificate common names. If a server presents a certificate that
	// isn't in this list, the system doesn't trust it.
	TLSTrustedServerNames []string `plist:"TLSTrustedServerNames,omitempty" json:"TLSTrustedServerNames,omitempty"`
	// If 'true', allows a dynamic trust decision by the user. The dynamic trust is the certificate
	// dialogue that appears when the system doesn't trust a certificate.
	//
	// Default: true.
	TLSAllowTrustExceptions *bool `plist:"TLSAllowTrustExceptions,omitempty" json:"TLSAllowTrustExceptions,omitempty"`
	// If 'true', allows for two-factor authentication for EAP-TTLS, PEAP, or EAP-FAST. If 'false',
	// allows for zero-factor authentication for EAP-TLS.
	//
	// Default: false.
	TLSCertificateIsRequired *bool `plist:"TLSCertificateIsRequired,omitempty" json:"TLSCertificateIsRequired,omitempty"`
	// The inner authentication that the TTLS module uses.
	//
	// Default: MSCHAPv2.
	TTLSInnerAuthentication *WifiManagedEAPClientConfigurationTTLSInnerAuthentication `plist:"TTLSInnerAuthentication,omitempty" json:"TTLSInnerAuthentication,omitempty"`
	// The minimum TLS version for EAP authentication.
	//
	// Default: 1.0.
	TLSMinimumVersion *WifiManagedEAPClientConfigurationTLSMinimumVersion `plist:"TLSMinimumVersion,omitempty" json:"TLSMinimumVersion,omitempty"`
	// The maximum TLS version for EAP authentication.
	//
	// Default: 1.2.
	TLSMaximumVersion *WifiManagedEAPClientConfigurationTLSMaximumVersion `plist:"TLSMaximumVersion,omitempty" json:"TLSMaximumVersion,omitempty"`
	// A name that hides the user's true name. The user's actual name appears only inside the encrypted
	// tunnel. For example, you might set this to anonymous or anon, or anon@mycompany.net. It can
	// increase security because an attacker can't see the authenticating user's name in the clear.
	OuterIdentity *string `plist:"OuterIdentity,omitempty" json:"OuterIdentity,omitempty"`
	// If 'true', the device uses an existing PAC if it's present. Otherwise, the server must present
	// its identity using a certificate.
	//
	// Default: false.
	EAPFASTUsePAC *bool `plist:"EAPFASTUsePAC,omitempty" json:"EAPFASTUsePAC,omitempty"`
	// If 'true', allows PAC provisioning.
	//
	// Default: false.
	EAPFASTProvisionPAC *bool `plist:"EAPFASTProvisionPAC,omitempty" json:"EAPFASTProvisionPAC,omitempty"`
	// If 'true', provisions the device anonymously. Note that there are known machine-in-the-middle
	// attacks for anonymous provisioning.
	//
	// Default: false.
	EAPFASTProvisionPACAnonymously *bool `plist:"EAPFASTProvisionPACAnonymously,omitempty" json:"EAPFASTProvisionPACAnonymously,omitempty"`
	// The minimum number of RAND values to accept from the server.
	//
	// Default: 3.
	EAPSIMNumberOfRANDs *WifiManagedEAPClientConfigurationEAPSIMNumberOfRANDs `plist:"EAPSIMNumberOfRANDs,omitempty" json:"EAPSIMNumberOfRANDs,omitempty"`
	// Set this string to 'ActiveDirectory' to use the AD computer name and password credentials.
	SystemModeCredentialsSource *string `plist:"SystemModeCredentialsSource,omitempty" json:"SystemModeCredentialsSource,omitempty"`
	// If 'true', the system mode connection tries to use the Open Directory credentials.
	//
	// Default: false.
	SystemModeUseOpenDirectoryCredentials *bool `plist:"SystemModeUseOpenDirectoryCredentials,omitempty" json:"SystemModeUseOpenDirectoryCredentials,omitempty"`
	// If 'true', the user receives a prompt for a password each time they connect to the network.
	//
	// Default: false.
	OneTimeUserPassword *bool `plist:"OneTimeUserPassword,omitempty" json:"OneTimeUserPassword,omitempty"`
}

// WifiManagedQoSMarkingPolicy is the QoSMarkingPolicy dictionary.
// A dictionary that contains the list of apps that the system allows to benefit from L2 and L3
// marking. When this dictionary isn't present, the system allows all apps to use L2 and L3 marking
// when the Wi-Fi network supports Cisco QoS fast lane.
type WifiManagedQoSMarkingPolicy struct {
	// An array of app bundle identifiers that defines the allow list for L2 and L3 marking for traffic
	// that goes to the Wi-Fi network. If the array isn't present, but the `QoSMarkingPolicy` key is
	// present — even empty — no apps can use L2 and L3 marking.
	QoSMarkingAllowListAppIdentifiers []string `plist:"QoSMarkingAllowListAppIdentifiers,omitempty" json:"QoSMarkingAllowListAppIdentifiers,omitempty"`
	// Use `QoSMarkingAllowListAppIdentifiers` instead.
	QoSMarkingWhitelistedAppIdentifiers []string `plist:"QoSMarkingWhitelistedAppIdentifiers,omitempty" json:"QoSMarkingWhitelistedAppIdentifiers,omitempty"`
	// If `true`, adds audio and video traffic of built-in audio or video services, such as FaceTime
	// and Wi-Fi Calling, to the allow list for L2 and L3 marking for traffic that goes to the Wi-Fi
	// network.
	//
	// Default: true.
	QoSMarkingAppleAudioVideoCalls *bool `plist:"QoSMarkingAppleAudioVideoCalls,omitempty" json:"QoSMarkingAppleAudioVideoCalls,omitempty"`
	// If `true`, disables L3 marking and only uses L2 marking for traffic that goes to the Wi-Fi
	// network.
	//
	// Default: true.
	QoSMarkingEnabled *bool `plist:"QoSMarkingEnabled,omitempty" json:"QoSMarkingEnabled,omitempty"`
}
