// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package assets

// Useridentity — Asset:User Identity.
// The user-identity data.
//
// Supported: iOS 15.0+, macOS 13.0+, tvOS 16.0+, visionOS 1.1+, watchOS 10.0+.
type Useridentity struct {
	// The user's full name.
	FullName *string `plist:"FullName,omitempty" json:"FullName,omitempty"`
	// The email address of the user.
	EmailAddress *string `plist:"EmailAddress,omitempty" json:"EmailAddress,omitempty"`
}
