// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// AccessibilitySettings — Accessibility Settings.
// The declaration to configure accessibility settings.
//
// Supported: iOS 27.0+, macOS 27.0+, visionOS 27.0+.
type AccessibilitySettings struct {
	// If present, configures vision accessibility settings.
	Vision *AccessibilitySettingsVision `plist:"Vision,omitempty" json:"Vision,omitempty"`
}

// AccessibilitySettingsVision is the Vision dictionary.
// If present, configures vision accessibility settings.
type AccessibilitySettingsVision struct {
	// If `false`, disables the Accessibility Live Recognition Ask about Images and Surroundings
	// features.
	//
	// Default: true.
	AllowLiveRecognition *bool `plist:"AllowLiveRecognition,omitempty" json:"AllowLiveRecognition,omitempty"`
}
