// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// AccountMail — Account:Mail.
// The declaration to configure a Mail account.
//
// Supported: iOS 15.0+, macOS 13.0+, visionOS 1.1+.
type AccountMail struct {
	// The name that apps show to the user for this mail account. If not present, the system generates
	// a suitable default.
	VisibleName *string `plist:"VisibleName,omitempty" json:"VisibleName,omitempty"`
	// The identifier of an asset declaration that contains the user identity for this account. Set the
	// corresponding asset type to `UserIdentity`.
	//
	// Allowed asset types: com.apple.asset.useridentity.
	UserIdentityAssetReference *string `plist:"UserIdentityAssetReference,omitempty" json:"UserIdentityAssetReference,omitempty"`
	// The settings for the incoming mail server for this account.
	IncomingServer AccountMailIncomingServer `plist:"IncomingServer" json:"IncomingServer"`
	// The settings for the outgoing mail server for this account.
	OutgoingServer AccountMailOutgoingServer `plist:"OutgoingServer" json:"OutgoingServer"`
	// Settings for S/MIME.
	SMIME *AccountMailSMIME `plist:"SMIME,omitempty" json:"SMIME,omitempty"`
}

// AccountMailIncomingServer is the IncomingServer dictionary.
// The settings for the incoming mail server for this account.
type AccountMailIncomingServer struct {
	// The mail protocol this account uses.
	ServerType AccountMailIncomingServerServerType `plist:"ServerType" json:"ServerType"`
	// The host name for the incoming mail server.
	HostName string `plist:"HostName" json:"HostName"`
	// The port number for the incoming mail server.
	Port *int64 `plist:"Port,omitempty" json:"Port,omitempty"`
	// The authentication method for the incoming mail server.
	AuthenticationMethod AccountMailIncomingServerAuthenticationMethod `plist:"AuthenticationMethod" json:"AuthenticationMethod"`
	// The identifier of an asset declaration that contains the credentials for this account to
	// authenticate with an incoming mail server. The corresponding asset must be of type
	// `CredentialUserNameAndPassword`.
	//
	// Allowed asset types: com.apple.asset.credential.userpassword.
	AuthenticationCredentialsAssetReference *string `plist:"AuthenticationCredentialsAssetReference,omitempty" json:"AuthenticationCredentialsAssetReference,omitempty"`
	// The path prefix for the IMAP server. The system uses this only when `ServerType` is `IMAP`.
	IMAPPathPrefix *string `plist:"IMAPPathPrefix,omitempty" json:"IMAPPathPrefix,omitempty"`
}

// AccountMailOutgoingServer is the OutgoingServer dictionary.
// The settings for the outgoing mail server for this account.
type AccountMailOutgoingServer struct {
	// The host name for the outgoing mail server.
	HostName string `plist:"HostName" json:"HostName"`
	// The port number for the outgoing mail server.
	Port *int64 `plist:"Port,omitempty" json:"Port,omitempty"`
	// The authentication method for the outgoing mail server.
	AuthenticationMethod AccountMailOutgoingServerAuthenticationMethod `plist:"AuthenticationMethod" json:"AuthenticationMethod"`
	// The identifier of an asset declaration that contains the credentials for this account to
	// authenticate with an outgoing mail server. The corresponding asset must be of type
	// `CredentialUserNameAndPassword`.
	//
	// Allowed asset types: com.apple.asset.credential.userpassword.
	AuthenticationCredentialsAssetReference *string `plist:"AuthenticationCredentialsAssetReference,omitempty" json:"AuthenticationCredentialsAssetReference,omitempty"`
}

// AccountMailSMIMESigning is the Signing dictionary.
// Settings for S/MIME signing.
type AccountMailSMIMESigning struct {
	// If `true`, the system enables S/MIME signing.
	Enabled bool `plist:"Enabled" json:"Enabled"`
	// Specifies the identifier of an asset declaration containing the identity required for S/MIME
	// signing of messages sent from this account.
	//
	// Allowed asset types: com.apple.asset.credential.acme, com.apple.asset.credential.identity, com.apple.asset.credential.scep.
	IdentityAssetReference *string `plist:"IdentityAssetReference,omitempty" json:"IdentityAssetReference,omitempty"`
	// If `true`, the user can turn S/MIME signing on or off in Settings.
	//
	// Default: false.
	UserOverrideable *bool `plist:"UserOverrideable,omitempty" json:"UserOverrideable,omitempty"`
	// If `true`, the user can select an S/MIME signing identity in Settings.
	//
	// Default: false.
	IdentityUserOverrideable *bool `plist:"IdentityUserOverrideable,omitempty" json:"IdentityUserOverrideable,omitempty"`
}

// AccountMailSMIMEEncryption is the Encryption dictionary.
// Settings for S/MIME encryption.
type AccountMailSMIMEEncryption struct {
	// If `true`, the system enables S/MIME encryption by default, which the user can't override if
	// `PerMessageSwitchEnabled` is `false`.
	Enabled bool `plist:"Enabled" json:"Enabled"`
	// Specifies the identifier of an asset declaration containing the identity required for S/MIME
	// encryption. The system attaches the public certificate to outgoing mail to allow the user to
	// receive encrypted mail. When the user sends encrypted mail, the system uses the public
	// certificate to encrypt the copy of the mail in their Sent mailbox.
	//
	// Allowed asset types: com.apple.asset.credential.acme, com.apple.asset.credential.identity, com.apple.asset.credential.scep.
	IdentityAssetReference *string `plist:"IdentityAssetReference,omitempty" json:"IdentityAssetReference,omitempty"`
	// If `true`, the user can set the default value for S/MIME encryption to on or off in Settings.
	//
	// Default: false.
	UserOverrideable *bool `plist:"UserOverrideable,omitempty" json:"UserOverrideable,omitempty"`
	// If `true`, the user can select an S/MIME signing identity in Settings.
	//
	// Default: false.
	IdentityUserOverrideable *bool `plist:"IdentityUserOverrideable,omitempty" json:"IdentityUserOverrideable,omitempty"`
	// If `true`, the system enables the per-message encryption switch in the compose view.
	//
	// Default: false.
	PerMessageSwitchEnabled *bool `plist:"PerMessageSwitchEnabled,omitempty" json:"PerMessageSwitchEnabled,omitempty"`
}

// AccountMailSMIME is the SMIME dictionary.
// Settings for S/MIME.
type AccountMailSMIME struct {
	// Settings for S/MIME signing.
	Signing *AccountMailSMIMESigning `plist:"Signing,omitempty" json:"Signing,omitempty"`
	// Settings for S/MIME encryption.
	Encryption *AccountMailSMIMEEncryption `plist:"Encryption,omitempty" json:"Encryption,omitempty"`
}
