// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// DeclarationType returns the wire type identifier for AccountLdap.
func (AccountLdap) DeclarationType() string { return "com.apple.configuration.account.ldap" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AccountLdap) Validate() error {
	var errs []error
	for i := range p.SearchSettings {
		if err := p.SearchSettings[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("SearchSettings", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AccountLdapSearchSettingsItem) Validate() error {
	var errs []error
	if p.Scope != nil {
		if err := validate.InList("Scope", *p.Scope, []AccountLdapSearchSettingsItemScope{AccountLdapSearchSettingsItemScopeBase, AccountLdapSearchSettingsItemScopeOneLevel, AccountLdapSearchSettingsItemScopeSubtree}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
