// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// DeclarationType returns the wire type identifier for AccountCaldav.
func (AccountCaldav) DeclarationType() string { return "com.apple.configuration.account.caldav" }

// Validate checks the payload against Apple's spec. AccountCaldav has no
// constraints beyond its field types.
func (p *AccountCaldav) Validate() error { return nil }
