// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// DeclarationType returns the wire type identifier for AccountGoogle.
func (AccountGoogle) DeclarationType() string { return "com.apple.configuration.account.google" }

// Validate checks the payload against Apple's spec. AccountGoogle has no
// constraints beyond its field types.
func (p *AccountGoogle) Validate() error { return nil }
