// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// DeclarationType returns the wire type identifier for AccountCarddav.
func (AccountCarddav) DeclarationType() string { return "com.apple.configuration.account.carddav" }

// Validate checks the payload against Apple's spec. AccountCarddav has no
// constraints beyond its field types.
func (p *AccountCarddav) Validate() error { return nil }
