// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// AppManaged — App:Managed.
// The declaration to configure a managed app.
//
// Supported: iOS 17.2+, macOS 26.0+, visionOS 2.4+.
type AppManaged struct {
	// The App Store ID of the managed app that is downloaded from the App Store.
	AppStoreID *string `plist:"AppStoreID,omitempty" json:"AppStoreID,omitempty"`
	// The bundle ID of the managed app that is downloaded from the App Store.
	BundleID *string `plist:"BundleID,omitempty" json:"BundleID,omitempty"`
	// The URL of the manifest for the managed app that the device downloads from a web site. The
	// manifest is returned as a `ManifestURL` property list.
	ManifestURL *string `plist:"ManifestURL,omitempty" json:"ManifestURL,omitempty"`
	// A string that specifies the composed identifier of an existing app that needs to be managed. The
	// device uses this to take over management of an app installed by some other process, for example
	// installed manually by the user, or via a package configuration. If the app isn't present when
	// the device applies the configuration, the device takes over management of it when it does
	// install.
	AppComposedIdentifier *string `plist:"AppComposedIdentifier,omitempty" json:"AppComposedIdentifier,omitempty"`
	// If `true`, the device installs an iOS or iPadOS app that runs on a Mac with Apple Silicon. This
	// is only used when the app is an App Store app.
	//
	// Default: false.
	IOSApp *bool `plist:"iOSApp,omitempty" json:"iOSApp,omitempty"`
	// A dictionary that describes how and when to install the app.
	InstallBehavior *AppManagedInstallBehavior `plist:"InstallBehavior,omitempty" json:"InstallBehavior,omitempty"`
	// A dictionary that specifies how the device updates apps.
	UpdateBehavior *AppManagedUpdateBehavior `plist:"UpdateBehavior,omitempty" json:"UpdateBehavior,omitempty"`
	// If `true`, backups contain the app and its data.
	//
	// Default: true.
	IncludeInBackup *bool `plist:"IncludeInBackup,omitempty" json:"IncludeInBackup,omitempty"`
	// A dictionary of values to associate with the app.
	Attributes *AppManagedAttributes `plist:"Attributes,omitempty" json:"Attributes,omitempty"`
	// A dictionary of app config data and credentials.
	AppConfig *AppConfigDictionary `plist:"AppConfig,omitempty" json:"AppConfig,omitempty"`
	// A dictionary of extension config data and credentials.
	ExtensionConfigs *AppManagedExtensionConfigs `plist:"ExtensionConfigs,omitempty" json:"ExtensionConfigs,omitempty"`
	// The identifier of an asset declaration containing a reference to the app config data. The device
	// provides the app config data to the app using the MDMv1 behavior. The corresponding asset needs
	// to be of type `com.apple.asset.data`. The referenced data needs to be a property list file, and
	// the asset's "ContentType"
	//
	// Allowed asset types: com.apple.asset.data.
	LegacyAppConfigAssetReference *string `plist:"LegacyAppConfigAssetReference,omitempty" json:"LegacyAppConfigAssetReference,omitempty"`
}

// AppManagedInstallBehaviorLicense is the License dictionary.
// A dictionary that describes the app's license.
type AppManagedInstallBehaviorLicense struct {
	// The type of license that the app uses for installation through the App Store, which is one of
	// the following values:
	Assignment *AppManagedInstallBehaviorLicenseAssignment `plist:"Assignment,omitempty" json:"Assignment,omitempty"`
	// The type of VPP license that the app uses for installation through the App Store, which is one
	// of the following values:
	VPPType *AppManagedInstallBehaviorLicenseVPPType `plist:"VPPType,omitempty" json:"VPPType,omitempty"`
}

// AppManagedInstallBehavior is the InstallBehavior dictionary.
// A dictionary that describes how and when to install the app.
type AppManagedInstallBehavior struct {
	// A string that specifies if the app needs to remain on the device at all times or if the user can
	// freely install and remove it, which is one of the following values:
	//
	// Default: Optional.
	Install *AppManagedInstallBehaviorInstall `plist:"Install,omitempty" json:"Install,omitempty"`
	// A dictionary that describes the app's license.
	License *AppManagedInstallBehaviorLicense `plist:"License,omitempty" json:"License,omitempty"`
	// The App Store external version identifier (EVID) of the version of the app the device installs.
	// You can retrieve this value from the App Store. For more information, see `Apps and Books for
	// Organizations`. This key is ignored if the app isn't an App Store app.
	Version *int64 `plist:"Version,omitempty" json:"Version,omitempty"`
	// Indicates how the device uses a cellular network when it downloads the app for automatic install
	// or update operations:
	//
	// Default: StoreSettings.
	AllowDownloadsOverCellular *AppManagedInstallBehaviorAllowDownloadsOverCellular `plist:"AllowDownloadsOverCellular,omitempty" json:"AllowDownloadsOverCellular,omitempty"`
}

// AppManagedUpdateBehavior is the UpdateBehavior dictionary.
// A dictionary that specifies how the device updates apps.
type AppManagedUpdateBehavior struct {
	// Specifies whether the device automatically updates the app:
	AutomaticAppUpdates AppManagedUpdateBehaviorAutomaticAppUpdates `plist:"AutomaticAppUpdates" json:"AutomaticAppUpdates"`
}

// AppManagedAttributes is the Attributes dictionary.
// A dictionary of values to associate with the app.
type AppManagedAttributes struct {
	// An array of domain names to associate with the app.
	AssociatedDomains []string `plist:"AssociatedDomains,omitempty" json:"AssociatedDomains,omitempty"`
	// If `true`, the system enables direct downloads for the `AssociatedDomains`.
	//
	// Default: false.
	AssociatedDomainsEnableDirectDownloads *bool `plist:"AssociatedDomainsEnableDirectDownloads,omitempty" json:"AssociatedDomainsEnableDirectDownloads,omitempty"`
	// The cellular slice identifier, which can be the data network name (DNN) or app category. For
	// DNN, encode the value as "DNN:name", where "name" is the carrier-provided DNN name. For app
	// category, encode the value as "AppCategory:category", where "category" is a carrier-provided
	// string such as "Enterprise1".
	CellularSliceUUID *string `plist:"CellularSliceUUID,omitempty" json:"CellularSliceUUID,omitempty"`
	// The UUID of the content filter to associate with the app.
	ContentFilterUUID *string `plist:"ContentFilterUUID,omitempty" json:"ContentFilterUUID,omitempty"`
	// The UUID of the DNS proxy to associate with the app.
	DNSProxyUUID *string `plist:"DNSProxyUUID,omitempty" json:"DNSProxyUUID,omitempty"`
	// If `false`, the system prevents the user from hiding the app. It doesn't affect the user's
	// ability to leave it in the App Library, while removing it from the Home Screen.
	//
	// Default: true.
	Hideable *bool `plist:"Hideable,omitempty" json:"Hideable,omitempty"`
	// If `false`, the system prevents the user from locking the app. This also prevents the user from
	// hiding the app.
	//
	// Default: true.
	Lockable *bool `plist:"Lockable,omitempty" json:"Lockable,omitempty"`
	// The UUID of the relay to associate with the app.
	RelayUUID *string `plist:"RelayUUID,omitempty" json:"RelayUUID,omitempty"`
	// If `true`, the device automatically locks after every transaction that requires a customer's
	// card PIN. If `false`, the user can choose the behavior.
	//
	// Default: false.
	TapToPayScreenLock *bool `plist:"TapToPayScreenLock,omitempty" json:"TapToPayScreenLock,omitempty"`
	// The UUID of the VPN to associate with the app.
	VPNUUID *string `plist:"VPNUUID,omitempty" json:"VPNUUID,omitempty"`
}

// AppConfigDictionaryPasswordAppConfigItem is the PasswordAppConfigItem dictionary.
// A dictionary of values associated with a credential config.
type AppConfigDictionaryPasswordAppConfigItem struct {
	// The app or extension uses this identifier to fetch the corresponding password using the
	// `ManagedApp` framework. App developers define the values for these identifiers.
	Identifier string `plist:"Identifier" json:"Identifier"`
	// Specifies the identifier of an asset declaration containing a username and password. The
	// `ManagedApp` framework makes the password available to the app or extension. The `ManagedApp`
	// framework ignores the username.
	//
	// Allowed asset types: com.apple.asset.credential.userpassword.
	AssetReference string `plist:"AssetReference" json:"AssetReference"`
}

// AppConfigDictionaryIdentityAppConfigItem is the IdentityAppConfigItem dictionary.
// A dictionary of values associated with a credential config.
type AppConfigDictionaryIdentityAppConfigItem struct {
	// The app or extension uses this identifier to fetch the corresponding identity using the
	// `ManagedApp` framework. App developers define the values for these identifiers.
	Identifier string `plist:"Identifier" json:"Identifier"`
	// Specifies the identifier of an asset declaration containing an identity.
	//
	// Allowed asset types: com.apple.asset.credential.identity, com.apple.asset.credential.scep, com.apple.asset.credential.acme.
	AssetReference string `plist:"AssetReference" json:"AssetReference"`
}

// AppConfigDictionaryCertificateAppConfigItem is the CertificateAppConfigItem dictionary.
// A dictionary of values associated with a credential config.
type AppConfigDictionaryCertificateAppConfigItem struct {
	// The app or extension uses this identifier to fetch the corresponding certificate using the
	// `ManagedApp` framework. App developers define the values for these identifiers.
	Identifier string `plist:"Identifier" json:"Identifier"`
	// Specifies the identifier of an asset declaration containing a certificate.
	//
	// Allowed asset types: com.apple.asset.credential.certificate.
	AssetReference string `plist:"AssetReference" json:"AssetReference"`
}

// AppConfigDictionary is the AppConfig dictionary.
// A dictionary of app config data and credentials.
type AppConfigDictionary struct {
	// Specifies the identifier of an asset declaration containing a reference to the app or extension
	// config data. The corresponding asset needs to be of type `com.apple.asset.data`. The referenced
	// data needs to be a property list file, and the asset's "ContentType" value set to match the data
	// type.
	//
	// Allowed asset types: com.apple.asset.data.
	DataAssetReference *string `plist:"DataAssetReference,omitempty" json:"DataAssetReference,omitempty"`
	// Provides passwords to the managed app or extension. Each element in the array contains a
	// password asset reference and an associated identifier which the app or extension uses to look up
	// the password.
	Passwords []AppConfigDictionaryPasswordAppConfigItem `plist:"Passwords,omitempty" json:"Passwords,omitempty"`
	// Provides identities to the managed app or extension. Each element in the array contains an
	// identity asset reference and an associated identifier which the app or extension uses to look up
	// the identity.
	Identities []AppConfigDictionaryIdentityAppConfigItem `plist:"Identities,omitempty" json:"Identities,omitempty"`
	// Provides certificates to the managed app or extension. Each element in the array contains a
	// certificate asset reference and an associated identifier which the app or extension uses to look
	// up the certificate.
	Certificates []AppConfigDictionaryCertificateAppConfigItem `plist:"Certificates,omitempty" json:"Certificates,omitempty"`
}

// AppManagedExtensionConfigs is the ExtensionConfigs dictionary.
// A dictionary of extension config data and credentials.
type AppManagedExtensionConfigs struct {
	// A dictionary mapping extension composed identifiers to the extension config data and
	// credentials. The expected format is "Identifier (TeamIdentifier)".
	ANY *AppConfigDictionary `plist:"ANY,omitempty" json:"ANY,omitempty"`
}
