// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-sdk-appleservices/device_management/validate"
)

// DeclarationType returns the wire type identifier for AppSettings.
func (AppSettings) DeclarationType() string { return "com.apple.configuration.app.settings" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AppSettings) Validate() error {
	var errs []error
	if p.Allowed != nil {
		if err := p.Allowed.Validate(); err != nil {
			errs = append(errs, validate.Nested("Allowed", err))
		}
	}
	if p.Privacy != nil {
		if err := p.Privacy.Validate(); err != nil {
			errs = append(errs, validate.Nested("Privacy", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AppSettingsAllowedBinaryIdentifier) Validate() error {
	var errs []error
	if p.SigningState != nil {
		if err := validate.InList("SigningState", *p.SigningState, []AppSettingsAllowedBinaryIdentifierSigningState{AppSettingsAllowedBinaryIdentifierSigningStateAll, AppSettingsAllowedBinaryIdentifierSigningStateTestFlight, AppSettingsAllowedBinaryIdentifierSigningStateDeveloperID, AppSettingsAllowedBinaryIdentifierSigningStateEnterprise, AppSettingsAllowedBinaryIdentifierSigningStateAppStore, AppSettingsAllowedBinaryIdentifierSigningStateApple}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AppSettingsAllowed) Validate() error {
	var errs []error
	for i := range p.AllowedBinaries {
		if err := p.AllowedBinaries[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("AllowedBinaries", i, err))
		}
	}
	for i := range p.DeniedBinaries {
		if err := p.DeniedBinaries[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("DeniedBinaries", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AppDictionary) Validate() error {
	var errs []error
	if p.Accessibility != nil {
		if err := validate.InList("Accessibility", *p.Accessibility, []AppDictionaryAccessibility{AppDictionaryAccessibilityNone, AppDictionaryAccessibilityAllow}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.Bluetooth != nil {
		if err := validate.InList("Bluetooth", *p.Bluetooth, []AppDictionaryBluetooth{AppDictionaryBluetoothNone, AppDictionaryBluetoothAllow}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.Camera != nil {
		if err := validate.InList("Camera", *p.Camera, []AppDictionaryCamera{AppDictionaryCameraNone, AppDictionaryCameraAllow}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.Dictation != nil {
		if err := validate.InList("Dictation", *p.Dictation, []AppDictionaryDictation{AppDictionaryDictationNone, AppDictionaryDictationAllow}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.LocalNetwork != nil {
		if err := validate.InList("LocalNetwork", *p.LocalNetwork, []AppDictionaryLocalNetwork{AppDictionaryLocalNetworkNone, AppDictionaryLocalNetworkAllow}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.Location != nil {
		if err := validate.InList("Location", *p.Location, []AppDictionaryLocation{AppDictionaryLocationNone, AppDictionaryLocationWhileUsing, AppDictionaryLocationAlways}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.LocationAccuracy != nil {
		if err := validate.InList("LocationAccuracy", *p.LocationAccuracy, []AppDictionaryLocationAccuracy{AppDictionaryLocationAccuracyNone, AppDictionaryLocationAccuracyApproximate, AppDictionaryLocationAccuracyPrecise}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.Microphone != nil {
		if err := validate.InList("Microphone", *p.Microphone, []AppDictionaryMicrophone{AppDictionaryMicrophoneNone, AppDictionaryMicrophoneAllow}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AppSettingsPrivacyPermissionDefaults) Validate() error {
	var errs []error
	if p.ANY != nil {
		if err := p.ANY.Validate(); err != nil {
			errs = append(errs, validate.Nested("ANY", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *AppSettingsPrivacy) Validate() error {
	var errs []error
	if p.PermissionDefaults != nil {
		if err := p.PermissionDefaults.Validate(); err != nil {
			errs = append(errs, validate.Nested("PermissionDefaults", err))
		}
	}
	return errors.Join(errs...)
}
