// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// AppSettingsAllowedBinaryIdentifierSigningState — allowed values for AppSettingsAllowedBinaryIdentifier.SigningState.
type AppSettingsAllowedBinaryIdentifierSigningState string

// AppSettingsAllowedBinaryIdentifierSigningState allowed values.
const (
	AppSettingsAllowedBinaryIdentifierSigningStateAll         AppSettingsAllowedBinaryIdentifierSigningState = "All"
	AppSettingsAllowedBinaryIdentifierSigningStateTestFlight  AppSettingsAllowedBinaryIdentifierSigningState = "TestFlight"
	AppSettingsAllowedBinaryIdentifierSigningStateDeveloperID AppSettingsAllowedBinaryIdentifierSigningState = "DeveloperID"
	AppSettingsAllowedBinaryIdentifierSigningStateEnterprise  AppSettingsAllowedBinaryIdentifierSigningState = "Enterprise"
	AppSettingsAllowedBinaryIdentifierSigningStateAppStore    AppSettingsAllowedBinaryIdentifierSigningState = "AppStore"
	AppSettingsAllowedBinaryIdentifierSigningStateApple       AppSettingsAllowedBinaryIdentifierSigningState = "Apple"
)

// String returns the AppSettingsAllowedBinaryIdentifierSigningState value as a plain string.
func (e AppSettingsAllowedBinaryIdentifierSigningState) String() string { return string(e) }

// AppDictionaryAccessibility — allowed values for AppDictionary.Accessibility.
type AppDictionaryAccessibility string

// AppDictionaryAccessibility allowed values.
const (
	AppDictionaryAccessibilityNone  AppDictionaryAccessibility = "None"
	AppDictionaryAccessibilityAllow AppDictionaryAccessibility = "Allow"
)

// String returns the AppDictionaryAccessibility value as a plain string.
func (e AppDictionaryAccessibility) String() string { return string(e) }

// AppDictionaryBluetooth — allowed values for AppDictionary.Bluetooth.
type AppDictionaryBluetooth string

// AppDictionaryBluetooth allowed values.
const (
	AppDictionaryBluetoothNone  AppDictionaryBluetooth = "None"
	AppDictionaryBluetoothAllow AppDictionaryBluetooth = "Allow"
)

// String returns the AppDictionaryBluetooth value as a plain string.
func (e AppDictionaryBluetooth) String() string { return string(e) }

// AppDictionaryCamera — allowed values for AppDictionary.Camera.
type AppDictionaryCamera string

// AppDictionaryCamera allowed values.
const (
	AppDictionaryCameraNone  AppDictionaryCamera = "None"
	AppDictionaryCameraAllow AppDictionaryCamera = "Allow"
)

// String returns the AppDictionaryCamera value as a plain string.
func (e AppDictionaryCamera) String() string { return string(e) }

// AppDictionaryDictation — allowed values for AppDictionary.Dictation.
type AppDictionaryDictation string

// AppDictionaryDictation allowed values.
const (
	AppDictionaryDictationNone  AppDictionaryDictation = "None"
	AppDictionaryDictationAllow AppDictionaryDictation = "Allow"
)

// String returns the AppDictionaryDictation value as a plain string.
func (e AppDictionaryDictation) String() string { return string(e) }

// AppDictionaryLocalNetwork — allowed values for AppDictionary.LocalNetwork.
type AppDictionaryLocalNetwork string

// AppDictionaryLocalNetwork allowed values.
const (
	AppDictionaryLocalNetworkNone  AppDictionaryLocalNetwork = "None"
	AppDictionaryLocalNetworkAllow AppDictionaryLocalNetwork = "Allow"
)

// String returns the AppDictionaryLocalNetwork value as a plain string.
func (e AppDictionaryLocalNetwork) String() string { return string(e) }

// AppDictionaryLocation — allowed values for AppDictionary.Location.
type AppDictionaryLocation string

// AppDictionaryLocation allowed values.
const (
	AppDictionaryLocationNone       AppDictionaryLocation = "None"
	AppDictionaryLocationWhileUsing AppDictionaryLocation = "WhileUsing"
	AppDictionaryLocationAlways     AppDictionaryLocation = "Always"
)

// String returns the AppDictionaryLocation value as a plain string.
func (e AppDictionaryLocation) String() string { return string(e) }

// AppDictionaryLocationAccuracy — allowed values for AppDictionary.LocationAccuracy.
type AppDictionaryLocationAccuracy string

// AppDictionaryLocationAccuracy allowed values.
const (
	AppDictionaryLocationAccuracyNone        AppDictionaryLocationAccuracy = "None"
	AppDictionaryLocationAccuracyApproximate AppDictionaryLocationAccuracy = "Approximate"
	AppDictionaryLocationAccuracyPrecise     AppDictionaryLocationAccuracy = "Precise"
)

// String returns the AppDictionaryLocationAccuracy value as a plain string.
func (e AppDictionaryLocationAccuracy) String() string { return string(e) }

// AppDictionaryMicrophone — allowed values for AppDictionary.Microphone.
type AppDictionaryMicrophone string

// AppDictionaryMicrophone allowed values.
const (
	AppDictionaryMicrophoneNone  AppDictionaryMicrophone = "None"
	AppDictionaryMicrophoneAllow AppDictionaryMicrophone = "Allow"
)

// String returns the AppDictionaryMicrophone value as a plain string.
func (e AppDictionaryMicrophone) String() string { return string(e) }
