// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// ContentCacheSettings — Content Caching.
// The declaration to configure the Content Caching service.
//
// Supported: macOS 27.0+.
type ContentCacheSettings struct {
	// If `true`, the system purges content from the cache automatically when it needs disk space for
	// other apps when free disk space runs low on the computer. Set to `false` to maximize
	// effectiveness of Content Caching.
	//
	// Default: true.
	AllowCacheDelete *bool `plist:"AllowCacheDelete,omitempty" json:"AllowCacheDelete,omitempty"`
	// If `true`, the system caches the user's iCloud data. Changes to this value don't have an
	// immediate effect. Clients may take some time to react to changes.
	//
	// Default: true.
	AllowPersonalCaching *bool `plist:"AllowPersonalCaching,omitempty" json:"AllowPersonalCaching,omitempty"`
	// If `true`, the system caches non-iCloud content, such as apps and software updates. Changes to
	// this value don't have an immediate effect. Clients may take some time to react to changes.
	//
	// Default: true.
	AllowSharedCaching *bool `plist:"AllowSharedCaching,omitempty" json:"AllowSharedCaching,omitempty"`
	// If `true`, the system automatically activates the content cache when possible and prevents
	// disabling it. If `allowContentCaching` is `false`, `AutoActivation` is also `false`.
	//
	// Default: false.
	AutoActivation *bool `plist:"AutoActivation,omitempty" json:"AutoActivation,omitempty"`
	// If `true`, the system automatically enables Internet connection sharing when possible and
	// prevent disabling Internet connection sharing. `DenyTetheredCaching` overrides
	// `AutoEnableTetheredCaching`. Tethered caching requires Content Caching.
	//
	// Default: false.
	AutoEnableTetheredCaching *bool `plist:"AutoEnableTetheredCaching,omitempty" json:"AutoEnableTetheredCaching,omitempty"`
	// The maximum number of bytes of disk space to use for the content cache. Set to `0` for unlimited
	// disk space. Also serves as the upper bound to the `PersonalCacheLimit`.
	//
	// Default: 0.
	CacheLimit *int64 `plist:"CacheLimit,omitempty" json:"CacheLimit,omitempty"`
	// The path to the directory used to store cached content. Changing this setting manually doesn't
	// automatically move cached content from the old location to the new one. To move content
	// automatically, use the Sharing preference's Content Caching pane. The value must be (or end
	// with) `/Library/Application Support/Apple/AssetCache/Data`.
	//
	// Default: /Library/Application Support/Apple/AssetCache/Data.
	DataPath *string `plist:"DataPath,omitempty" json:"DataPath,omitempty"`
	// If `true`, the system disables Content Caching. This is the inverse of the `allowContentCaching`
	// restriction in MDM. It overrides the `AutoActivation` key. Use this key to prevent launching the
	// Content Caching service.
	//
	// Default: false.
	DenyActivation *bool `plist:"DenyActivation,omitempty" json:"DenyActivation,omitempty"`
	// If `true`, the system disables tethered caching.
	//
	// Default: false.
	DenyTetheredCaching *bool `plist:"DenyTetheredCaching,omitempty" json:"DenyTetheredCaching,omitempty"`
	// The time interval in seconds the system uses to update the `StatusContentCacheInfo` declarative
	// status item. The reporting interval can't be less than 60 (1 per minute) or larger than 86400 (1
	// per day), defaults to 0 (off)
	//
	// Default: 0.
	DeclarativeStatusInterval *int64 `plist:"DeclarativeStatusInterval,omitempty" json:"DeclarativeStatusInterval,omitempty"`
	// If `true`, Content Caching displays exceptional conditions (alerts) as system notifications in
	// the upper corner of the screen.
	//
	// Default: false.
	DisplayAlerts *bool `plist:"DisplayAlerts,omitempty" json:"DisplayAlerts,omitempty"`
	// If `true`, the system prevents the computer from sleeping as long as Content Caching is on
	// (System Preferences > Sharing > Content Caching is on). Customers who want Content Caching to be
	// as available as much as possible should turn this setting on.
	//
	// Default: false.
	KeepAwake *bool `plist:"KeepAwake,omitempty" json:"KeepAwake,omitempty"`
	// An array of dictionaries that describe a range of client IP addresses to serve.
	ListenRanges []ContentCacheSettingsRangesItem `plist:"ListenRanges,omitempty" json:"ListenRanges,omitempty"`
	// If `true`, the content cache provides content to the clients in the `ListenRanges`.
	//
	// Default: false.
	ListenRangesOnly *bool `plist:"ListenRangesOnly,omitempty" json:"ListenRangesOnly,omitempty"`
	// If `true`, the content cache provides content to the clients in the union of the `ListenRanges`,
	// `PeerListenRanges` and `Parents`.
	//
	// Default: true.
	ListenWithPeersAndParents *bool `plist:"ListenWithPeersAndParents,omitempty" json:"ListenWithPeersAndParents,omitempty"`
	// If `true`, the content cache offers content to clients only on the same immediate local network
	// only. The content cache offers no content to clients on other networks reachable by the content
	// cache. If `LocalSubnetsOnly` is `true`, the system ignores `ListenRanges`.
	//
	// Default: true.
	LocalSubnetsOnly *bool `plist:"LocalSubnetsOnly,omitempty" json:"LocalSubnetsOnly,omitempty"`
	// If `true`, the Content Cache logs the IP address and port number of the clients that request
	// content.
	//
	// Default: false.
	LogClientIdentity *bool `plist:"LogClientIdentity,omitempty" json:"LogClientIdentity,omitempty"`
	// An array of the local IP addresses of other content caches that this cache should download from
	// or upload to, instead of downloading from or uploading to Apple directly. The system ignores
	// invalid addresses and addresses of computers that aren't content caches. The system skips Parent
	// caches that become unavailable. If all parent content caches become unavailable, the content
	// cache downloads from or uploads to Apple directly, until a parent content cache becomes
	// available again.
	Parents []string `plist:"Parents,omitempty" json:"Parents,omitempty"`
	// The policy to implement when choosing among more than one configured parent content cache. With
	// every policy, the system skips parent caches that are temporarily unavailable. Allowed values:
	//
	// Default: round-robin.
	ParentSelectionPolicy *ContentCacheSettingsParentSelectionPolicy `plist:"ParentSelectionPolicy,omitempty" json:"ParentSelectionPolicy,omitempty"`
	// An array of dictionaries describing a range of peer IP addresses that the content cache uses to
	// filter its list of peers to query for content. The content cache only queries peers in
	// `PeerFilterRanges`. When `PeerFilterRanges` is an empty array, the content cache doesn't query
	// any peers.
	PeerFilterRanges []ContentCacheSettingsRangesItem `plist:"PeerFilterRanges,omitempty" json:"PeerFilterRanges,omitempty"`
	// An array of dictionaries describing a range of peer IP addresses the content cache responds to.
	// When `PeerListenRanges` is an empty array, the content cache responds with an error to all cache
	// queries.
	PeerListenRanges []ContentCacheSettingsRangesItem `plist:"PeerListenRanges,omitempty" json:"PeerListenRanges,omitempty"`
	// If `true`, the content cache only peers with other content caches on the same immediate local
	// network, rather than with content caches that use the same public IP address as the device. When
	// `PeerLocalSubnetsOnly` is `true`, it overrides the configuration of `PeerFilterRanges` and
	// `PeerListenRanges`. If the network changes, the local network peering restrictions update
	// appropriately. If `false`, the content cache defers to `PeerFilterRanges` and `PeerListenRanges`
	// for configuring the peering restrictions.
	//
	// Default: true.
	PeerLocalSubnetsOnly *bool `plist:"PeerLocalSubnetsOnly,omitempty" json:"PeerLocalSubnetsOnly,omitempty"`
	// The maximum number of bytes of disk space to use for the personal content cache. The content
	// cache limits the maximum value to the `CacheLimit` value. Set to `0` to use the overall
	// `CacheLimit`.
	//
	// Default: 0.
	PersonalCacheLimit *int64 `plist:"PersonalCacheLimit,omitempty" json:"PersonalCacheLimit,omitempty"`
	// The TCP port number on which the content cache accepts requests for uploads or downloads. Set to
	// `0` to pick a random, available port.
	//
	// Default: 0.
	Port *int64 `plist:"Port,omitempty" json:"Port,omitempty"`
	// An array of dictionaries describing a range of public IP addresses that the cloud servers should
	// use for matching clients to content caches.
	PublicRanges []ContentCacheSettingsRangesItem `plist:"PublicRanges,omitempty" json:"PublicRanges,omitempty"`
	// The target URL the system uses to send management statistics using an HTTP PUT request with a
	// json dictionary as the payload. If the URL is an https URL (recommended) the
	// `ManagementSecurityConfig` defines how the system secures the connection. The system sends the
	// management statistics report to the target URL at an interval set by the
	// `ManagementReportingInterval` value.
	ManagementStatusTarget *string `plist:"ManagementStatusTarget,omitempty" json:"ManagementStatusTarget,omitempty"`
	// If the `ManagementStatusTarget` is an https URL, the system uses this field to determine how the
	// connection is secured.
	//
	// Default: no-cert.
	ManagementSecurityConfig *ContentCacheSettingsManagementSecurityConfig `plist:"ManagementSecurityConfig,omitempty" json:"ManagementSecurityConfig,omitempty"`
	// The reporting interval in seconds the system uses when `ManagementStatusTarget` is present. The
	// reporting interval can't be less than 60 (1 per minute) or larger than 86400 (1 per day), and
	// defaults to 300 (1 per 5 min).
	//
	// Default: 300.
	ManagementReportingInterval *int64 `plist:"ManagementReportingInterval,omitempty" json:"ManagementReportingInterval,omitempty"`
	// The identifier of an asset declaration that contains the certificate the system uses to verify
	// the security of the status reporting https connection. Required when `ManagementSecurityConfig`
	// is set to `signedByCACert` or `specificServerCert`.
	//
	// Allowed asset types: com.apple.asset.credential.certificate.
	ManagementStatusCertificateReference *string `plist:"ManagementStatusCertificateReference,omitempty" json:"ManagementStatusCertificateReference,omitempty"`
}

// ContentCacheSettingsRangesItem is the RangesItem dictionary.
// A range of IP addresses to cache.
type ContentCacheSettingsRangesItem struct {
	// The IP address type.
	//
	// Default: IPv4.
	Type *ContentCacheSettingsRangesItemType `plist:"type,omitempty" json:"type,omitempty"`
	// The first IP address in the range.
	First string `plist:"first" json:"first"`
	// The last IP address in the range.
	Last string `plist:"last" json:"last"`
}
