// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// ContentCacheSettingsRangesItemType — allowed values for ContentCacheSettingsRangesItem.Type.
type ContentCacheSettingsRangesItemType string

// ContentCacheSettingsRangesItemType allowed values.
const (
	ContentCacheSettingsRangesItemTypeIPv4 ContentCacheSettingsRangesItemType = "IPv4"
	ContentCacheSettingsRangesItemTypeIPv6 ContentCacheSettingsRangesItemType = "IPv6"
)

// String returns the ContentCacheSettingsRangesItemType value as a plain string.
func (e ContentCacheSettingsRangesItemType) String() string { return string(e) }

// ContentCacheSettingsParentSelectionPolicy — allowed values for ContentCacheSettings.ParentSelectionPolicy.
type ContentCacheSettingsParentSelectionPolicy string

// ContentCacheSettingsParentSelectionPolicy allowed values.
const (
	ContentCacheSettingsParentSelectionPolicyFirstAvailable  ContentCacheSettingsParentSelectionPolicy = "first-available"
	ContentCacheSettingsParentSelectionPolicyUrlPathHash     ContentCacheSettingsParentSelectionPolicy = "url-path-hash"
	ContentCacheSettingsParentSelectionPolicyRandom          ContentCacheSettingsParentSelectionPolicy = "random"
	ContentCacheSettingsParentSelectionPolicyRoundRobin      ContentCacheSettingsParentSelectionPolicy = "round-robin"
	ContentCacheSettingsParentSelectionPolicyStickyAvailable ContentCacheSettingsParentSelectionPolicy = "sticky-available"
)

// String returns the ContentCacheSettingsParentSelectionPolicy value as a plain string.
func (e ContentCacheSettingsParentSelectionPolicy) String() string { return string(e) }

// ContentCacheSettingsManagementSecurityConfig — allowed values for ContentCacheSettings.ManagementSecurityConfig.
type ContentCacheSettingsManagementSecurityConfig string

// ContentCacheSettingsManagementSecurityConfig allowed values.
const (
	ContentCacheSettingsManagementSecurityConfigNoCert             ContentCacheSettingsManagementSecurityConfig = "no-cert"
	ContentCacheSettingsManagementSecurityConfigSignedByCACert     ContentCacheSettingsManagementSecurityConfig = "signedByCACert"
	ContentCacheSettingsManagementSecurityConfigSpecificServerCert ContentCacheSettingsManagementSecurityConfig = "specificServerCert"
)

// String returns the ContentCacheSettingsManagementSecurityConfig value as a plain string.
func (e ContentCacheSettingsManagementSecurityConfig) String() string { return string(e) }
