// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// DiskmanagementSettings — Disk Management:Settings.
// The declaration to configure disk management settings on the device.
//
// Supported: macOS 15.0+.
type DiskmanagementSettings struct {
	// The restrictions for the disk.
	Restrictions *DiskmanagementSettingsRestrictions `plist:"Restrictions,omitempty" json:"Restrictions,omitempty"`
}

// DiskmanagementSettingsRestrictions is the Restrictions dictionary.
// The restrictions for the disk.
type DiskmanagementSettingsRestrictions struct {
	// Specifies the mount policy for external storage:
	ExternalStorage *DiskmanagementSettingsRestrictionsExternalStorage `plist:"ExternalStorage,omitempty" json:"ExternalStorage,omitempty"`
	// Specifies the mount policy for network storage:
	NetworkStorage *DiskmanagementSettingsRestrictionsNetworkStorage `plist:"NetworkStorage,omitempty" json:"NetworkStorage,omitempty"`
}
