// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// DeclarationType returns the wire type identifier for IntelligenceSettings.
func (IntelligenceSettings) DeclarationType() string {
	return "com.apple.configuration.intelligence.settings"
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *IntelligenceSettings) Validate() error {
	var errs []error
	if p.Apps != nil {
		if err := p.Apps.Validate(); err != nil {
			errs = append(errs, validate.Nested("Apps", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. IntelligenceSettingsAppsMail has no
// constraints beyond its field types.
func (p *IntelligenceSettingsAppsMail) Validate() error { return nil }

// Validate checks the payload against Apple's spec. IntelligenceSettingsAppsNotes has no
// constraints beyond its field types.
func (p *IntelligenceSettingsAppsNotes) Validate() error { return nil }

// Validate checks the payload against Apple's spec. IntelligenceSettingsAppsSafari has no
// constraints beyond its field types.
func (p *IntelligenceSettingsAppsSafari) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *IntelligenceSettingsApps) Validate() error {
	var errs []error
	if p.Mail != nil {
		if err := p.Mail.Validate(); err != nil {
			errs = append(errs, validate.Nested("Mail", err))
		}
	}
	if p.Notes != nil {
		if err := p.Notes.Validate(); err != nil {
			errs = append(errs, validate.Nested("Notes", err))
		}
	}
	if p.Safari != nil {
		if err := p.Safari.Validate(); err != nil {
			errs = append(errs, validate.Nested("Safari", err))
		}
	}
	return errors.Join(errs...)
}
