// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// KeyboardSettings — Keyboard Settings.
// The declaration to configure keyboard settings.
//
// Supported: iOS 26.4+, macOS 26.4+.
type KeyboardSettings struct {
	// If `false`, disables auto-correction.
	//
	// Default: true.
	AllowAutoCorrection *bool `plist:"AllowAutoCorrection,omitempty" json:"AllowAutoCorrection,omitempty"`
	// If `false`, disables definition lookup.
	//
	// Default: true.
	AllowDefinitionLookup *bool `plist:"AllowDefinitionLookup,omitempty" json:"AllowDefinitionLookup,omitempty"`
	// If `false`, disables dictation.
	//
	// Default: true.
	AllowDictation *bool `plist:"AllowDictation,omitempty" json:"AllowDictation,omitempty"`
	// If `false`, disables keyboard suggestions that include math solutions. This key is also
	// supported by the math.settings configuration.
	//
	// Default: true.
	AllowMathKeyboardSuggestions *bool `plist:"AllowMathKeyboardSuggestions,omitempty" json:"AllowMathKeyboardSuggestions,omitempty"`
	// If `false`, disables predictive text.
	//
	// Default: true.
	AllowPredictiveText *bool `plist:"AllowPredictiveText,omitempty" json:"AllowPredictiveText,omitempty"`
	// If `false`, disables slide to type.
	//
	// Default: true.
	AllowSlideToType *bool `plist:"AllowSlideToType,omitempty" json:"AllowSlideToType,omitempty"`
	// If `false`, disables spell check.
	//
	// Default: true.
	AllowSpellCheck *bool `plist:"AllowSpellCheck,omitempty" json:"AllowSpellCheck,omitempty"`
	// If `false`, disables text replacement.
	//
	// Default: true.
	AllowTextReplacement *bool `plist:"AllowTextReplacement,omitempty" json:"AllowTextReplacement,omitempty"`
}
