// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// DeclarationType returns the wire type identifier for LegacyInteractive.
func (LegacyInteractive) DeclarationType() string {
	return "com.apple.configuration.legacy.interactive"
}

// Validate checks the payload against Apple's spec. LegacyInteractive has no
// constraints beyond its field types.
func (p *LegacyInteractive) Validate() error { return nil }
