// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// ManagementTestReturnStatus — allowed values for ManagementTest.ReturnStatus.
type ManagementTestReturnStatus string

// ManagementTestReturnStatus allowed values.
const (
	ManagementTestReturnStatusInstalled ManagementTestReturnStatus = "Installed"
	ManagementTestReturnStatusFailed    ManagementTestReturnStatus = "Failed"
	ManagementTestReturnStatusUnlocked  ManagementTestReturnStatus = "Unlocked"
)

// String returns the ManagementTestReturnStatus value as a plain string.
func (e ManagementTestReturnStatus) String() string { return string(e) }
