// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// DeclarationType returns the wire type identifier for ManagementTest.
func (ManagementTest) DeclarationType() string { return "com.apple.configuration.management.test" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ManagementTest) Validate() error {
	var errs []error
	if p.ReturnStatus != nil {
		if err := validate.InList("ReturnStatus", *p.ReturnStatus, []ManagementTestReturnStatus{ManagementTestReturnStatusInstalled, ManagementTestReturnStatusFailed, ManagementTestReturnStatusUnlocked}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
