// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// ManagementTest — Management:Test.
// The declaration to test declarative device management.
//
// Supported: iOS 15.0+, macOS 13.0+, tvOS 16.0+, visionOS 1.1+, watchOS 10.0+.
type ManagementTest struct {
	// The string to echo back in a status response reason.
	Echo string `plist:"Echo" json:"Echo"`
	// The string to read from a data asset to echo back in status response reason description.
	//
	// Allowed asset types: com.apple.asset.data.
	EchoDataAssetReference *string `plist:"EchoDataAssetReference,omitempty" json:"EchoDataAssetReference,omitempty"`
	// The status the system reports back when the device implements the configuration. Use this to
	// override the normal `success` result.
	//
	// Default: Installed.
	ReturnStatus *ManagementTestReturnStatus `plist:"ReturnStatus,omitempty" json:"ReturnStatus,omitempty"`
}
