// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// DeclarationType returns the wire type identifier for MathSettings.
func (MathSettings) DeclarationType() string { return "com.apple.configuration.math.settings" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *MathSettings) Validate() error {
	var errs []error
	if p.Calculator != nil {
		if err := p.Calculator.Validate(); err != nil {
			errs = append(errs, validate.Nested("Calculator", err))
		}
	}
	if p.SystemBehavior != nil {
		if err := p.SystemBehavior.Validate(); err != nil {
			errs = append(errs, validate.Nested("SystemBehavior", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. MathSettingsCalculatorBasicMode has no
// constraints beyond its field types.
func (p *MathSettingsCalculatorBasicMode) Validate() error { return nil }

// Validate checks the payload against Apple's spec. MathSettingsCalculatorScientificMode has no
// constraints beyond its field types.
func (p *MathSettingsCalculatorScientificMode) Validate() error { return nil }

// Validate checks the payload against Apple's spec. MathSettingsCalculatorProgrammerMode has no
// constraints beyond its field types.
func (p *MathSettingsCalculatorProgrammerMode) Validate() error { return nil }

// Validate checks the payload against Apple's spec. MathSettingsCalculatorMathNotesMode has no
// constraints beyond its field types.
func (p *MathSettingsCalculatorMathNotesMode) Validate() error { return nil }

// Validate checks the payload against Apple's spec. MathSettingsCalculatorInputModes has no
// constraints beyond its field types.
func (p *MathSettingsCalculatorInputModes) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *MathSettingsCalculator) Validate() error {
	var errs []error
	if p.BasicMode != nil {
		if err := p.BasicMode.Validate(); err != nil {
			errs = append(errs, validate.Nested("BasicMode", err))
		}
	}
	if p.ScientificMode != nil {
		if err := p.ScientificMode.Validate(); err != nil {
			errs = append(errs, validate.Nested("ScientificMode", err))
		}
	}
	if p.ProgrammerMode != nil {
		if err := p.ProgrammerMode.Validate(); err != nil {
			errs = append(errs, validate.Nested("ProgrammerMode", err))
		}
	}
	if p.MathNotesMode != nil {
		if err := p.MathNotesMode.Validate(); err != nil {
			errs = append(errs, validate.Nested("MathNotesMode", err))
		}
	}
	if p.InputModes != nil {
		if err := p.InputModes.Validate(); err != nil {
			errs = append(errs, validate.Nested("InputModes", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. MathSettingsSystemBehavior has no
// constraints beyond its field types.
func (p *MathSettingsSystemBehavior) Validate() error { return nil }
