// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// MigrationAssistantSettings — Migration Assistant Settings.
// The declaration to configure Migration Assistant settings.
//
// Supported: macOS 26.4+.
type MigrationAssistantSettings struct {
	// If `true`, the device manages Migration Assistant.
	ShouldDoManagedMigration bool `plist:"ShouldDoManagedMigration" json:"ShouldDoManagedMigration"`
	// An array of strings that represent the user account short names the system excludes from
	// migration.
	ExcludedAccounts []string `plist:"ExcludedAccounts,omitempty" json:"ExcludedAccounts,omitempty"`
	// An array of strings that represent files and directories relative to the user's home directory
	// that the system excludes from migration. Directory paths need to include a trailing "/". For
	// example, to exclude the "Excluded" directory in the "Documents" folder of a user's home
	// directory, use "Documents/Excluded/".
	ExcludedPaths []string `plist:"ExcludedPaths,omitempty" json:"ExcludedPaths,omitempty"`
	// An array of strings that represent files and directories relative to the user's home directory
	// that the system needs to migrate. Directory paths need to include a trailing "/". For example,
	// to require the "Required" directory in the "Documents" folder of a user's home directory, use
	// "Documents/Required/".
	RequiredPaths []string `plist:"RequiredPaths,omitempty" json:"RequiredPaths,omitempty"`
	// If `true`, the system migrates Security & Privacy settings.
	ShouldMigrateSecurityPrivacySettings bool `plist:"ShouldMigrateSecurityPrivacySettings" json:"ShouldMigrateSecurityPrivacySettings"`
}
