// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// NetworkRelay — Network:Relay.
// The declaration to configure Network Relay settings.
//
// Supported: iOS 27.0+, macOS 27.0+, visionOS 27.0+.
type NetworkRelay struct {
	// The name of the network relays that the system displays on the device.
	VisibleName string `plist:"VisibleName" json:"VisibleName"`
	// An array of dictionaries that describe one or more relay servers that the system can chain
	// together.
	Relays []NetworkRelayRelay `plist:"Relays" json:"Relays"`
	// A list of domain strings that the system uses to determine which connection to route through the
	// servers in `Relays`.
	MatchDomains []string `plist:"MatchDomains,omitempty" json:"MatchDomains,omitempty"`
	// A list of domain strings to exclude from routing through the servers in `Relays`. Any connection
	// that matches a domain in the list exactly or is a subdomain of the listed domain won't use the
	// relay server.
	ExcludedDomains []string `plist:"ExcludedDomains,omitempty" json:"ExcludedDomains,omitempty"`
	// A list of Fully Qualified Domain Names (FQDNs) to route through the servers contained in
	// `Relays`. Any connection that matches an FQDN in the list exactly uses the relay servers. If
	// this list and `MatchDomains` are empty, the system routes traffic to all domains to the relay
	// servers, except those that match an excluded domain or excluded FQDN.
	MatchFQDNs []string `plist:"MatchFQDNs,omitempty" json:"MatchFQDNs,omitempty"`
	// A list of Fully Qualified Domain Names (FQDNs) to exclude from routing through the servers
	// contained in `Relays`. Any connection that matches an FQDN in the list exactly won't use the
	// relay server. When `MatchDomains` is also present, any FQDN listed in the list should be a
	// subdomain of at least one `MatchDomain` value, otherwise it won't have any effect.
	ExcludedFQDNs []string `plist:"ExcludedFQDNs,omitempty" json:"ExcludedFQDNs,omitempty"`
	// A globally unique identifier for this relay configuration. The system uses this UUID to route
	// managed apps through the servers in `Relays`. This key is required for user enrollment.
	RelayUUID *string `plist:"RelayUUID,omitempty" json:"RelayUUID,omitempty"`
	// If `true`, the device allows the user to disable this network relay configuration.
	//
	// Default: true.
	UIToggleEnabled *bool `plist:"UIToggleEnabled,omitempty" json:"UIToggleEnabled,omitempty"`
	// If `true`, the device allows the relay to failover to the default system DNS resolver.
	//
	// Default: false.
	AllowDNSFailover *bool `plist:"AllowDNSFailover,omitempty" json:"AllowDNSFailover,omitempty"`
}

// NetworkRelayRelayAdditionalHTTPHeaderFields is the AdditionalHTTPHeaderFields dictionary.
// A dictionary that contains custom HTTP header keys and values to add to each request. The
// dictionary key name represents the HTTP header field name to use, and the dictionary value is
// the string to use as the HTTP header field value.
type NetworkRelayRelayAdditionalHTTPHeaderFields struct {
	// The HTTP header field value for the corresponding header field name.
	ANY string `plist:"ANY" json:"ANY"`
}

// NetworkRelayRelay is the Relay dictionary.
type NetworkRelayRelay struct {
	// The URL or URI template, as defined in RFC 9298, of a relay server that's reachable using HTTP/3
	// and supports proxying TCP and UDP using the CONNECT method.
	HTTP3RelayURL *string `plist:"HTTP3RelayURL,omitempty" json:"HTTP3RelayURL,omitempty"`
	// The URL or URI template, as defined in RFC 9298, of a relay server that's reachable using HTTP/2
	// and supports proxying TCP and UDP using the CONNECT method.
	HTTP2RelayURL *string `plist:"HTTP2RelayURL,omitempty" json:"HTTP2RelayURL,omitempty"`
	// A dictionary that contains custom HTTP header keys and values to add to each request. The
	// dictionary key name represents the HTTP header field name to use, and the dictionary value is
	// the string to use as the HTTP header field value.
	AdditionalHTTPHeaderFields *NetworkRelayRelayAdditionalHTTPHeaderFields `plist:"AdditionalHTTPHeaderFields,omitempty" json:"AdditionalHTTPHeaderFields,omitempty"`
	// The identifier of an asset declaration that contains the identity to install.
	//
	// Allowed asset types: com.apple.asset.credential.identity, com.apple.asset.credential.scep, com.apple.asset.credential.acme.
	IdentityAssetReference *string `plist:"IdentityAssetReference,omitempty" json:"IdentityAssetReference,omitempty"`
	// An array of references to data assets containing DER-encoded public key data that the system
	// uses to authenticate the server during a TLS handshake. The server needs to use one of the keys
	// in the handshake to authenticate.
	//
	// Allowed asset types: com.apple.asset.data.
	PublicKeyData []string `plist:"PublicKeyData,omitempty" json:"PublicKeyData,omitempty"`
}
