// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// NetworkDnsProxy — Network:DNS Proxy.
// The declaration to configure DNS proxy settings.
//
// Supported: iOS 27.0+, macOS 27.0+, visionOS 27.0+.
type NetworkDnsProxy struct {
	// The name of the DNS proxy configuration that the system displays on the device.
	VisibleName string `plist:"VisibleName" json:"VisibleName"`
	// The bundle identifier of the app containing the DNS proxy network extension.
	AppBundleIdentifier string `plist:"AppBundleIdentifier" json:"AppBundleIdentifier"`
	// The identifier of the provider to use for this configuration. Useful for apps that contain more
	// than one DNS proxy extension.
	ProviderComposedIdentifier *string `plist:"ProviderComposedIdentifier,omitempty" json:"ProviderComposedIdentifier,omitempty"`
	// The dictionary of vendor-specific configuration items.
	ProviderConfiguration *NetworkDnsProxyProviderConfiguration `plist:"ProviderConfiguration,omitempty" json:"ProviderConfiguration,omitempty"`
	// A globally unique identifier for this DNS proxy configuration. The proxy processes DNS lookups
	// traffic for managed apps with the same `DNSProxyUUID` in their app attributes. This key is
	// required for user enrollment.
	DNSProxyUUID *string `plist:"DNSProxyUUID,omitempty" json:"DNSProxyUUID,omitempty"`
}

// NetworkDnsProxyProviderConfiguration is the ProviderConfiguration dictionary.
// The dictionary of vendor-specific configuration items.
type NetworkDnsProxyProviderConfiguration struct {
	// Key/value pairs.
	ANY any `plist:"ANY,omitempty" json:"ANY,omitempty"`
}
