// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-sdk-appleservices/device_management/ptr"
	"github.com/deploymenttheory/go-sdk-appleservices/device_management/validate"
)

// DeclarationType returns the wire type identifier for NetworkVpnVpnPlugin.
func (NetworkVpnVpnPlugin) DeclarationType() string {
	return "com.apple.configuration.network.vpn.vpn-plugin"
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPlugin) Validate() error {
	var errs []error
	if p.VendorConfig != nil {
		if err := p.VendorConfig.Validate(); err != nil {
			errs = append(errs, validate.Nested("VendorConfig", err))
		}
	}
	if err := p.Authentication.Validate(); err != nil {
		errs = append(errs, validate.Nested("Authentication", err))
	}
	if p.Provider != nil {
		if err := p.Provider.Validate(); err != nil {
			errs = append(errs, validate.Nested("Provider", err))
		}
	}
	if p.NetworkRouting != nil {
		if err := p.NetworkRouting.Validate(); err != nil {
			errs = append(errs, validate.Nested("NetworkRouting", err))
		}
	}
	if p.Idle != nil {
		if err := p.Idle.Validate(); err != nil {
			errs = append(errs, validate.Nested("Idle", err))
		}
	}
	if p.OnDemand != nil {
		if err := p.OnDemand.Validate(); err != nil {
			errs = append(errs, validate.Nested("OnDemand", err))
		}
	}
	if p.DNS != nil {
		if err := p.DNS.Validate(); err != nil {
			errs = append(errs, validate.Nested("DNS", err))
		}
	}
	if p.Proxies != nil {
		if err := p.Proxies.Validate(); err != nil {
			errs = append(errs, validate.Nested("Proxies", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. NetworkVpnVpnPluginVendorConfig has no
// constraints beyond its field types.
func (p *NetworkVpnVpnPluginVendorConfig) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPluginAuthentication) Validate() error {
	var errs []error
	if err := validate.InList("Method", p.Method, []NetworkVpnVpnPluginAuthenticationMethod{NetworkVpnVpnPluginAuthenticationMethodPassword, NetworkVpnVpnPluginAuthenticationMethodCertificate, NetworkVpnVpnPluginAuthenticationMethodPasswordCertificate}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPluginProvider) Validate() error {
	var errs []error
	if p.Type != nil {
		if err := validate.InList("Type", *p.Type, []NetworkVpnVpnPluginProviderType{NetworkVpnVpnPluginProviderTypePacketTunnel, NetworkVpnVpnPluginProviderTypeAppProxy}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. NetworkVpnVpnPluginNetworkRouting has no
// constraints beyond its field types.
func (p *NetworkVpnVpnPluginNetworkRouting) Validate() error { return nil }

// Validate checks the payload against Apple's spec. NetworkVpnVpnPluginIdle has no
// constraints beyond its field types.
func (p *NetworkVpnVpnPluginIdle) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPluginOnDemandRulesElementActionParameter) Validate() error {
	var errs []error
	if p.Domains == nil {
		errs = append(errs, validate.Required("Domains"))
	}
	if err := validate.InList("DomainAction", p.DomainAction, []NetworkVpnVpnPluginOnDemandRulesElementActionParameterDomainAction{NetworkVpnVpnPluginOnDemandRulesElementActionParameterDomainActionConnectIfNeeded, NetworkVpnVpnPluginOnDemandRulesElementActionParameterDomainActionNeverConnect}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPluginOnDemandRulesElement) Validate() error {
	var errs []error
	if err := validate.InList("Action", p.Action, []NetworkVpnVpnPluginOnDemandRulesElementAction{NetworkVpnVpnPluginOnDemandRulesElementActionAllow, NetworkVpnVpnPluginOnDemandRulesElementActionConnect, NetworkVpnVpnPluginOnDemandRulesElementActionDisconnect, NetworkVpnVpnPluginOnDemandRulesElementActionEvaluateConnection, NetworkVpnVpnPluginOnDemandRulesElementActionIgnore}); err != nil {
		errs = append(errs, err)
	}
	for i := range p.ActionParameters {
		if err := p.ActionParameters[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ActionParameters", i, err))
		}
	}
	if p.InterfaceTypeMatch != nil {
		if err := validate.InList("InterfaceTypeMatch", *p.InterfaceTypeMatch, []NetworkVpnVpnPluginOnDemandRulesElementInterfaceTypeMatch{NetworkVpnVpnPluginOnDemandRulesElementInterfaceTypeMatchEthernet, NetworkVpnVpnPluginOnDemandRulesElementInterfaceTypeMatchWiFi, NetworkVpnVpnPluginOnDemandRulesElementInterfaceTypeMatchCellular}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPluginOnDemand) Validate() error {
	var errs []error
	for i := range p.Rules {
		if err := p.Rules[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Rules", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPluginDNS) Validate() error {
	var errs []error
	if p.ServerAddresses == nil {
		errs = append(errs, validate.Required("ServerAddresses"))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPluginProxiesProtocolHTTP) Validate() error {
	var errs []error
	if p.Port != nil {
		if err := validate.IntRange("Port", *p.Port, ptr.To(int64(0)), ptr.To(int64(65535))); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPluginProxiesProtocolHTTPS) Validate() error {
	var errs []error
	if p.Port != nil {
		if err := validate.IntRange("Port", *p.Port, ptr.To(int64(0)), ptr.To(int64(65535))); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPluginProxiesProtocol) Validate() error {
	var errs []error
	if p.HTTP != nil {
		if err := p.HTTP.Validate(); err != nil {
			errs = append(errs, validate.Nested("HTTP", err))
		}
	}
	if p.HTTPS != nil {
		if err := p.HTTPS.Validate(); err != nil {
			errs = append(errs, validate.Nested("HTTPS", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkVpnVpnPluginProxies) Validate() error {
	var errs []error
	if p.Protocol != nil {
		if err := p.Protocol.Validate(); err != nil {
			errs = append(errs, validate.Nested("Protocol", err))
		}
	}
	return errors.Join(errs...)
}
