// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// NetworkVpnVpnPlugin — Network:VPN:VPN Plugin.
// The declaration to configure a VPN using the VPN plugin sub-type.
//
// Supported: iOS 27.0+, macOS 27.0+, tvOS 27.0+, visionOS 27.0+.
type NetworkVpnVpnPlugin struct {
	// The name of the VPN connection that the system displays on the device.
	VisibleName string `plist:"VisibleName" json:"VisibleName"`
	// The IP address or hostname of the VPN server.
	HostName string `plist:"HostName" json:"HostName"`
	// An identifier for a vendor-specified configuration dictionary.
	SubType string `plist:"SubType" json:"SubType"`
	// The vendor-specific configuration dictionary, which the system reads only when `SubType` has a
	// value.
	VendorConfig *NetworkVpnVpnPluginVendorConfig `plist:"VendorConfig,omitempty" json:"VendorConfig,omitempty"`
	// Settings that control authentication.
	Authentication NetworkVpnVpnPluginAuthentication `plist:"Authentication" json:"Authentication"`
	// Specifies details about the provider.
	Provider *NetworkVpnVpnPluginProvider `plist:"Provider,omitempty" json:"Provider,omitempty"`
	// Specifies details about how the VPN routes different types of network traffic.
	NetworkRouting *NetworkVpnVpnPluginNetworkRouting `plist:"NetworkRouting,omitempty" json:"NetworkRouting,omitempty"`
	// Specifies details about how the system handles idle VPN connections.
	Idle *NetworkVpnVpnPluginIdle `plist:"Idle,omitempty" json:"Idle,omitempty"`
	// Specifies details about how the system controls on-demand VPN.
	OnDemand *NetworkVpnVpnPluginOnDemand `plist:"OnDemand,omitempty" json:"OnDemand,omitempty"`
	// A dictionary to use for all VPN types.
	DNS *NetworkVpnVpnPluginDNS `plist:"DNS,omitempty" json:"DNS,omitempty"`
	// The dictionary to use to configure `Proxies` for use with `VPN`.
	Proxies *NetworkVpnVpnPluginProxies `plist:"Proxies,omitempty" json:"Proxies,omitempty"`
}

// NetworkVpnVpnPluginVendorConfig is the VendorConfig dictionary.
// The vendor-specific configuration dictionary, which the system reads only when `SubType` has a
// value.
type NetworkVpnVpnPluginVendorConfig struct {
	// The Kerberos realm name, which needs to be properly capitalized. Valid only for Juniper SSL and
	// Pulse Secure.
	Realm *string `plist:"Realm,omitempty" json:"Realm,omitempty"`
	// The role to select when connecting to the server. Valid only for Juniper SSL and Pulse Secure.
	Role *string `plist:"Role,omitempty" json:"Role,omitempty"`
	// The group to connect to on the head end. Valid for Cisco AnyConnect and Cisco Legacy AnyConnect.
	Group *string `plist:"Group,omitempty" json:"Group,omitempty"`
	// The login group or domain. Valid only for SonicWALL Mobile Connect.
	LoginGroupOrDomain *string `plist:"LoginGroupOrDomain,omitempty" json:"LoginGroupOrDomain,omitempty"`
}

// NetworkVpnVpnPluginAuthentication is the Authentication dictionary.
// Settings that control authentication.
type NetworkVpnVpnPluginAuthentication struct {
	// The authentication method to use.
	Method NetworkVpnVpnPluginAuthenticationMethod `plist:"Method" json:"Method"`
	// The identifier of an asset declaration that contains the credentials (user name and password) to
	// authenticate with the VPN server. Required when `Authentication.Method` is set to `Password`.
	//
	// Allowed asset types: com.apple.asset.credential.userpassword.
	CredentialsAssetReference *string `plist:"CredentialsAssetReference,omitempty" json:"CredentialsAssetReference,omitempty"`
	// The identifier of a credential asset declaration that contains the identity that this account
	// requires to authenticate with the VPN server. Required when `Authentication.Method` is set to
	// `Certificate`.
	//
	// Allowed asset types: com.apple.asset.credential.acme, com.apple.asset.credential.identity, com.apple.asset.credential.scep.
	IdentityAssetReference *string `plist:"IdentityAssetReference,omitempty" json:"IdentityAssetReference,omitempty"`
}

// NetworkVpnVpnPluginProvider is the Provider dictionary.
// Specifies details about the provider.
type NetworkVpnVpnPluginProvider struct {
	// The type of VPN service. If the value is `app-proxy`, the service tunnels traffic at the app
	// level. If the value is `packet-tunnel`, the service tunnels traffic at the IP layer.
	//
	// Default: packet-tunnel.
	Type *NetworkVpnVpnPluginProviderType `plist:"Type,omitempty" json:"Type,omitempty"`
	// If the `SubType` field contains the bundle identifier of an app that contains multiple VPN
	// providers of the same type (app-proxy or packet-tunnel), then the system uses this field to
	// choose which provider to use for this configuration. If the VPN provider is implemented as a
	// System Extension, then this field is required.
	ComposedIdentifier *string `plist:"ComposedIdentifier,omitempty" json:"ComposedIdentifier,omitempty"`
}

// NetworkVpnVpnPluginNetworkRouting is the NetworkRouting dictionary.
// Specifies details about how the VPN routes different types of network traffic.
type NetworkVpnVpnPluginNetworkRouting struct {
	// If `true`, all the VPN's non-default routes take precedence over any locally defined routes.
	//
	// Default: false.
	EnforceRoutes *bool `plist:"EnforceRoutes,omitempty" json:"EnforceRoutes,omitempty"`
	// If `true`, routes all traffic through the VPN, with some exclusions. Several of the exclusions
	// can be controlled with the `ExcludeLocalNetworks`, `ExcludeCellularServices`, `ExcludeAPNs` and
	// `ExcludeDeviceCommunication` properties. The following traffic is always excluded from the
	// tunnel:
	//
	// Default: false.
	IncludeAllNetworks *bool `plist:"IncludeAllNetworks,omitempty" json:"IncludeAllNetworks,omitempty"`
	// If `true` and `IncludeAllNetworks` is `true`, routes all local network traffic outside the VPN.
	ExcludeLocalNetworks *bool `plist:"ExcludeLocalNetworks,omitempty" json:"ExcludeLocalNetworks,omitempty"`
	// If `true` and `IncludeAllNetworks` is `true`, then the system excludes internet-routable network
	// traffic for cellular services (VoLTE, Wi-Fi Calling, IMS, MMS, Visual Voicemail, etc.) from the
	// tunnel. Note that some cellular carriers route cellular services traffic directly to the carrier
	// network, bypassing the internet. Such cellular services traffic is always excluded from the
	// tunnel.
	//
	// Default: true.
	ExcludeCellularServices *bool `plist:"ExcludeCellularServices,omitempty" json:"ExcludeCellularServices,omitempty"`
	// If `true` and `IncludeAllNetworks` is `true`, then the system excludes the network traffic for
	// the Apple Push Notification service (APNs) from the tunnel.
	//
	// Default: true.
	ExcludeAPNs *bool `plist:"ExcludeAPNs,omitempty" json:"ExcludeAPNs,omitempty"`
	// If set to `true` and `IncludeAllNetworks` is set to `true`, the device excludes network traffic
	// used for communicating with devices connected via USB or Wi-Fi from the tunnel.
	//
	// Default: true.
	ExcludeDeviceCommunication *bool `plist:"ExcludeDeviceCommunication,omitempty" json:"ExcludeDeviceCommunication,omitempty"`
}

// NetworkVpnVpnPluginIdle is the Idle dictionary.
// Specifies details about how the system handles idle VPN connections.
type NetworkVpnVpnPluginIdle struct {
	// If `true`, disconnects after an on-demand connection idles.
	//
	// Default: false.
	Disconnect *bool `plist:"Disconnect,omitempty" json:"Disconnect,omitempty"`
	// The length of time to wait, in seconds, before disconnecting an on-demand connection.
	Timer *int64 `plist:"Timer,omitempty" json:"Timer,omitempty"`
}

// NetworkVpnVpnPluginOnDemandRulesElementActionParameter is the ActionParameter dictionary.
// A dictionary that provides rules similar to the OnDemandRules dictionary, but evaluated on each
// connection instead of when the network changes. These dictionaries are evaluated in order, and
// the behavior is determined by the first dictionary that matches.
type NetworkVpnVpnPluginOnDemandRulesElementActionParameter struct {
	// The domains to apply this evaluation.
	Domains []string `plist:"Domains" json:"Domains"`
	// Defines the VPN behavior for the specified domains. Allowed values are:
	DomainAction NetworkVpnVpnPluginOnDemandRulesElementActionParameterDomainAction `plist:"DomainAction" json:"DomainAction"`
	// An array of IP addresses of DNS servers to use for resolving the specified domains. These
	// servers don't need to be part of the device's current network configuration. If these DNS
	// servers aren't reachable, the system establishes a VPN connection. These DNS servers need to be
	// either internal DNS servers or trusted external DNS servers.
	RequiredDNSServers []string `plist:"RequiredDNSServers,omitempty" json:"RequiredDNSServers,omitempty"`
	// An HTTP or HTTPS (preferred) URL to probe, using a GET request. If the URL's hostname can't be
	// resolved, if the server is unreachable, or if the server doesn't respond with a 200 HTTP status
	// code, a VPN connection is established in response.
	RequiredURLStringProbe *string `plist:"RequiredURLStringProbe,omitempty" json:"RequiredURLStringProbe,omitempty"`
}

// NetworkVpnVpnPluginOnDemandRulesElement is the RulesElement dictionary.
type NetworkVpnVpnPluginOnDemandRulesElement struct {
	// The action to take if this dictionary matches the current network. Possible values are:
	Action NetworkVpnVpnPluginOnDemandRulesElementAction `plist:"Action" json:"Action"`
	// An array of dictionaries that provides rules similar to the `OnDemandRules` dictionary, but
	// evaluated on each connection instead of when the network changes. This value is only for use
	// with dictionaries in which the `Action` value is `EvaluateConnection`. The system evaluates
	// these dictionaries in order and the first dictionary that matches determines the behavior.
	ActionParameters []NetworkVpnVpnPluginOnDemandRulesElementActionParameter `plist:"ActionParameters,omitempty" json:"ActionParameters,omitempty"`
	// An array of domain names. This rule matches if any of the domain names in the specified list
	// matches any domain in the device's search domains list.
	DNSDomainMatch []string `plist:"DNSDomainMatch,omitempty" json:"DNSDomainMatch,omitempty"`
	// An array of IP addresses. This rule matches if any of the network's specified DNS servers match
	// any entry in the array.
	DNSServerAddressMatch []string `plist:"DNSServerAddressMatch,omitempty" json:"DNSServerAddressMatch,omitempty"`
	// An interface type. If specified, this rule matches only if the primary network interface
	// hardware matches the specified type.
	InterfaceTypeMatch *NetworkVpnVpnPluginOnDemandRulesElementInterfaceTypeMatch `plist:"InterfaceTypeMatch,omitempty" json:"InterfaceTypeMatch,omitempty"`
	// An array of SSIDs to match against the current network. If the network isn't a Wi-Fi network or
	// if the SSID doesn't appear in this array, the match fails.
	SSIDMatch []string `plist:"SSIDMatch,omitempty" json:"SSIDMatch,omitempty"`
	// A URL to probe. This rule matches when this URL is successfully fetched (returns a `200` HTTP
	// status code) without redirection.
	URLStringProbe *string `plist:"URLStringProbe,omitempty" json:"URLStringProbe,omitempty"`
}

// NetworkVpnVpnPluginOnDemand is the OnDemand dictionary.
// Specifies details about how the system controls on-demand VPN.
type NetworkVpnVpnPluginOnDemand struct {
	// If `true`, enables VPN On Demand.
	//
	// Default: false.
	Enabled *bool `plist:"Enabled,omitempty" json:"Enabled,omitempty"`
	// If `true`, the device disables the Connect On Demand toggle in Settings for this configuration.
	//
	// Default: false.
	DisableUserOverride *bool `plist:"DisableUserOverride,omitempty" json:"DisableUserOverride,omitempty"`
	// An array of dictionaries defining On Demand Rules.
	Rules []NetworkVpnVpnPluginOnDemandRulesElement `plist:"Rules,omitempty" json:"Rules,omitempty"`
}

// NetworkVpnVpnPluginDNS is the DNS dictionary.
// A dictionary to use for all VPN types.
type NetworkVpnVpnPluginDNS struct {
	// The array of DNS server IP address strings. These IP addresses can be a mixture of IPv4 and IPv6
	// addresses.
	ServerAddresses []string `plist:"ServerAddresses" json:"ServerAddresses"`
	// The list of domain strings used to fully qualify single-label host names.
	SearchDomains []string `plist:"SearchDomains,omitempty" json:"SearchDomains,omitempty"`
	// The primary domain of the tunnel.
	DomainName *string `plist:"DomainName,omitempty" json:"DomainName,omitempty"`
	// The list of domain strings used to determine which DNS queries use the DNS resolver settings in
	// `ServerAddresses`. The system uses this key to create a split DNS configuration where it
	// resolves only hosts in certain domains using the tunnel's DNS resolver. The system uses the
	// default resolver for hosts that aren't in one of the domains in this list.
	SupplementalMatchDomains []string `plist:"SupplementalMatchDomains,omitempty" json:"SupplementalMatchDomains,omitempty"`
	// If `true`, don't append the domains in the `SupplementalMatchDomains` list to the resolver's
	// list of search domains.
	//
	// Default: false.
	SupplementalMatchDomainsNoSearch *bool `plist:"SupplementalMatchDomainsNoSearch,omitempty" json:"SupplementalMatchDomainsNoSearch,omitempty"`
	// The identifier of a credential asset declaration that contains the identity that the system uses
	// to authenticate the user to the DNS resolver.
	//
	// Allowed asset types: com.apple.asset.credential.acme, com.apple.asset.credential.identity, com.apple.asset.credential.scep.
	IdentityAssetReference *string `plist:"IdentityAssetReference,omitempty" json:"IdentityAssetReference,omitempty"`
}

// NetworkVpnVpnPluginProxiesProtocolHTTP is the HTTP dictionary.
// The dictionary to use to configure the HTTP (non-TLS) server.
type NetworkVpnVpnPluginProxiesProtocolHTTP struct {
	// If `true`, enables proxy for HTTP traffic.
	//
	// Default: false.
	Enable *bool `plist:"Enable,omitempty" json:"Enable,omitempty"`
	// The host name of the HTTP proxy.
	HostName *string `plist:"HostName,omitempty" json:"HostName,omitempty"`
	// The port number of the HTTP proxy. This field is required if `HostName` is specified.
	Port *int64 `plist:"Port,omitempty" json:"Port,omitempty"`
}

// NetworkVpnVpnPluginProxiesProtocolHTTPS is the HTTPS dictionary.
// The dictionary to use to configure the HTTPS (TLS) server.
type NetworkVpnVpnPluginProxiesProtocolHTTPS struct {
	// If `true`, enables proxy for HTTPS traffic.
	//
	// Default: false.
	Enable *bool `plist:"Enable,omitempty" json:"Enable,omitempty"`
	// The host name of the HTTPS proxy.
	HostName *string `plist:"HostName,omitempty" json:"HostName,omitempty"`
	// The port number of the HTTPS proxy. This field is required if `HostName` is specified.
	Port *int64 `plist:"Port,omitempty" json:"Port,omitempty"`
}

// NetworkVpnVpnPluginProxiesProtocol is the Protocol dictionary.
// The dictionary to use to configure HTTP servers for `Proxies` for use with `VPN`.
type NetworkVpnVpnPluginProxiesProtocol struct {
	// The dictionary to use to configure the HTTP (non-TLS) server.
	HTTP *NetworkVpnVpnPluginProxiesProtocolHTTP `plist:"HTTP,omitempty" json:"HTTP,omitempty"`
	// The dictionary to use to configure the HTTPS (TLS) server.
	HTTPS *NetworkVpnVpnPluginProxiesProtocolHTTPS `plist:"HTTPS,omitempty" json:"HTTPS,omitempty"`
	// The identifier of an asset declaration that contains the credentials (user name and password) to
	// authenticate with the proxy server.
	//
	// Allowed asset types: com.apple.asset.credential.userpassword.
	CredentialsAssetReference *string `plist:"CredentialsAssetReference,omitempty" json:"CredentialsAssetReference,omitempty"`
}

// NetworkVpnVpnPluginProxies is the Proxies dictionary.
// The dictionary to use to configure `Proxies` for use with `VPN`.
type NetworkVpnVpnPluginProxies struct {
	// If `true`, enables automatic proxy configuration.
	//
	// Default: false.
	AutoConfigEnable *bool `plist:"AutoConfigEnable,omitempty" json:"AutoConfigEnable,omitempty"`
	// If `true`, enables proxy auto discovery.
	//
	// Default: true.
	AutoDiscoveryEnable *bool `plist:"AutoDiscoveryEnable,omitempty" json:"AutoDiscoveryEnable,omitempty"`
	// The URL to the location of the proxy auto-configuration file. Used only when
	// `ProxyAutoConfigEnable` is `true`.
	AutoConfigURLString *string `plist:"AutoConfigURLString,omitempty" json:"AutoConfigURLString,omitempty"`
	// An array of domains that defines which hosts use proxy settings for hosts.
	SupplementalMatchDomains []string `plist:"SupplementalMatchDomains,omitempty" json:"SupplementalMatchDomains,omitempty"`
	// The dictionary to use to configure HTTP servers for `Proxies` for use with `VPN`.
	Protocol *NetworkVpnVpnPluginProxiesProtocol `plist:"Protocol,omitempty" json:"Protocol,omitempty"`
}
