// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-sdk-appleservices/device_management/validate"
)

// DeclarationType returns the wire type identifier for NetworkDnsSettings.
func (NetworkDnsSettings) DeclarationType() string {
	return "com.apple.configuration.network.dns-settings"
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkDnsSettings) Validate() error {
	var errs []error
	if err := p.DNSSettings.Validate(); err != nil {
		errs = append(errs, validate.Nested("DNSSettings", err))
	}
	for i := range p.OnDemandRules {
		if err := p.OnDemandRules[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("OnDemandRules", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkDnsSettingsDNSSettings) Validate() error {
	var errs []error
	if err := validate.InList("DNSProtocol", p.DNSProtocol, []NetworkDnsSettingsDNSSettingsDNSProtocol{NetworkDnsSettingsDNSSettingsDNSProtocolHTTPS, NetworkDnsSettingsDNSSettingsDNSProtocolTLS}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkDnsSettingsOnDemandRulesElementActionParameter) Validate() error {
	var errs []error
	if p.Domains == nil {
		errs = append(errs, validate.Required("Domains"))
	}
	if err := validate.InList("DomainAction", p.DomainAction, []NetworkDnsSettingsOnDemandRulesElementActionParameterDomainAction{NetworkDnsSettingsOnDemandRulesElementActionParameterDomainActionNeverConnect, NetworkDnsSettingsOnDemandRulesElementActionParameterDomainActionConnectIfNeeded}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkDnsSettingsOnDemandRulesElement) Validate() error {
	var errs []error
	if err := validate.InList("Action", p.Action, []NetworkDnsSettingsOnDemandRulesElementAction{NetworkDnsSettingsOnDemandRulesElementActionConnect, NetworkDnsSettingsOnDemandRulesElementActionDisconnect, NetworkDnsSettingsOnDemandRulesElementActionEvaluateConnection}); err != nil {
		errs = append(errs, err)
	}
	for i := range p.ActionParameters {
		if err := p.ActionParameters[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("ActionParameters", i, err))
		}
	}
	if p.InterfaceTypeMatch != nil {
		if err := validate.InList("InterfaceTypeMatch", *p.InterfaceTypeMatch, []NetworkDnsSettingsOnDemandRulesElementInterfaceTypeMatch{NetworkDnsSettingsOnDemandRulesElementInterfaceTypeMatchEthernet, NetworkDnsSettingsOnDemandRulesElementInterfaceTypeMatchWiFi, NetworkDnsSettingsOnDemandRulesElementInterfaceTypeMatchCellular}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
