// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-sdk-appleservices/device_management/validate"
)

// DeclarationType returns the wire type identifier for NetworkRelay.
func (NetworkRelay) DeclarationType() string { return "com.apple.configuration.network.relay" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkRelay) Validate() error {
	var errs []error
	if p.Relays == nil {
		errs = append(errs, validate.Required("Relays"))
	}
	for i := range p.Relays {
		if err := p.Relays[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("Relays", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec. NetworkRelayRelayAdditionalHTTPHeaderFields has no
// constraints beyond its field types.
func (p *NetworkRelayRelayAdditionalHTTPHeaderFields) Validate() error { return nil }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *NetworkRelayRelay) Validate() error {
	var errs []error
	if p.AdditionalHTTPHeaderFields != nil {
		if err := p.AdditionalHTTPHeaderFields.Validate(); err != nil {
			errs = append(errs, validate.Nested("AdditionalHTTPHeaderFields", err))
		}
	}
	return errors.Join(errs...)
}
