// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// DeclarationType returns the wire type identifier for Package.
func (Package) DeclarationType() string { return "com.apple.configuration.package" }

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *Package) Validate() error {
	var errs []error
	if p.InstallBehavior != nil {
		if err := p.InstallBehavior.Validate(); err != nil {
			errs = append(errs, validate.Nested("InstallBehavior", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *PackageInstallBehavior) Validate() error {
	var errs []error
	if p.Install != nil {
		if err := validate.InList("Install", *p.Install, []PackageInstallBehaviorInstall{PackageInstallBehaviorInstallOptional, PackageInstallBehaviorInstallRequired}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}
