// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"github.com/deploymenttheory/go-api-sdk-apple/device_management/ddm"
)

// ByDeclarationType maps declaration type identifiers to payload factories.
// Factories return zero payloads ready to populate or decode into.
var ByDeclarationType = map[string]func() ddm.DeclarationPayload{
	"com.apple.configuration.account.caldav":                      func() ddm.DeclarationPayload { return new(AccountCaldav) },
	"com.apple.configuration.account.carddav":                     func() ddm.DeclarationPayload { return new(AccountCarddav) },
	"com.apple.configuration.account.exchange":                    func() ddm.DeclarationPayload { return new(AccountExchange) },
	"com.apple.configuration.account.google":                      func() ddm.DeclarationPayload { return new(AccountGoogle) },
	"com.apple.configuration.account.ldap":                        func() ddm.DeclarationPayload { return new(AccountLdap) },
	"com.apple.configuration.account.mail":                        func() ddm.DeclarationPayload { return new(AccountMail) },
	"com.apple.configuration.account.subscribed-calendar":         func() ddm.DeclarationPayload { return new(AccountSubscribedCalendar) },
	"com.apple.configuration.app.managed":                         func() ddm.DeclarationPayload { return new(AppManaged) },
	"com.apple.configuration.audio-accessory.settings":            func() ddm.DeclarationPayload { return new(AudioAccessorySettings) },
	"com.apple.configuration.diskmanagement.settings":             func() ddm.DeclarationPayload { return new(DiskmanagementSettings) },
	"com.apple.configuration.external-intelligence.settings":      func() ddm.DeclarationPayload { return new(ExternalIntelligenceSettings) },
	"com.apple.configuration.intelligence.settings":               func() ddm.DeclarationPayload { return new(IntelligenceSettings) },
	"com.apple.configuration.keyboard.settings":                   func() ddm.DeclarationPayload { return new(KeyboardSettings) },
	"com.apple.configuration.legacy":                              func() ddm.DeclarationPayload { return new(Legacy) },
	"com.apple.configuration.legacy.interactive":                  func() ddm.DeclarationPayload { return new(LegacyInteractive) },
	"com.apple.configuration.management.status-subscriptions":     func() ddm.DeclarationPayload { return new(ManagementStatusSubscriptions) },
	"com.apple.configuration.management.test":                     func() ddm.DeclarationPayload { return new(ManagementTest) },
	"com.apple.configuration.math.settings":                       func() ddm.DeclarationPayload { return new(MathSettings) },
	"com.apple.configuration.migration-assistant.settings":        func() ddm.DeclarationPayload { return new(MigrationAssistantSettings) },
	"com.apple.configuration.package":                             func() ddm.DeclarationPayload { return new(Package) },
	"com.apple.configuration.passcode.settings":                   func() ddm.DeclarationPayload { return new(PasscodeSettings) },
	"com.apple.configuration.safari.bookmarks":                    func() ddm.DeclarationPayload { return new(SafariBookmarks) },
	"com.apple.configuration.safari.extensions.settings":          func() ddm.DeclarationPayload { return new(SafariExtensionsSettings) },
	"com.apple.configuration.safari.settings":                     func() ddm.DeclarationPayload { return new(SafariSettings) },
	"com.apple.configuration.screensharing.connection":            func() ddm.DeclarationPayload { return new(ScreensharingConnection) },
	"com.apple.configuration.screensharing.connection.group":      func() ddm.DeclarationPayload { return new(ScreensharingConnectionGroup) },
	"com.apple.configuration.screensharing.host.settings":         func() ddm.DeclarationPayload { return new(ScreensharingHostSettings) },
	"com.apple.configuration.security.certificate":                func() ddm.DeclarationPayload { return new(SecurityCertificate) },
	"com.apple.configuration.security.identity":                   func() ddm.DeclarationPayload { return new(SecurityIdentity) },
	"com.apple.configuration.security.passkey.attestation":        func() ddm.DeclarationPayload { return new(SecurityPasskeyAttestation) },
	"com.apple.configuration.services.background-tasks":           func() ddm.DeclarationPayload { return new(ServicesBackgroundTasks) },
	"com.apple.configuration.services.configuration-files":        func() ddm.DeclarationPayload { return new(ServicesConfigurationFiles) },
	"com.apple.configuration.siri.settings":                       func() ddm.DeclarationPayload { return new(SiriSettings) },
	"com.apple.configuration.softwareupdate.enforcement.specific": func() ddm.DeclarationPayload { return new(SoftwareupdateEnforcementSpecific) },
	"com.apple.configuration.softwareupdate.settings":             func() ddm.DeclarationPayload { return new(SoftwareupdateSettings) },
	"com.apple.configuration.watch.enrollment":                    func() ddm.DeclarationPayload { return new(WatchEnrollment) },
}
