// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// ExtensionDictionaryState — allowed values for ExtensionDictionary.State.
type ExtensionDictionaryState string

// ExtensionDictionaryState allowed values.
const (
	ExtensionDictionaryStateAllowed   ExtensionDictionaryState = "Allowed"
	ExtensionDictionaryStateAlwaysOn  ExtensionDictionaryState = "AlwaysOn"
	ExtensionDictionaryStateAlwaysOff ExtensionDictionaryState = "AlwaysOff"
)

// String returns the ExtensionDictionaryState value as a plain string.
func (e ExtensionDictionaryState) String() string { return string(e) }

// ExtensionDictionaryPrivateBrowsing — allowed values for ExtensionDictionary.PrivateBrowsing.
type ExtensionDictionaryPrivateBrowsing string

// ExtensionDictionaryPrivateBrowsing allowed values.
const (
	ExtensionDictionaryPrivateBrowsingAllowed   ExtensionDictionaryPrivateBrowsing = "Allowed"
	ExtensionDictionaryPrivateBrowsingAlwaysOn  ExtensionDictionaryPrivateBrowsing = "AlwaysOn"
	ExtensionDictionaryPrivateBrowsingAlwaysOff ExtensionDictionaryPrivateBrowsing = "AlwaysOff"
)

// String returns the ExtensionDictionaryPrivateBrowsing value as a plain string.
func (e ExtensionDictionaryPrivateBrowsing) String() string { return string(e) }
