// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// SafariSettingsAcceptCookies — allowed values for SafariSettings.AcceptCookies.
type SafariSettingsAcceptCookies string

// SafariSettingsAcceptCookies allowed values.
const (
	SafariSettingsAcceptCookiesNever           SafariSettingsAcceptCookies = "Never"
	SafariSettingsAcceptCookiesCurrentWebsite  SafariSettingsAcceptCookies = "CurrentWebsite"
	SafariSettingsAcceptCookiesVisitedWebsites SafariSettingsAcceptCookies = "VisitedWebsites"
	SafariSettingsAcceptCookiesAlways          SafariSettingsAcceptCookies = "Always"
)

// String returns the SafariSettingsAcceptCookies value as a plain string.
func (e SafariSettingsAcceptCookies) String() string { return string(e) }

// SafariSettingsNewTabStartPagePageType — allowed values for SafariSettingsNewTabStartPage.PageType.
type SafariSettingsNewTabStartPagePageType string

// SafariSettingsNewTabStartPagePageType allowed values.
const (
	SafariSettingsNewTabStartPagePageTypeStart     SafariSettingsNewTabStartPagePageType = "Start"
	SafariSettingsNewTabStartPagePageTypeHome      SafariSettingsNewTabStartPagePageType = "Home"
	SafariSettingsNewTabStartPagePageTypeExtension SafariSettingsNewTabStartPagePageType = "Extension"
)

// String returns the SafariSettingsNewTabStartPagePageType value as a plain string.
func (e SafariSettingsNewTabStartPagePageType) String() string { return string(e) }

// WebsiteDictionaryCamera — allowed values for WebsiteDictionary.Camera.
type WebsiteDictionaryCamera string

// WebsiteDictionaryCamera allowed values.
const (
	WebsiteDictionaryCameraNone  WebsiteDictionaryCamera = "None"
	WebsiteDictionaryCameraAllow WebsiteDictionaryCamera = "Allow"
)

// String returns the WebsiteDictionaryCamera value as a plain string.
func (e WebsiteDictionaryCamera) String() string { return string(e) }

// WebsiteDictionaryMicrophone — allowed values for WebsiteDictionary.Microphone.
type WebsiteDictionaryMicrophone string

// WebsiteDictionaryMicrophone allowed values.
const (
	WebsiteDictionaryMicrophoneNone  WebsiteDictionaryMicrophone = "None"
	WebsiteDictionaryMicrophoneAllow WebsiteDictionaryMicrophone = "Allow"
)

// String returns the WebsiteDictionaryMicrophone value as a plain string.
func (e WebsiteDictionaryMicrophone) String() string { return string(e) }
