// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// DeclarationType returns the wire type identifier for SafariExtensionsSettings.
func (SafariExtensionsSettings) DeclarationType() string {
	return "com.apple.configuration.safari.extensions.settings"
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *SafariExtensionsSettings) Validate() error {
	var errs []error
	if p.ManagedExtensions != nil {
		if err := p.ManagedExtensions.Validate(); err != nil {
			errs = append(errs, validate.Nested("ManagedExtensions", err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ExtensionDictionary) Validate() error {
	var errs []error
	if p.State != nil {
		if err := validate.InList("State", *p.State, []ExtensionDictionaryState{ExtensionDictionaryStateAllowed, ExtensionDictionaryStateAlwaysOn, ExtensionDictionaryStateAlwaysOff}); err != nil {
			errs = append(errs, err)
		}
	}
	if p.PrivateBrowsing != nil {
		if err := validate.InList("PrivateBrowsing", *p.PrivateBrowsing, []ExtensionDictionaryPrivateBrowsing{ExtensionDictionaryPrivateBrowsingAllowed, ExtensionDictionaryPrivateBrowsingAlwaysOn, ExtensionDictionaryPrivateBrowsingAlwaysOff}); err != nil {
			errs = append(errs, err)
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *SafariExtensionsSettingsManagedExtensions) Validate() error {
	var errs []error
	if p.ANY != nil {
		if err := p.ANY.Validate(); err != nil {
			errs = append(errs, validate.Nested("ANY", err))
		}
	}
	return errors.Join(errs...)
}
