// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// SafariSettings — Safari:Settings.
// The declaration to configure Safari settings.
//
// Supported: iOS 26.0+, macOS 26.0+, visionOS 26.0+.
type SafariSettings struct {
	// The policy Safari uses for managing cookies:
	//
	// Default: Always.
	AcceptCookies *SafariSettingsAcceptCookies `plist:"AcceptCookies,omitempty" json:"AcceptCookies,omitempty"`
	// If `false`, the system forces fraud warnings on in Safari.
	//
	// Default: true.
	AllowDisablingFraudWarning *bool `plist:"AllowDisablingFraudWarning,omitempty" json:"AllowDisablingFraudWarning,omitempty"`
	// If `false`, the system disables clearing history in Safari.
	//
	// Default: true.
	AllowHistoryClearing *bool `plist:"AllowHistoryClearing,omitempty" json:"AllowHistoryClearing,omitempty"`
	// If `false`, the system disables JavaScript in Safari.
	//
	// Default: true.
	AllowJavaScript *bool `plist:"AllowJavaScript,omitempty" json:"AllowJavaScript,omitempty"`
	// If `false`, the system disables private browsing in Safari.
	//
	// Default: true.
	AllowPrivateBrowsing *bool `plist:"AllowPrivateBrowsing,omitempty" json:"AllowPrivateBrowsing,omitempty"`
	// If `false`, the system disables popups in Safari.
	//
	// Default: true.
	AllowPopups *bool `plist:"AllowPopups,omitempty" json:"AllowPopups,omitempty"`
	// If `false`, the system disables summarization of content in Safari.
	//
	// Default: true.
	AllowSummary *bool `plist:"AllowSummary,omitempty" json:"AllowSummary,omitempty"`
	// Sets the start page for new tabs in Safari.
	NewTabStartPage *SafariSettingsNewTabStartPage `plist:"NewTabStartPage,omitempty" json:"NewTabStartPage,omitempty"`
	// The dictionary of website privacy settings.
	Privacy *SafariSettingsPrivacy `plist:"Privacy,omitempty" json:"Privacy,omitempty"`
}

// SafariSettingsNewTabStartPage is the NewTabStartPage dictionary.
// Sets the start page for new tabs in Safari.
type SafariSettingsNewTabStartPage struct {
	// Sets the start page type in Safari:
	PageType SafariSettingsNewTabStartPagePageType `plist:"PageType" json:"PageType"`
	// The URL of the homepage which needs to start with `https://` or `http://`. Required when setting
	// `PageType` to `Home`.
	HomepageURL *string `plist:"HomepageURL,omitempty" json:"HomepageURL,omitempty"`
	// The composed identifier of the extension that provides the start page. The required format is
	// "Identifier (TeamIdentifier)", for example "com.example.app (ABCD1234)". Required when setting
	// `PageType` to `Extension`.
	ExtensionIdentifier *string `plist:"ExtensionIdentifier,omitempty" json:"ExtensionIdentifier,omitempty"`
}

// WebsiteDictionary is the ANY dictionary.
// The dictionary that defines the website privacy permission defaults. Each key represents a
// website.
type WebsiteDictionary struct {
	// Text that clearly explains to the Safari user the reason why the organization requires these
	// website privacy permission defaults. Safari includes this text in the permission consent prompt
	// it displays when it first displays the website.
	OrganizationJustification string `plist:"OrganizationJustification" json:"OrganizationJustification"`
	// Controls whether a website privacy permission default is set.
	Camera *WebsiteDictionaryCamera `plist:"Camera,omitempty" json:"Camera,omitempty"`
	// Controls whether a website privacy permission default is set.
	Microphone *WebsiteDictionaryMicrophone `plist:"Microphone,omitempty" json:"Microphone,omitempty"`
}

// SafariSettingsPrivacyPermissionDefaults is the PermissionDefaults dictionary.
// The dictionary of website permission defaults. Each key in the dictionary represents a single
// website, or a website and its sub-domains. The dictionary values represent the permission
// defaults that Safari applies for each website that matches the key.
type SafariSettingsPrivacyPermissionDefaults struct {
	// The dictionary that defines the website privacy permission defaults. Each key represents a
	// website.
	ANY *WebsiteDictionary `plist:"ANY,omitempty" json:"ANY,omitempty"`
}

// SafariSettingsPrivacy is the Privacy dictionary.
// The dictionary of website privacy settings.
type SafariSettingsPrivacy struct {
	// The dictionary of website permission defaults. Each key in the dictionary represents a single
	// website, or a website and its sub-domains. The dictionary values represent the permission
	// defaults that Safari applies for each website that matches the key.
	PermissionDefaults *SafariSettingsPrivacyPermissionDefaults `plist:"PermissionDefaults,omitempty" json:"PermissionDefaults,omitempty"`
}
