// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// SafariSettingsAcceptCookies — allowed values for SafariSettings.AcceptCookies.
type SafariSettingsAcceptCookies string

// SafariSettingsAcceptCookies allowed values.
const (
	SafariSettingsAcceptCookiesNever           SafariSettingsAcceptCookies = "Never"
	SafariSettingsAcceptCookiesCurrentWebsite  SafariSettingsAcceptCookies = "CurrentWebsite"
	SafariSettingsAcceptCookiesVisitedWebsites SafariSettingsAcceptCookies = "VisitedWebsites"
	SafariSettingsAcceptCookiesAlways          SafariSettingsAcceptCookies = "Always"
)

// String returns the SafariSettingsAcceptCookies value as a plain string.
func (e SafariSettingsAcceptCookies) String() string { return string(e) }

// SafariSettingsNewTabStartPagePageType — allowed values for SafariSettingsNewTabStartPage.PageType.
type SafariSettingsNewTabStartPagePageType string

// SafariSettingsNewTabStartPagePageType allowed values.
const (
	SafariSettingsNewTabStartPagePageTypeStart     SafariSettingsNewTabStartPagePageType = "Start"
	SafariSettingsNewTabStartPagePageTypeHome      SafariSettingsNewTabStartPagePageType = "Home"
	SafariSettingsNewTabStartPagePageTypeExtension SafariSettingsNewTabStartPagePageType = "Extension"
)

// String returns the SafariSettingsNewTabStartPagePageType value as a plain string.
func (e SafariSettingsNewTabStartPagePageType) String() string { return string(e) }
