// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// ScreensharingConnectionGroup — Screen Sharing:Connection Group.
// The declaration to configure a group of screen-sharing connections.
//
// Supported: macOS 14.0+.
type ScreensharingConnectionGroup struct {
	// A unique identifier for this connection group.
	ConnectionGroupUUID string `plist:"ConnectionGroupUUID" json:"ConnectionGroupUUID"`
	// The name of the connection group.
	GroupName string `plist:"GroupName" json:"GroupName"`
	// An array of `ConnectionUUID`s that represent connections declared in `ScreenSharingConnection`
	// configurations that are members of this group.
	Members []string `plist:"Members" json:"Members"`
}
