// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// ScreensharingHostSettings — Screen Sharing:Host Settings.
// The declaration to configure screen-sharing host settings and restrictions.
//
// Supported: macOS 14.0+.
type ScreensharingHostSettings struct {
	// The maximum number of virtual displays to make available to clients.
	MaximumVirtualDisplays *int64 `plist:"MaximumVirtualDisplays,omitempty" json:"MaximumVirtualDisplays,omitempty"`
	// The initial UDP port number to connect to the host. Screen sharing requires multiple
	// connections, so the system increments this value by 1 for each additional connection. This
	// doesn't change the port number that the system uses to initially establish a connection with a
	// host, which is always TCP port 5900.
	PortBase *int64 `plist:"PortBase,omitempty" json:"PortBase,omitempty"`
	// If `true`, the system prevents users from copying files from the screen-sharing host.
	//
	// Default: false.
	PreventCopyFilesFromHost *bool `plist:"PreventCopyFilesFromHost,omitempty" json:"PreventCopyFilesFromHost,omitempty"`
	// If `true`, the system prevents users from copying files to the screen-sharing host.
	//
	// Default: false.
	PreventCopyFilesToHost *bool `plist:"PreventCopyFilesToHost,omitempty" json:"PreventCopyFilesToHost,omitempty"`
	// If `true`, the system prevents clients from establishing high-performance connections to the
	// host.
	//
	// Default: false.
	PreventHighPerformanceConnections *bool `plist:"PreventHighPerformanceConnections,omitempty" json:"PreventHighPerformanceConnections,omitempty"`
}
