// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// DeclarationType returns the wire type identifier for ScreensharingConnection.
func (ScreensharingConnection) DeclarationType() string {
	return "com.apple.configuration.screensharing.connection"
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ScreensharingConnection) Validate() error {
	var errs []error
	if err := p.DisplayConfiguration.Validate(); err != nil {
		errs = append(errs, validate.Nested("DisplayConfiguration", err))
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ScreensharingConnectionDisplayConfiguration) Validate() error {
	var errs []error
	if err := validate.InList("DisplayType", p.DisplayType, []ScreensharingConnectionDisplayConfigurationDisplayType{ScreensharingConnectionDisplayConfigurationDisplayTypeVirtual1, ScreensharingConnectionDisplayConfigurationDisplayTypeVirtual2}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}
