// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// ScreensharingConnection — Screen Sharing:Connection.
// The declaration to configure a connection to a screen-sharing host.
//
// Supported: macOS 14.0+.
type ScreensharingConnection struct {
	// A unique identifier for this connection when it's in a connection group.
	ConnectionUUID string `plist:"ConnectionUUID" json:"ConnectionUUID"`
	// The name of the connection.
	DisplayName string `plist:"DisplayName" json:"DisplayName"`
	// The host name or IP address of the Mac that hosts the screen-sharing connection.
	HostName string `plist:"HostName" json:"HostName"`
	// The TCP port number on the host to initiate the connection.
	Port *int64 `plist:"Port,omitempty" json:"Port,omitempty"`
	// The display configuration for this connection.
	DisplayConfiguration ScreensharingConnectionDisplayConfiguration `plist:"DisplayConfiguration" json:"DisplayConfiguration"`
	// The identifier of an asset declaration that contains the required credentials for this
	// connection to authenticate with the screen-sharing server. Set the corresponding asset type to
	// `com.apple.asset.credential.userpassword`.
	//
	// Allowed asset types: com.apple.asset.credential.userpassword.
	AuthenticationCredentialsAssetReference *string `plist:"AuthenticationCredentialsAssetReference,omitempty" json:"AuthenticationCredentialsAssetReference,omitempty"`
}

// ScreensharingConnectionDisplayConfiguration is the DisplayConfiguration dictionary.
// The display configuration for this connection.
type ScreensharingConnectionDisplayConfiguration struct {
	// The type of display for the connection, which has these allowed values:
	DisplayType ScreensharingConnectionDisplayConfigurationDisplayType `plist:"DisplayType" json:"DisplayType"`
}
