// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

import (
	"errors"

	"github.com/deploymenttheory/go-api-sdk-apple/device_management/validate"
)

// DeclarationType returns the wire type identifier for ServicesBackgroundTasks.
func (ServicesBackgroundTasks) DeclarationType() string {
	return "com.apple.configuration.services.background-tasks"
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ServicesBackgroundTasks) Validate() error {
	var errs []error
	for i := range p.LaunchdConfigurations {
		if err := p.LaunchdConfigurations[i].Validate(); err != nil {
			errs = append(errs, validate.Indexed("LaunchdConfigurations", i, err))
		}
	}
	return errors.Join(errs...)
}

// Validate checks the payload against Apple's spec: required keys,
// allowed values, ranges, formats and nested payload keys.
func (p *ServicesBackgroundTasksLaunchdItem) Validate() error {
	var errs []error
	if err := validate.InList("Context", p.Context, []ServicesBackgroundTasksLaunchdItemContext{ServicesBackgroundTasksLaunchdItemContextDaemon, ServicesBackgroundTasksLaunchdItemContextAgent}); err != nil {
		errs = append(errs, err)
	}
	return errors.Join(errs...)
}
