// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// SiriSettings — Siri Settings.
// The declaration to configure Siri settings.
//
// Supported: iOS 26.4+, macOS 26.4+, visionOS 26.4+, watchOS 26.4+.
type SiriSettings struct {
	// If `false`, disables Siri.
	//
	// Default: true.
	Enabled *bool `plist:"Enabled,omitempty" json:"Enabled,omitempty"`
	// If `false`, disables Siri user-generated content.
	//
	// Default: true.
	AllowUserGeneratedContent *bool `plist:"AllowUserGeneratedContent,omitempty" json:"AllowUserGeneratedContent,omitempty"`
	// If `false`, disables Siri while locked.
	//
	// Default: true.
	AllowWhileLocked *bool `plist:"AllowWhileLocked,omitempty" json:"AllowWhileLocked,omitempty"`
	// If `true`, forces Siri profanity filter.
	//
	// Default: false.
	ForceProfanityFilter *bool `plist:"ForceProfanityFilter,omitempty" json:"ForceProfanityFilter,omitempty"`
}
