// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// DeclarationType returns the wire type identifier for SiriSettings.
func (SiriSettings) DeclarationType() string { return "com.apple.configuration.siri.settings" }

// Validate checks the payload against Apple's spec. SiriSettings has no
// constraints beyond its field types.
func (p *SiriSettings) Validate() error { return nil }
