// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// SoftwareupdateSettings — Software Update:Settings.
// The declaration to configure software updates.
//
// Supported: iOS 18.0+, macOS 15.0+, tvOS 18.4+, visionOS 26.0+.
type SoftwareupdateSettings struct {
	// If set to `true`, the device shows all software update enforcement notifications.
	//
	// Default: true.
	Notifications *bool `plist:"Notifications,omitempty" json:"Notifications,omitempty"`
	// This object configures the deferral of software updates. Background Security Improvements aren't
	// considered in `Major`, `Minor`, or `System` deferral mechanism.
	Deferrals *SoftwareupdateSettingsDeferrals `plist:"Deferrals,omitempty" json:"Deferrals,omitempty"`
	// This string specifies how the device shows software updates to the user. When more than one
	// update is available update, the device behaves as follows:
	RecommendedCadence *SoftwareupdateSettingsRecommendedCadence `plist:"RecommendedCadence,omitempty" json:"RecommendedCadence,omitempty"`
	// This object configures various automatic Software Update functionality.
	AutomaticActions *SoftwareupdateSettingsAutomaticActions `plist:"AutomaticActions,omitempty" json:"AutomaticActions,omitempty"`
	// These configurations set user access to interacting with Background Security Improvement.
	RapidSecurityResponse *SoftwareupdateSettingsRapidSecurityResponse `plist:"RapidSecurityResponse,omitempty" json:"RapidSecurityResponse,omitempty"`
	// If set to `true`, a standard user can perform Major and Minor Software Updates.
	//
	// Default: true.
	AllowStandardUserOSUpdates *bool `plist:"AllowStandardUserOSUpdates,omitempty" json:"AllowStandardUserOSUpdates,omitempty"`
	// This object configures the beta program settings for a device.
	Beta *SoftwareupdateSettingsBeta `plist:"Beta,omitempty" json:"Beta,omitempty"`
}

// SoftwareupdateSettingsDeferrals is the Deferrals dictionary.
// This object configures the deferral of software updates. Background Security Improvements aren't
// considered in `Major`, `Minor`, or `System` deferral mechanism.
type SoftwareupdateSettingsDeferrals struct {
	// Specifies the number of days to defer a major or minor OS software update on the device. When
	// set, software updates only appear after the specified delay, following the release of the
	// software update. Available in iOS 18 and later.
	CombinedPeriodInDays *int64 `plist:"CombinedPeriodInDays,omitempty" json:"CombinedPeriodInDays,omitempty"`
	// Specifies the number of days to defer a major OS software update on the device. When set,
	// software updates only appear after the specified delay, following the release of the software
	// update. Available in macOS 15 and later.
	MajorPeriodInDays *int64 `plist:"MajorPeriodInDays,omitempty" json:"MajorPeriodInDays,omitempty"`
	// Specifies the number of days to defer a minor OS software update on the device. It also defers
	// major updates for iOS. When set, software updates only appear after the specified delay,
	// following the release of the software update. Available in macOS 15 and later.
	MinorPeriodInDays *int64 `plist:"MinorPeriodInDays,omitempty" json:"MinorPeriodInDays,omitempty"`
	// Specifies the number of days to defer system or non-OS updates. When set, updates only appear
	// after the specified delay, following the release of the update. Available in macOS 15 and later.
	SystemPeriodInDays *int64 `plist:"SystemPeriodInDays,omitempty" json:"SystemPeriodInDays,omitempty"`
}

// SoftwareupdateSettingsAutomaticActions is the AutomaticActions dictionary.
// This object configures various automatic Software Update functionality.
type SoftwareupdateSettingsAutomaticActions struct {
	// Specifies whether the user can control automatic downloads of available updates:
	//
	// Default: Allowed.
	Download *SoftwareupdateSettingsAutomaticActionsDownload `plist:"Download,omitempty" json:"Download,omitempty"`
	// Specifies whether the user can control automatic installation of available updates:
	//
	// Default: Allowed.
	InstallOSUpdates *SoftwareupdateSettingsAutomaticActionsInstallOSUpdates `plist:"InstallOSUpdates,omitempty" json:"InstallOSUpdates,omitempty"`
	// Specifies whether the user can control automatic installation of available security updates:
	//
	// Default: Allowed.
	InstallSecurityUpdate *SoftwareupdateSettingsAutomaticActionsInstallSecurityUpdate `plist:"InstallSecurityUpdate,omitempty" json:"InstallSecurityUpdate,omitempty"`
}

// SoftwareupdateSettingsRapidSecurityResponse is the RapidSecurityResponse dictionary.
// These configurations set user access to interacting with Background Security Improvement.
type SoftwareupdateSettingsRapidSecurityResponse struct {
	// If set to `false`, Background Security Improvements aren't offered for user installation. The
	// system can still install Background Security Improvements with
	// `com.apple.configuration.softwareupdate.enforcement.specific` configurations.
	//
	// Default: true.
	Enable *bool `plist:"Enable,omitempty" json:"Enable,omitempty"`
	// If set to `false`, the system doesn't offer Background Security Improvement rollbacks to the
	// user.
	//
	// Default: true.
	EnableRollback *bool `plist:"EnableRollback,omitempty" json:"EnableRollback,omitempty"`
}

// SoftwareupdateSettingsBetaProgram is the Program dictionary.
// The name and token associated with a specific beta program to be allowed.
type SoftwareupdateSettingsBetaProgram struct {
	// A human readable description of the beta program.
	Description string `plist:"Description" json:"Description"`
	// The Apple Business Manager or Apple School Manager seeding service token for the organization
	// the MDM server is part of. The system uses this token to enroll the device in the corresponding
	// beta program.
	Token string `plist:"Token" json:"Token"`
}

// SoftwareupdateSettingsBetaRequireProgram is the RequireProgram dictionary.
// The device automatically enrolls in this beta program. This key must only be present if the
// `ProgramEnrollment` key is set to `AlwaysOn`. The `OfferPrograms` key must not be present if
// this key is present.
type SoftwareupdateSettingsBetaRequireProgram struct {
	// A human readable description of the beta program.
	Description string `plist:"Description" json:"Description"`
	// The Apple Business Manager or Apple School Manager seeding service token for the organization
	// the MDM server is part of. The system uses this token to enroll the device in the corresponding
	// beta program.
	Token string `plist:"Token" json:"Token"`
}

// SoftwareupdateSettingsBeta is the Beta dictionary.
// This object configures the beta program settings for a device.
type SoftwareupdateSettingsBeta struct {
	// Specifies whether the user can control beta program enrollment in the software update settings
	// UI:
	//
	// Default: Allowed.
	ProgramEnrollment *SoftwareupdateSettingsBetaProgramEnrollment `plist:"ProgramEnrollment,omitempty" json:"ProgramEnrollment,omitempty"`
	// An array of beta programs allowed on the device. This key must only be present if the
	// `ProgramEnrollment` key is set to `Allowed` or `AlwaysOn`. This key must not be present if the
	// `RequireProgram` key is present. This key can be present on unsupervised devices where the
	// `ProgramEnrollment` key isn't supported but is implicitly set to `Allowed`.
	OfferPrograms []SoftwareupdateSettingsBetaProgram `plist:"OfferPrograms,omitempty" json:"OfferPrograms,omitempty"`
	// The device automatically enrolls in this beta program. This key must only be present if the
	// `ProgramEnrollment` key is set to `AlwaysOn`. The `OfferPrograms` key must not be present if
	// this key is present.
	RequireProgram *SoftwareupdateSettingsBetaRequireProgram `plist:"RequireProgram,omitempty" json:"RequireProgram,omitempty"`
}
