// Code generated by go-api-sdk-apple-dm-codegen. DO NOT EDIT.

package configurations

// DeclarationType returns the wire type identifier for WatchEnrollment.
func (WatchEnrollment) DeclarationType() string { return "com.apple.configuration.watch.enrollment" }

// Validate checks the payload against Apple's spec. WatchEnrollment has no
// constraints beyond its field types.
func (p *WatchEnrollment) Validate() error { return nil }
